### ISSUE TITLE
[Android ] Request to add tab swipe

### ISSUE THREAD

**Issue by wajidareeb** [wanghongenpin/network_proxy_flutter#100]
I wanted to suggest adding tab swipe functionality to this app. 
Tab swipe allows users to seamlessly navigate between different tabs by simply swiping horizontally.

**Comment by wanghongenpin** [comment]
Is the packet capture details page [Request, Response, Cookie] tab swiping?

**Comment by wajidareeb** [comment]
Yes

**Comment by wanghongenpin** [comment]
1.0.7-Beta Supported tab swipe 
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/1.0.7-Beta
