### ISSUE TITLE
希望能够添加对js脚本临时数据存储的支持

### ISSUE THREAD

**Issue by FeiZhaixiage** [wanghongenpin/network_proxy_flutter#102]
**您的功能请求是否与问题有关？请描述.**
我在实际使用当中发现有些时候网络请求包它分为好几个，其中在一个get请求获取一些参数之后，需要利用这个参数进行计算或查库才能进行第二次发送，但是本软件的js脚本并不能处理这种情况，它不能将第一次抓包下来的参数传递到第二次抓包里。
我尝试去使用js中的
localStorage.setItem，localStorage.getItem来达到传送参数到其他js脚本的方案，可是本软件并不支持localStorage

**描述您想要的解决方案**
所以我希望能够添加对临时变量存储的支持，或者能有方式去传递这些数据到其他js脚本内。
实现方式可能为添加临时变量存储池好让js脚本去访问，对于不同脚本之间的隐私问题，可对不同脚本分组，相同组内的脚本能够互相访问内容，不相同组不能够跨组访问。
能够能够实现，感谢开发者。

**Comment by wanghongenpin** [comment]
context增加个session字段, var session = {}, 应用运行期间共用一个session。
context.session['key'] = 'val';

这样是否可行

**Comment by wanghongenpin** [comment]
最新包已经支持了
> 可行，希望开发者能够支持此功能。感谢贡献。
