### ISSUE TITLE
[Android]不能很好的支持中文或者相关的符号

### ISSUE THREAD

**Issue by Mr9357** [wanghongenpin/network_proxy_flutter#105]
很多抓包请求都是写了%xx%xx这种新式，有些原本是符号和中文的，重发后也变成了这种形式。这个应该是编码不正确的问题吧![Screenshot_2024-01-07-15-28-01-75_04e63bc7959998aa186ce9fdd3b40c8f.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/89758772/29f64c53-8d71-4749-9b7a-cf1e51000e3e)

**Comment by wanghongenpin** [comment]
header一般都是 ASCII 编码，中文一般用其他编码处理过，你这个是使用url编码过吧？

**Comment by wanghongenpin** [comment]
本软件对header没有做过任何特殊编码处理

**Comment by Mr9357** [comment]
我没有做做什么处理哦，原本是符号或者中文之类的，重发后，新的请求里面就是这种%类型

**Comment by wanghongenpin** [comment]
发下原始curl

**Comment by Mr9357** [comment]
不懂curl怎么弄额，截图可以吗，第一张是抓包下来的，第二张是点编辑重发，软件自动载入的。划线部分开始被改变了
![IMG_20240107_202422.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/89758772/081ab602-10c1-4624-aba1-a19e106221c5)

![IMG_20240107_202455.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/89758772/0afbe969-33f3-4898-92d2-14531ce9ccbb)

**Comment by wanghongenpin** [comment]
你这个是表单不是header，表单都是URL编码过的，在抓包详情页，那个tab是decode过的，在编辑重发是展示原始文本，原始文本都是url编码过的
