### ISSUE TITLE
编辑重放后，主页里不生成请求条目

### ISSUE THREAD

**Issue by Mr9357** [wanghongenpin/network_proxy_flutter#106]
直接重放会生成一个新的抓包请求条目，而编辑重放的，不会有新的条目生成，只在编辑重放那个页面能看到响应，返回后就没有记录了，希望能有记录，方便多次查看

**Comment by wanghongenpin** [comment]
手机端有，桌面端取的系统代理，打开抓包软件后就能看到

**Comment by Mr9357** [comment]
我是安卓端的最新版客户端，重发有，编辑重发没有

**Comment by wanghongenpin** [comment]
开启抓包就有了，这里编辑重发是根据开启抓包走的

> 我是安卓端的最新版客户端，重发有，编辑重发没有

**Comment by Mr9357** [comment]
试了，确实要开启抓包才行，谢谢了
