### ISSUE TITLE
软件无法进行二级搜索

### ISSUE THREAD

**Issue by lucc1832** [wanghongenpin/network_proxy_flutter#107]
抓包后 点击搜索只能进行一级搜索，但我只需要这个包里的其中一个数据一个一个去找就会很麻烦，希望加个2级搜索，这样搜其中一个变量就很快能出来了

**Comment by wanghongenpin** [comment]
什么是二级搜索

**Comment by lucc1832** [comment]
比如就像图片上的 我只需要accesstoken的数据，但我只能一个一个点击查看， 在主页搜索只能是 首页抓包的网址要么是接口，不能进行二级搜索。
![微信图片_20240107223247](https://github.com/wanghongenpin/network_proxy_flutter/assets/58016883/faa1b6cf-7eb6-45c8-a975-d8e7afd12394)

**Comment by wanghongenpin** [comment]
点击搜索icon会出现复杂搜索条件

**Comment by lucc1832** [comment]
你好 ，我尝试过了 ，复杂搜索条件一样是搜索的请求头 url 啥的 依旧不能搜索里面的变量， 假如链接里的变量数据名怎么搜索呢
![微信图片_20240107223247](https://github.com/wanghongenpin/network_proxy_flutter/assets/58016883/8323da1d-df61-4882-a454-c643bd22297b)
正如图片中的一样 ，我不知到url是什么 只是想抓取一个变量

**Comment by lucc1832** [comment]
你好 ，我尝试过了 ，复杂搜索条件一样是搜索的请求头 url 啥的 依旧不能搜索里面的变量， 假如链接里的变量数据名怎么搜索呢
![Uploading 微信图片_20240107224438.jpg…]()

正如图片中的一样 ，我不知到url是什么 只是想抓取一个变量

**Comment by lucc1832** [comment]
![微信图片_20240107224438](https://github.com/wanghongenpin/network_proxy_flutter/assets/58016883/8e6e342a-da62-46b8-9424-adaf22076c60)
你好 ，我尝试过了 ，复杂搜索条件一样是搜索的请求头 url 啥的 依旧不能搜索里面的变量， 假如链接里的变量数据名怎么搜索呢

正如图片中的一样 ，我不知到url是什么 只是想抓取一个变量

**Comment by lucc1832** [comment]
我用图片可能更好的给你解释 ，我的词可能用的不专业，差不多就类似于网页中的二级标题， 但搜索一样能包括进去。
![微信图片_20240107225402](https://github.com/wanghongenpin/network_proxy_flutter/assets/58016883/17cd0938-afea-4e02-a7bc-f797d8bcc01c)

**Comment by wanghongenpin** [comment]
你好，安卓刚重新打了个包，之前header应该只搜索了value，现在把key也加上了，1.0.7重新下载下就好了

**Comment by wanghongenpin** [comment]
下载最新包 已经解决
