### ISSUE TITLE
[Android] 深色模式 WebSocket 亮色底 白色字 看不清

### ISSUE THREAD

**Issue by TimeRainStarSky** [wanghongenpin/network_proxy_flutter#115]
**描述错误**
深色模式 WebSocket 亮色底 白色字 看不清
**To Reproduce**
打开深色模式，抓包 WebSocket，转到 WebSocket 栏
**屏幕截图*
![Screenshot_2024-01-17-00-40-00-446_com network proxy](https://github.com/wanghongenpin/network_proxy_flutter/assets/63490117/4477b731-3237-4a2f-8621-1e479f5475c0)

**Comment by wanghongenpin** [comment]
V1.0.8-Beta 已经修改

https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.0.8-Beta
