### ISSUE TITLE
json解析格式缩进能不能改为4个空格，2个空格不好分辨

### ISSUE THREAD

**Issue by iven98** [wanghongenpin/network_proxy_flutter#116]
**您的功能请求是否与问题有关？请描述.**
对问题所在的清晰简洁的描述[...]

**描述您想要的解决方案**
对你想要发生的事情进行清晰简洁的描述.

**附加上下文**

**Comment by wanghongenpin** [comment]
桌面端还是手机端，手机端屏幕小，层级太深会导致很多换行

**Comment by iven98** [comment]
桌面端



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月20日 12:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wanghongenpin/network_proxy_flutter] json解析格式缩进能不能改为4个空格，2个空格不好分辨 (Issue #116) |

桌面端还是手机端，手机端屏幕小，层级太深会导致很多换行

**Comment by wanghongenpin** [comment]
V1.0.8-Beta 已经修改

https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.0.8-Beta
