### ISSUE TITLE
希望增加提交数据和返回数据16位复制的按钮和查看

### ISSUE THREAD

**Issue by bianyuan456** [wanghongenpin/network_proxy_flutter#12]
Content-Type: application/proto
当协议头的Content-Type 是这种时，提交数据和返回数据不是纯文本形式的，希望再增加16位数据的查看或者base64位编码来方便复制到电脑端去解析。

**Comment by wanghongenpin** [comment]
这几天处理下

**Comment by wanghongenpin** [comment]
做了个简版16进制展示，最新版包已经更新
<img width="868" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/fa798923-21f5-4ef7-825f-836d71eb3e9e">

**Comment by bianyuan456** [comment]
感谢更新！挺好的！看来flutter开发真是神速呀！昨天提issue，今天就更新完了。。。
testflight也是推送神速，更新完了能马上推、不用怎么审核。。
