### ISSUE TITLE
历史记录希望能够自动保存

### ISSUE THREAD

**Issue by lvzhenbo** [wanghongenpin/network_proxy_flutter#122]
**您的功能请求是否与问题有关？请描述.**
功能叫历史记录不是保存记录，没有自动保存也太费劲了

**描述您想要的解决方案**
将手动保存改为自动保存

**附加上下文**
终于有人做高版本适配的抓包软件了，建议参照小黄鸟，这个软件功能很全也很成熟就是不更新了

**Comment by wanghongenpin** [comment]
V1.0.8-Beta 历史记录支持自动缓存时间设置

https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.0.8-Beta
