### ISSUE TITLE
Android
工具箱里base两边都是编码

### ISSUE THREAD

**Issue by hixanny** [wanghongenpin/network_proxy_flutter#124]
**描述错误(Describe the bug)**
工具箱里两边都是编码

**To Reproduce**
右上角➕进入工具箱，base64![Screenshot_2024-01-29-07-24-10-184_com.network.proxy.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/34408263/ac563086-d743-4969-b28c-d38f31e3d0d8)

右边的文字应该是解码

**屏幕截图(Screenshots)*

**Comment by wanghongenpin** [comment]
V1.0.8-Beta版本已解决
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.0.8-Beta
