### ISSUE TITLE
王者营地app开了抓包后就无法获取数据了，这个有办法处理吗

### ISSUE THREAD

**Issue by Xaw-xu** [wanghongenpin/network_proxy_flutter#126]
**描述错误(Describe the bug)**

**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面

**屏幕截图(Screenshots)*

**Comment by wanghongenpin** [comment]
抓应用需要你自己研究，如果是抓包软件本身问题可以反馈
