### ISSUE TITLE
[Android]请求重写功能好像会自己重写自己，然后无限重发？

### ISSUE THREAD

**Issue by pinoren** [wanghongenpin/network_proxy_flutter#128]
**描述错误(Describe the bug)**
建立重写规则后，APP抓到了对应的包，好像会无限自己重写自己这个包然后重发，形成死循环？必须立即暂停抓包才能停止下来。
**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面
从已捕获的数据包建立重写规则，并替换响应体，就会产生这么一个效果。替换响应头似乎不会如此。
**屏幕截图(Screenshots)*
暂无。

**Comment by wanghongenpin** [comment]
无法复现，有视频和curl请求吗？

**Comment by wanghongenpin** [comment]
长时间无反馈先关了，有进展可以重新打开
