### ISSUE TITLE
请求列表优化建议

### ISSUE THREAD

**Issue by MrMoxing** [wanghongenpin/network_proxy_flutter#129]
请求列表能显示应用图标，并且优化类型显示，现在的太不突出了

**Comment by M17764017422** [comment]
合并请求#36

**Comment by wanghongenpin** [comment]
类型显示不是已经有icon了吗

**Comment by wanghongenpin** [comment]
1.0.9-Beta版本已经支持应用图标展示

https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/1.0.9-Beta
