### ISSUE TITLE
[Android]页面上滑，会侧滑到另一项

### ISSUE THREAD

**Issue by MrMoxing** [wanghongenpin/network_proxy_flutter#130]
**描述错误(Describe the bug)**

请求详情页面，上滑内容，有概率会侧滑到另一项

**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面

**屏幕截图(Screenshots)*
https://github.com/wanghongenpin/network_proxy_flutter/assets/81543605/c5932c0d-3e53-490a-883b-47939ed5b3ee

**Comment by wanghongenpin** [comment]
这个是左右滑动切换tab

**Comment by MrMoxing** [comment]
> 这个是左右滑动切换tab

但是我是上滑屏幕，他为什么会左右滑

**Comment by zzt0504** [comment]
我认为也是，灵敏度过高，希望可以稍稍低点，谢谢!

**Comment by wanghongenpin** [comment]
处理了下，试下这个包呢，我自测几乎不会出现了
https://www.lanzoub.com/irTot1r7k1re
密码:b33n

**Comment by wanghongenpin** [comment]
可以下载1.0.9-Beta版本，已经处理
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/1.0.9-Beta
