### ISSUE TITLE
[Android]掉小窗

### ISSUE THREAD

**Issue by MrMoxing** [wanghongenpin/network_proxy_flutter#137]
**描述错误(Describe the bug)**

小窗模式划掉后台卡片小窗会直接掉

**To Reproduce**
当后台仅剩一个任意卡片，且划掉时，会把应用的小窗杀掉

**屏幕截图(Screenshots)*
https://github.com/wanghongenpin/network_proxy_flutter/assets/81543605/dc05f66d-ff6e-474e-895d-c20acbc9be17

**Comment by M17764017422** [comment]
锁定后台就可以了
