### ISSUE TITLE
优化应用列表读取速度

### ISSUE THREAD

**Issue by MrMoxing** [wanghongenpin/network_proxy_flutter#138]
现在这个读取速度真的太慢了，6，7 秒才能加载出来，还只能单选，每选一个就需要等 6，7 秒

https://github.com/wanghongenpin/network_proxy_flutter/assets/81543605/d7f3016a-5e05-434a-b992-ef447ccb881f

**Comment by wanghongenpin** [comment]
只有首次加载才会慢吧，读取了一次做了缓存，后面就快了

**Comment by MrMoxing** [comment]
> 只有首次加载才会慢吧，读取了一次做了缓存，后面就快了

重启还需要再次加载，这个能不能读取上次缓存的列表，顶部加刷新按钮

**Comment by M17764017422** [comment]
> 只有首次加载才会慢吧，读取了一次做了缓存，后面就快了

缓存只对本次启动有效，一旦重启就要重新读取

**Comment by M17764017422** [comment]
> > 只有首次加载才会慢吧，读取了一次做了缓存，后面就快了
> 
> 重启还需要再次加载，这个能不能读取上次缓存的列表，顶部加刷新按钮

不建议增加刷新按钮，可以放在后台加载，前台先用以前的数据，加载后如果数据有更新再动态同步到前台

**Comment by wanghongenpin** [comment]
1.0.8最新包改成了多线程解析app详情，速度会快很多
