### ISSUE TITLE
小米安全中心报毒

### ISSUE THREAD

**Issue by zhangheng2022** [wanghongenpin/network_proxy_flutter#139]
![Screenshot_2024-02-24-23-19-24-713_com.miui.securitycenter.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/17758261/5178e15e-7f27-417e-8062-b180ad8c84a8)

**Comment by wanghongenpin** [comment]
本软件绝对没有病毒，纯本地软件，已经找腾讯提出申诉

**Comment by wanghongenpin** [comment]
下载最新包再试下呢

**Comment by MoFly5201314** [comment]
自己从新签名就没事了

**Comment by wanghongenpin** [comment]
最新包我试了扫描也没提示病毒
