### ISSUE TITLE
[Mac] 抓包没生效

### ISSUE THREAD

**Issue by renweiXu** [wanghongenpin/network_proxy_flutter#141]
开启了抓包扫描，但是没有任何包被抓取到，使用的是mac版本的

=
![161709255190_ pic](https://github.com/wanghongenpin/network_proxy_flutter/assets/41334875/118bcb70-36f5-490f-8ecf-bd156352d6d9)

**Comment by renweiXu** [comment]
证书也配置了，也完全信任了，每一步都是按照视频来的，难道是还有什么开关没打开，在iphone上抓包是可以的

**Comment by wanghongenpin** [comment]
> 证书也配置了，也完全信任了，每一步都是按照视频来的，难道是还有什么开关没打开，在iphone上抓包是可以的

手机wifi配置代理电脑上可以看到请求吗，就和Charles那样

**Comment by renweiXu** [comment]
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/41334875/dbd8adda-3284-424d-9c15-d558e70d124a)
如图，没有，访问百度 github 很多网页 都没有抓取到

**Comment by renweiXu** [comment]
![Uploading 181709274791_.pic.jpg…]()

**Comment by renweiXu** [comment]
不好意思 ，我才知道 按照你说的 连同一wifi，手机扫描mac端上的二维码，抓取的是 手机端上的 网络请求包，实际上我想抓取的是mac端的网络请求包

**Comment by wanghongenpin** [comment]
<img width="652" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/2748c1d8-e098-4c63-923d-191d89140684">
你有用其它VPN软件吗，Wifi代理一定得是抓包的端口号，如果有VPN软件会冲突。如果WIFI代理正确，抓包软件HTTPS打开，域名过滤不要开启白名单。

我也有看见别人遇到过重启下浏览器就好了，首次才会这样。

**Comment by wanghongenpin** [comment]
如果还有问题，私聊我TG或者B站吧，这上面沟通效率太低，理论上应该是没问题

**Comment by renweiXu** [comment]
好的

**Comment by renweiXu** [comment]
还是有点不行&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wanghongenpin/network_proxy_flutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月11日(星期一) 晚上9:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wanghongenpin/network_proxy_flutter] [Mac] 抓包没生效 (Issue #141)





 
如果还有问题，私聊我TG或者B站吧，这上面沟通效率太低，理论上应该是没问题
