### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by skyfile** [wanghongenpin/network_proxy_flutter#142]
能有一个自动转发的功能，就是指定某些域名的请求可以指定配置采集地址，在请求完成之后，将请求和响应一同转发到指定的地址web接口。

有时候需要做些自动采集的事情，比如有些请求并不好破解加密方法，只能是手动收集这些信息。

**Comment by wanghongenpin** [comment]
可以使用脚本实现

**Comment by wanghongenpin** [comment]
太过于自定义，暂不考虑实现功能，用脚本可以快速实现
