### ISSUE TITLE
[iOS]开启抓包没有vpn标识，暂停抓包后再开抓包页面会显示无法连接服务器

### ISSUE THREAD

**Issue by watercatmiao** [wanghongenpin/network_proxy_flutter#146]
**描述错误(Describe the bug)**
开启抓包没有vpn标识，暂停抓包后再开抓包页面会显示无法连接服务器
**To Reproduce**
重现行为的步骤: 开启抓包后状态栏没有vpn标识，但是可以正常抓包。暂停抓包，过一会再开启抓包，刷新页面会出现打不开网页的问题

**屏幕截图(Screenshots)**
![微信图片_20240307155228]
没有显示vpn
(https://github.com/wanghongenpin/network_proxy_flutter/assets/20806422/6c564d55-1cac-4726-afd4-c35dae6dc55f)
网页打不开
![微信图片_20240307155234](https://github.com/wanghongenpin/network_proxy_flutter/assets/20806422/76c604c2-7290-4716-8793-7a2d1fa8100c)
![微信图片_20240307155238](https://github.com/wanghongenpin/network_proxy_flutter/assets/20806422/9770268d-20a0-4073-987f-596372e6f68a)
**设备**
iPhone 7Plus iOS15.6

**Comment by wanghongenpin** [comment]
TF V1.1.2版本最新报已经解决
