### ISSUE TITLE
[ios] 抓包抖音

### ISSUE THREAD

**Issue by dcsunny** [wanghongenpin/network_proxy_flutter#147]
想抓包抖音app的https请求，但是全都失败，这个能解决吗？

**Comment by wanghongenpin** [comment]
你试下其他抓包软件好使不，如果不行，可能抖音做了证书验证。

**Comment by SeaRat** [comment]
不用试了，我用安卓一样不行，抖音内置了证书，连系统证书都不信任

**Comment by SeaRat** [comment]
不用试了，我用安卓一样不行，抖音内置了证书，连系统证书都不信任
