### ISSUE TITLE
安卓13 proxywin1.08 root magisk证书包已安装

### ISSUE THREAD

**Issue by pope-L** [wanghongenpin/network_proxy_flutter#150]
捕捉不到任何流量

黑白名单都关了，应用名单也清空了

补充，这里投诉后，再次开启捕捉，居然一切正常了  为何？这软件也怕给爸爸投诉吗？

**Comment by T0sng** [comment]
软件本身并无涉及商业行为，何来“投诉”一说。

**Comment by wanghongenpin** [comment]
可能有些缓存啥的。
本软件是纯本地软件，除了转发流量，其他不会和任何远程服务交互。

**Comment by pope-L** [comment]
> 软件本身并无涉及商业行为，何来“投诉”一说。
说笑而已 ，就是转身发个贴就好了
