### ISSUE TITLE
增加长按进行请求重写和请求屏蔽以及注入脚本的功能

### ISSUE THREAD

**Issue by pingping666** [wanghongenpin/network_proxy_flutter#152]
想要增加长按进行请求重写和请求屏蔽以及注入脚本的功能，这样就不用手动在侧边栏输入url了，就像httpcanary一样，只需要长按然后点击就能自动填入url，然后设置重写内容或是否屏蔽

![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/135102138/f823b372-b719-48cd-be73-86ffa4c85ee8)

**Comment by wanghongenpin** [comment]
现在的菜单太多，影响美观，请求屏蔽和脚本感觉使用率都比较低，可以手动复制URL。
因为重写会填充body体，在详情页做了icon快速重写填充

**Comment by pingping666** [comment]
> 现在的菜单太多，影响美观，请求屏蔽和脚本感觉使用率都比较低，可以手动复制URL。 因为重写会填充body体，在详情页做了icon快速重写填充

好吧~_~，因为我用的手机重写，不像Windows有多窗口可以先复制url再复制body，所以每次要先放到一个文本里面，所以觉得一丢麻烦

**Comment by wanghongenpin** [comment]
重写可以点击详情页icon 会自动填充URL和body
<img width="319" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/1646e187-4667-4e52-a4b3-9129fe9d5d13">

**Comment by pingping666** [comment]
> 重写可以点击详情页icon 会自动填充URL和body <img alt="image" width="319" src="https://private-user-images.githubusercontent.com/24794200/312295425-1646e187-4667-4e52-a4b3-9129fe9d5d13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDAwMTYsIm5iZiI6MTcxMDI5OTcxNiwicGF0aCI6Ii8yNDc5NDIwMC8zMTIyOTU0MjUtMTY0NmUxODctNDY2Ny00ZTUyLWE0YjMtOTEyOWZlOWQ1ZDEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAzMTUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5MTNhOTk3Y2RhMjJmYTZmODUyNDBkMGIxZTYzYTYxNWE0YzRmZTE0ZDhjODNlOTcyZTY3Mjg5ZDMwNWRkYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HQnVFC_qH5kONVXO413gB1hHU_8S532Rb0tXe3rsMvU">

对不起，之前没注意到，这挺好的👌🏻，不过填充url的时候端口没有加冒号
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/135102138/26781556-6e43-40e7-91f8-cf745e4d2d3b)

**Comment by wanghongenpin** [comment]
应该不会，发下curl

> 对不起，之前没注意到，这挺好的👌🏻，不过填充url的时候端口没有加冒号

**Comment by wanghongenpin** [comment]
如果后续发现填充URL不对，可以重新打开
