### ISSUE TITLE
怎么指定应用呢

### ISSUE THREAD

**Issue by SiMaLaoShi** [wanghongenpin/network_proxy_flutter#154]
**您的功能请求是否与问题有关？请描述.**
对问题所在的清晰简洁的描述[...]

**描述您想要的解决方案**
对你想要发生的事情进行清晰简洁的描述.

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by kkopmm** [comment]
过滤-应用白名单

**Comment by SiMaLaoShi** [comment]
太强了大佬
