### ISSUE TITLE
关于mac使用白板

### ISSUE THREAD

**Issue by walingcc** [wanghongenpin/network_proxy_flutter#158]
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/37326329/7c502583-c1b2-4bef-be1a-087614bf9a25)
系统证书已经安装，mac打开白板，什么也没抓到

**Comment by soxft** [comment]
同遇

**Comment by wanghongenpin** [comment]
https开启了吗，还有看下wifi代理配置有没有只想成抓包的端口

**Comment by soxft** [comment]
我也遇到了类似的问题， 发现是因为同时开启了 其余的代理软件， 关掉就行了

**Comment by wanghongenpin** [comment]
检查代理是否设置是本软件端口，如果有其他VPN软件可能会出现覆盖，可以使用外部代理转发vpn软件
