### ISSUE TITLE
Mac 停止抓包以后仍然在抓包

### ISSUE THREAD

**Issue by CncCbz** [wanghongenpin/network_proxy_flutter#163]
**描述错误(Describe the bug)**
停止抓包以后，仍然在抓包
**To Reproduce**
1、开始抓包
2、停止抓包
3、发现停止后仍然在抓包
**屏幕截图(Screenshots)*

https://github.com/wanghongenpin/network_proxy_flutter/assets/43227065/37303ae1-c41d-45e5-9378-bc6fce410a41

**Comment by wanghongenpin** [comment]
有些应用可能做了代理缓存，抓包软件本身没发解决，最多不显示
