### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Mr9357** [wanghongenpin/network_proxy_flutter#165]
画中画这个bug好久了。

重现步骤：先点开始抓包，返回桌面进画中画，再进软件暂停抓包，又点击开始抓包，再返回桌面进画中画

![Screenshot_2024-03-23-14-13-29-52_04e63bc7959998aa186ce9fdd3b40c8f.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/89758772/e696180e-bf94-4ff7-88d1-b84101d3e113)

**Comment by wanghongenpin** [comment]
可以试下1.0.9版本是否还有问题
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/1.0.9-Beta

**Comment by Mr9357** [comment]
下载下来依然是1.0.8版

**Comment by wanghongenpin** [comment]
版本号没修改，新版本还有问题吗，我自己测试没办法复现
> 下载下来依然是1.0.8版

**Comment by Mr9357** [comment]
依然存在问题![Screenshot_2024-03-26-08-57-05-70_04e63bc7959998aa186ce9fdd3b40c8f.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/89758772/9d907538-4c02-4ff2-9c74-0439e8567c96)

**Comment by Mr9357** [comment]
并且抓包的时候，小窗口有可能不显示抓包内容，要点进去才能看到

**Comment by gentlemanxzh** [comment]
> 并且抓包的时候，小窗口有可能不显示抓包内容，要点进去才能看到

什么机型，Android版本是多少？

**Comment by Mr9357** [comment]
OPPO Reno5K
Android 11

**Comment by gentlemanxzh** [comment]
> OPPO Reno5K Android 11
我试着改了一下，重新打了个包，你试试还会不会
链接：https://pan.baidu.com/s/1BYC-l8kClf6d7rkd4e6h4A?pwd=7ozf 
提取码：7ozf 
--来自百度网盘超级会员V5的分享

如果还会的话，我在侧滑菜单加了个Debug日志，你可以把日志发出来看看
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/31216074/f1d7c1eb-8c54-4d89-b1ea-95e3702e1423)

**Comment by Mr9357** [comment]
你直接发在github上，我下载都比百度云快😂

**Comment by gentlemanxzh** [comment]
> 你直接发在github上，我下载都比百度云快😂

我在评论里传不了APK文件~~

**Comment by Mr9357** [comment]
截图可以吗![Screenshot_2024-03-26-19-17-26-32_04e63bc7959998aa186ce9fdd3b40c8f.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/89758772/09f294b2-50b0-4b8e-846d-bc0ba94a04da)

**Comment by gentlemanxzh** [comment]
日志看上去是正常的，画中画的UI绘制了，你那里显示还是不正常？

**Comment by Mr9357** [comment]
还是老问题，不正常显示

**Comment by gentlemanxzh** [comment]
用阿里云的云真机试了一下同机型 也没复现出来～

**Comment by Mr9357** [comment]
那就不管了，影响不大
