### ISSUE TITLE
[Android]即使安装了系统证书，chrome依然不信任

### ISSUE THREAD

**Issue by 12189108** [wanghongenpin/network_proxy_flutter#167]
**描述错误(Describe the bug)**
安装系统证书重启后，chrome依然报错，提示证书无效，提示NET::ERR_CERT_AUTHORITY_INVALID，
如github.com 通常会使用加密技术来保护您的信息。Chrome 此次尝试连接到 github.com 时，该网站发回了异常的错误凭据。这可能是因为有攻击者在试图冒充 github.com，或者 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Chrome 尚未进行任何数据交换便停止了连接。

您目前无法访问 github.com，因为此网站使用了 HSTS。网络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常。

**Comment by ga33me2222** [comment]
无解

**Comment by wanghongenpin** [comment]
将证书安装到用户证书里，我测试用户证书是可以抓的，先禁用Magisk证书模块重启手机，保证系统证书里看不到，然后安装安装用户证书方式，这样证书可以同时存在用户和系统证书里，如果系统证书存在没办法安装用户证书
