### ISSUE TITLE
手机APP的请求重写功能，无法看到已保存的行为

### ISSUE THREAD

**Issue by kkopmm** [wanghongenpin/network_proxy_flutter#168]
如题所示，修改请求和修改响应保存后，再次点进去的时候，无法看到，也无法删除

**Comment by wanghongenpin** [comment]
请说明具体操作步骤，最好附上截图

**Comment by kkopmm** [comment]
> 请说明具体操作步骤，最好附上截图
![布丁扫描2024-03-26 16-05-05.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/130914655/d5793337-20fa-4bdf-ae0e-6934e0fd28e0)

**Comment by kkopmm** [comment]
图片有点大

**Comment by wanghongenpin** [comment]
在请求重写列表里可以看到，从请求重写菜单里进入

**Comment by wanghongenpin** [comment]
点击icon只会填充重写类型的，请求修改得需要从请求重写列表查看
