### ISSUE TITLE
[Windows]打开软件后，安装证书到信任机构，发现网页打不开了。停止和退出软件都无法恢复网络。只有重启电脑才能解决。

### ISSUE THREAD

**Issue by zhuyuanmin** [wanghongenpin/network_proxy_flutter#169]
**描述错误(Describe the bug)**
[Windows]打开软件后，安装证书到信任机构，发现网页打不开了。停止和退出软件都无法恢复网络。只有重启电脑才能解决。
**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面

**屏幕截图(Screenshots)*

**Comment by wanghongenpin** [comment]
我没遇到过，是必现的吗？软件关闭后如果遇到无法上网可以看下代理是否ha还开着


<img width="914" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/83f0a63c-d69e-44f6-be0e-f449f9eb1f67">

**Comment by wanghongenpin** [comment]
请检查证书安装, 如果不需要抓取网页,可以把设置系统代理给关闭
