### ISSUE TITLE
使用了一下，功能还能薄弱

### ISSUE THREAD

**Issue by hongbing2017** [wanghongenpin/network_proxy_flutter#17]
我抓PC版微信小程序，只能抓到image，对比之下charles可以抓到完整记录
希望作者能找到自己的优势地方，比如针对ssl spinning问题提出比较好的解决方案，而不是简单照搬一般抓包软件已有的功能

**Comment by wanghongenpin** [comment]
mac、windows、ios微信小程序我测了都可以抓，可以具体说下哪个小程序抓不到？
我全平台免费开源，pc版有几个完全免费的？更不用说是开源，功能不完善 刚开发完，我会继续完善，你也可以继续使用破解的或者功能受限制的软件。
