### ISSUE TITLE
[Windows] 访问https://www.msn.cn/zh-cn 站点，显示此站点的连接不安全

### ISSUE THREAD

**Issue by sjbwylbs** [wanghongenpin/network_proxy_flutter#172]
**描述错误(Describe the bug)**
访问https://www.msn.cn/zh-cn 站点，显示此站点的连接不安全。其他网站正常
**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面
点击Edge浏览器首页任何一个链接，或者访问https://www.msn.cn/zh-cn 站点，显示此站点的连接不安全
**屏幕截图(Screenshots)*
<img width="530" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/333239/b894abb9-bff0-450d-8c11-22834d2457ea">

**Comment by wanghongenpin** [comment]
我这边可以，你证书安装好了嘛
<img width="1304" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/f56baebf-e17b-4359-b170-bb74d3176d56">

**Comment by sjbwylbs** [comment]
安装好了。
如图
<img width="606" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/333239/aa73a64c-bf1e-4146-9554-295bd540ad7d">
