### ISSUE TITLE
Windows 执行exe文件报错

### ISSUE THREAD

**Issue by SghJson** [wanghongenpin/network_proxy_flutter#173]
![Snipaste_2024-03-28_09-48-02](https://github.com/wanghongenpin/network_proxy_flutter/assets/31149111/cc2481ef-4b5a-4c8a-bf8e-ea69638ce7f1)

**Comment by wanghongenpin** [comment]
可以先网上搜索解决方案，是不是缺少了一些基础的dll

<img width="899" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/46f6d949-40d3-410c-9e32-498b6e2f2763">

**Comment by wanghongenpin** [comment]
安装下这个组件是在呢，根据系统选中x64或者x86
https://www.microsoft.com/zh-CN/download/details.aspx?id=53587

**Comment by wanghongenpin** [comment]
本软件是64位的
