### ISSUE TITLE
选中项不够突出

### ISSUE THREAD

**Issue by CncCbz** [wanghongenpin/network_proxy_flutter#174]
[Mac端]当前选中查看的请求颜色不够突出，很难分辨。希望可以优化一下选中项的高亮效果。
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/43227065/dec78e79-9c62-47fa-ba36-3efc4cb316c0)

**Comment by wanghongenpin** [comment]
加个淡色背景是否可行
<img width="583" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/99d47644-5705-4ac6-bcb0-13a05407a927">

**Comment by CncCbz** [comment]
> 加个淡色背景是否可行
> <img width="583" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/99d47644-5705-4ac6-bcb0-13a05407a927">
> 

可以，好很多

**Comment by wanghongenpin** [comment]
最新包已经更新
