### ISSUE TITLE
(Android) 希望增加应用黑名单

### ISSUE THREAD

**Issue by 123z45** [wanghongenpin/network_proxy_flutter#176]
**您的功能请求是否与问题有关？请描述.**
对问题所在的清晰简洁的描述[...]
由于技术原因（issue #171 ），抓包时某些不需要抓包应用可能异常。手动添加应用白名单太浪费时间了，而且可能漏掉某些系统app。对于上面那个issue，其实Termux不用抓包，而且frpc也不适用域名黑名单，不走dns
**描述您想要的解决方案**
对你想要发生的事情进行清晰简洁的描述.
添加修改应用黑名单功能，对设置的黑名单app不抓包，其他app全部抓包。
**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。
nothing

**Comment by wanghongenpin** [comment]
最新版包已经支持

**Comment by 123z45** [comment]
好的，谢谢啦～希望在版本号后面加个小版本号，不然看不到软件更新
