### ISSUE TITLE
希望可以增加一个一键移动.0根证书至根目录的功能。

### ISSUE THREAD

**Issue by hdhd3** [wanghongenpin/network_proxy_flutter#18]
毕竟安卓没根证书基本上抓不到任何有用的东西

**Comment by wanghongenpin** [comment]
这个不root没法做，建议先用adb手动操作吧，后面可以提供下载系统证书文件

**Comment by Ecalose** [comment]
赞同，希望能早日提供系统证书，用户可以考虑直接移动或塞到面具里

**Comment by wanghongenpin** [comment]
> 赞同，希望能早日提供系统证书，用户可以考虑自行直接移动或塞到面具里

系统证书就是文件名不一样，最新版已增加根证书提示

**Comment by Ecalose** [comment]
> > 赞同，希望能早日提供系统证书，用户可以考虑自行直接移动或塞到面具里
> 
> 系统证书就是文件名不一样，最新版已增加根证书提示

好的，感谢提醒
