### ISSUE TITLE
希望出按照时间的列表和域名列表方式两种,时间列表的方便看上下文关系和执行顺序

### ISSUE THREAD

**Issue by olam321** [wanghongenpin/network_proxy_flutter#180]
希望出按照时间的列表和域名列表方式两种,时间列表的方便看上下文关系和执行顺序

**Comment by zuohl** [comment]
全部请求为啥不直接按时间排序呢，最好能支持顺序和倒序两种

**Comment by wanghongenpin** [comment]
桌面端吗

**Comment by YandLiu** [comment]
同求，桌面端需要，这样更方便

**Comment by wanghongenpin** [comment]
V1.1.2版本已经支持

https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.2
