### ISSUE TITLE
啥都挺好，完全可以代替charles但是图标能不能稍微说是能换就好了。

### ISSUE THREAD

**Issue by ttc9082** [wanghongenpin/network_proxy_flutter#181]
RTRTRTRTRT

**Comment by ga33me2222** [comment]
图标的确不够高大上

**Comment by ywgdjryf** [comment]
这图标是个什么东西?

**Comment by ywgdjryf** [comment]
他这图标是个什么东西?

**Comment by wanghongenpin** [comment]
有好的图标素材欢迎提供哈

**Comment by ttc9082** [comment]
![DALL·E 2024-04-01 16 46 41 - Design an abstract image of a pin or tack, where the top part resembles the letter 'P'  The design should be minimalist and stylized, embodying both t](https://github.com/wanghongenpin/network_proxy_flutter/assets/4164321/a0ebfb17-c8ad-4b4c-858e-47d5272aeb76)

**Comment by ttc9082** [comment]
看看这个咋样 首先他是一个pin 其次 他头上有抽象的P P
我觉得你可以往这方面 搞一搞 @wanghongenpin

**Comment by wanghongenpin** [comment]
最新版logo已经换了，怎么样
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.0-Beta
