### ISSUE TITLE
[Windows、Mac、Android]xxx

### ISSUE THREAD

**Issue by star2k** [wanghongenpin/network_proxy_flutter#184]
**描述错误(Describe the bug)**
打开安装证书，运行了半小时浏览器，为什么采抓到这么几个包？

![PixPin_2024-04-03_06-31-56](https://github.com/wanghongenpin/network_proxy_flutter/assets/9582078/c3735bd3-33d2-4687-9981-6a3581fd5b92)

**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面

**屏幕截图(Screenshots)*

**Comment by wanghongenpin** [comment]
你可以看下代理是否有冲突，如果有用其他vpn软件，可以配置外部代理
