### ISSUE TITLE
自定义根证书

### ISSUE THREAD

**Issue by Rw-Ro** [wanghongenpin/network_proxy_flutter#185]
建议增加导入和使用自定义证书的功能。

**Comment by yunyuyan** [comment]
+1
要是可以和Charles那样导入使用自己生成的根证书就太好了

**Comment by wanghongenpin** [comment]
下个版本支持

**Comment by wanghongenpin** [comment]
最新版V1.1.1已经支持
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.1
