### ISSUE TITLE
安卓

### ISSUE THREAD

**Issue by LanFeng11** [wanghongenpin/network_proxy_flutter#186]
安卓可以添加直接复制域名吗？
抓包屏蔽hosts用

**Comment by LanFeng11** [comment]
> 快捷复制域名吗，现在有快捷复制整个url

嗯嗯，因为一般的屏蔽hosts都只需要域名，

**Comment by wanghongenpin** [comment]
好，我想想怎么设计快捷复制操作，你有好的设计思路也可以提供下

**Comment by LanFeng11** [comment]
> 好，我想想怎么设计快捷复制操作，你有好的设计思路也可以提供下

![Screenshot_2024-04-26-23-19-31-607_com network proxy](https://github.com/wanghongenpin/network_proxy_flutter/assets/43339825/d777d5bf-5b3d-4120-8829-1ed1df3b127f)
这个位置应该不错

**Comment by LanFeng11** [comment]
> > 好，我想想怎么设计快捷复制操作，你有好的设计思路也可以提供下
> 
> ![Screenshot_2024-04-26-23-19-31-607_com network proxy](https://private-user-images.githubusercontent.com/43339825/326028160-d777d5bf-5b3d-4120-8829-1ed1df3b127f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNDUyODAsIm5iZiI6MTcxNDE0NDk4MCwicGF0aCI6Ii80MzMzOTgyNS8zMjYwMjgxNjAtZDc3N2Q1YmYtNWIzZC00MTIwLTg4MjktMWVkMWRmM2IxMjdmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDE1MjMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMzc2ZGFkY2UxODRkN2QxNGIzOGI5MTAxZDEzMjk4MzlmZmUwODkyNWI0NWMzNzAwNmVkM2U3MTc0MWNiZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M99ZBfvA4YzO_lfypok--p7MbkjsAb34mbeCroKqQmk) 这个位置应该不错



> > 好，我想想怎么设计快捷复制操作，你有好的设计思路也可以提供下
> 
> ![Screenshot_2024-04-26-23-19-31-607_com network proxy](https://private-user-images.githubusercontent.com/43339825/326028160-d777d5bf-5b3d-4120-8829-1ed1df3b127f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNDUyODAsIm5iZiI6MTcxNDE0NDk4MCwicGF0aCI6Ii80MzMzOTgyNS8zMjYwMjgxNjAtZDc3N2Q1YmYtNWIzZC00MTIwLTg4MjktMWVkMWRmM2IxMjdmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDE1MjMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMzc2ZGFkY2UxODRkN2QxNGIzOGI5MTAxZDEzMjk4MzlmZmUwODkyNWI0NWMzNzAwNmVkM2U3MTc0MWNiZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M99ZBfvA4YzO_lfypok--p7MbkjsAb34mbeCroKqQmk) 这个位置应该不错

![Screenshot_2024-04-26-23-24-22-621_com network proxy](https://github.com/wanghongenpin/network_proxy_flutter/assets/43339825/b18f86aa-3115-4c48-a849-56cc9642c5d1)
还有黑白名单这里也可以加个复制hosts

**Comment by wanghongenpin** [comment]
这个包已经支持复制host菜单
https://www.lanzoub.com/iDT3S1wq3i6h
密码:1ver
