### ISSUE TITLE
抓包精灵-可以免root在安卓直接安装证书-对https请求进行抓包原理是什么? 项目之后是否也支持直接安装证书抓包.

### ISSUE THREAD

**Issue by lucoo01** [wanghongenpin/network_proxy_flutter#187]
**抓包精灵-可以在安卓直接安装证书-对https请求进行抓包原理是什么?**

**描述您想要的解决方案**
如果可以, 请添加直接安装证书功能

**Comment by wanghongenpin** [comment]
兄弟，你把别人开源的代码自己给上架了，然后跑来这提需求，你觉得合理吗？为什么不尊重下别人的劳动成果？
