### ISSUE TITLE
希望抓包工具能够使用代理

### ISSUE THREAD

**Issue by lxeduir** [wanghongenpin/network_proxy_flutter#19]
希望抓包工具能够使用代理这样抓一些国外的网站方便一些

**Comment by wanghongenpin** [comment]
这几天做下，会增加个外部代理地址配置，现在不想抓电脑请求，可以把抓取电脑请求给关闭，这样不会覆盖电脑代理配置

**Comment by wanghongenpin** [comment]
> 希望抓包工具能够使用代理这样抓一些国外的网站方便一些

新增外部代理设置，抓包可以同时访问外网，退出时自动还原成外部代理，抓包软件和VPN再也不会有冲突啦
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/0.0.2

**Comment by jaychoubaby** [comment]
> > 希望抓包工具能够使用代理这样抓一些国外的网站方便一些
> 
> 新增外部代理设置，抓包可以同时访问外网，退出时自动还原成外部代理，抓包软件和VPN再也不会有冲突啦 https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/0.0.2

ios上可以解决代理抓包吗

**Comment by wanghongenpin** [comment]
> ios上可以解决代理抓包吗

ios代理什么问题呢，也需要设置外部代理吗

**Comment by jaychoubaby** [comment]
> > ios上可以解决代理抓包吗
> 
> ios代理什么问题呢，也需要设置外部代理吗

是的，因为ios上面开启抓包vpn则会掉，这样在抓包的时候则无法访问外网

**Comment by wanghongenpin** [comment]
> 是的，因为ios上面开启抓包vpn则会掉，这样在抓包的时候则无法访问外网

手机大概率不行，因为抓包得启用VPN，会冲掉外网软件的VPN，那些软件检测到vpn关闭 就把本地端口号给关了

**Comment by wanghongenpin** [comment]
> 是的，因为ios上面开启抓包vpn则会掉，这样在抓包的时候则无法访问外网

建议手机wifi配置电脑ip代理把，由电脑开VPN访问

**Comment by jaychoubaby** [comment]
> > 是的，因为ios上面开启抓包vpn则会掉，这样在抓包的时候则无法访问外网
> 
> 手机大概率不行，因为抓包得启用VPN，会冲掉外网软件的VPN，那些软件检测到vpn关闭 就把本地端口号给关了

好的，也不是刚需，qx类的代理app也具备抓包功能，只不过不是主线功能，但也够用，咱们这个app如果要代理+抓包，一不小心可能就做出了代理appl
