### ISSUE TITLE
[Android]1.0.9抓包失败

### ISSUE THREAD

**Issue by 2935677496** [wanghongenpin/network_proxy_flutter#190]
**1.0.9安卓版本抓包时出现ERR_NAME_NOT_RESOLVED错误**

**设备为IQOO3 安卓13 无root，1.0.8版本中安装了证书后可正常抓包，升级了1.0.9后开启抓包时其他应用无法连接网络，即使没有开始HTTP代理，在浏览器提示ERR_NAME_NOT_RESOLVED错误，换回1.0.8版本后恢复正常**

**Comment by wanghongenpin** [comment]
是所有软件都这样吗，试下最新版本呢，我这边没出现过

https://github.com/wanghongenpin/network_proxy_flutter/releases

**Comment by wanghongenpin** [comment]
可以试下最新版本, 长时间没反馈先关闭了, 有进展可以重新打开

**Comment by moliyadi007** [comment]
我的pixel3 也是从1.0.9开始打开抓包就断网
