### ISSUE TITLE
控制台如何打开?

### ISSUE THREAD

**Issue by TSYMQMYST** [wanghongenpin/network_proxy_flutter#191]
请问一下控制台怎么打开

**Comment by TSYMQMYST** [comment]
我是mac 或者 安卓 / ios

**Comment by wanghongenpin** [comment]
什么控制台，现在只有脚本日志控制台

**Comment by wanghongenpin** [comment]
<img width="750" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/f97b0c16-cac1-4748-b73f-25534a5c5c84">

脚本菜单，有个控制台
