### ISSUE TITLE
代码脚本发送的请求可以抓包吗？例如python的requests、php的file_get_contents

### ISSUE THREAD

**Issue by chenjin01** [wanghongenpin/network_proxy_flutter#196]
**您的功能请求是否与问题有关？请描述.**

请问现在软件可以抓包一些代码脚本发送的HTTP请求吗？

**例如：**

`$resp = file_get_contents("http://httpbin.org/get");`

`response = requests.get("http://httpbin.org/get")`

**Comment by wanghongenpin** [comment]
目前不能，可以看下代码能不能设置代理，转发到抓包软件就可以看到了

**Comment by xy3xy3** [comment]
> 目前不能，可以看下代码能不能设置代理，转发到抓包软件就可以看到了

可否参考类似clash的tun模式实现？
