### ISSUE TITLE
请求时间能否增加毫秒

### ISSUE THREAD

**Issue by zuohl** [wanghongenpin/network_proxy_flutter#199]
列表和general详情都涉及,目前只精确到秒了

**Comment by wanghongenpin** [comment]
什么系统

**Comment by zuohl** [comment]
> 什么系统

我这边安卓和mac

**Comment by wanghongenpin** [comment]
Mac: https://www.lanzoub.com/imZ8o1wqqd7g

Android: https://www.lanzoub.com/iPUv81wq5iad
密码:1o7j
