### ISSUE TITLE
启动就奔溃了，原因不详

### ISSUE THREAD

**Issue by guominfang** [wanghongenpin/network_proxy_flutter#2]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 478EAA17-C873-41F5-8B3C-24A22CFBB82C
CrashReporter Key:   4719C95E-6ECF-3371-8293-480789219AEC
Hardware Model:      MacBookPro15,4
Process:             ProxyPin [723]
Path:                /Applications/ProxyPin.app/Contents/MacOS/ProxyPin
Identifier:          com.network.proxy
Version:             1.0.0 (1)
Code Type:           X86-64 (Native)
Role:                Default
Parent Process:      launchd [1]
Coalition:           com.network.proxy [713]

Date/Time:           2023-07-06 19:01:04.1560 +0800
Launch Time:         2023-07-06 19:01:04.1270 +0800
OS Version:          macOS 12.6.5 (21G531)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: CODESIGNING 1 

Triggered by Thread:  0

Thread 0 Crashed:
0                                	       0x1194d1ae0 _dyld_start + 0
1   ???                           	               0x1 ???

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007ff7b23b7c00
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00000001194d1ae0  rfl: 0x0000000000000200  cr2: 0x0000000000000000
  
Logical CPU:     0
Error Code:      0x00000000 
Trap Number:     0

Binary Images:
       0x1194cd000 -        0x119538fff  (*) <6376ba16-20f7-3c31-a5c5-a10648ae7b56> 
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

Error Formulating Crash Report:
dyld_process_snapshot_get_shared_cache failed

EOF

-----------
Full Report
-----------

{"app_name":"ProxyPin","timestamp":"2023-07-06 19:01:06.00 +0800","app_version":"1.0.0","slice_uuid":"de6191de-ff72-3ab3-8e5a-285e3c20b510","build_version":"1","platform":0,"bundleID":"com.network.proxy","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6.5 (21G531)","incident_id":"478EAA17-C873-41F5-8B3C-24A22CFBB82C","name":"ProxyPin"}
{
  "uptime" : 68,
  "procLaunch" : "2023-07-06 19:01:04.1270 +0800",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro15,4",
  "procStartAbsTime" : 68728499686,
  "coalitionID" : 713,
  "osVersion" : {
    "train" : "macOS 12.6.5",
    "build" : "21G531",
    "releaseType" : "User"
  },
  "captureTime" : "2023-07-06 19:01:04.1560 +0800",
  "incident" : "478EAA17-C873-41F5-8B3C-24A22CFBB82C",
  "bug_type" : "309",
  "pid" : 723,
  "procExitAbsTime" : 68751081168,
  "cpuType" : "X86-64",
  "procName" : "ProxyPin",
  "procPath" : "\/Applications\/ProxyPin.app\/Contents\/MacOS\/ProxyPin",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0.0","CFBundleVersion":"1","CFBundleIdentifier":"com.network.proxy"},
  "storeInfo" : {"deviceIdentifierForVendor":"23ACEC91-279F-5318-999F-BB03E0C4C3A2","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.network.proxy",
  "crashReporterKey" : "4719C95E-6ECF-3371-8293-480789219AEC",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL (Code Signature Invalid)"},
  "termination" : {"namespace":"CODESIGNING","flags":66,"code":1},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":5963,"threadState":{"r13":{"value":0},"rax":{"value":0},"rflags":{"value":512},"cpu":{"value":0},"r14":{"value":0},"rsi":{"value":0},"r8":{"value":0},"cr2":{"value":0},"rdx":{"value":0},"r10":{"value":0},"r9":{"value":0},"r15":{"value":0},"rbx":{"value":0},"trap":{"value":0},"err":{"value":0},"r11":{"value":0},"rip":{"value":4719450848,"matchesCrashFrame":1},"rbp":{"value":0},"rsp":{"value":140701823892480},"r12":{"value":0},"rcx":{"value":0},"flavor":"x86_THREAD_STATE","rdi":{"value":0}},"frames":[{"imageOffset":19168,"symbol":"_dyld_start","symbolLocation":0,"imageIndex":0},{"imageOffset":1,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4719431680,
    "size" : 442368,
    "uuid" : "6376ba16-20f7-3c31-a5c5-a10648ae7b56",
    "path" : "\u0004",
    "name" : "\u0004"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "vmSummary" : "ReadOnly portion of Libraries: Total=680K resident=0K(0%) swapped_out_or_unallocated=680K(100%)\nWritable regions: Total=8192K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8192K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          8K        2 \n__DATA                              32K        2 \n__DATA_CONST                        80K        1 \n__LINKEDIT                         256K        4 \n__TEXT                             448K        2 \n===========                     =======  ======= \nTOTAL                             64.8M       13 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000025
    },
    {
      "rolloutId" : "5fb4245a1bbfe8005e33a1e1",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c28e4ee6-1b08-4f90-8e05-2809e78310a3",
      "experimentId" : "6317d2003d24842ff850182a",
      "deploymentId" : 400000012
    }
  ]
},
  "reportNotes" : [
  "dyld_process_snapshot_get_shared_cache failed"
]
}

Model: MacBookPro15,4, BootROM 1715.81.2.0.0, 6 processors, 6-Core Intel Core i7, 1.6 GHz, 16 GB, SMC 
Graphics: Intel Iris Plus Graphics 645, Intel Iris Plus Graphics 645, Built-In
Display: spdisplays_display, 2560 x 1600, Main, MirrorOff, Online
Display: PHL 241i8, 1920 x 1080 (1080p FHD - Full High Definition), MirrorOff, Online
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, DDR4, 2667 MHz, Micron, 4ATF1G64HZ-3G2B1
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, DDR4, 2667 MHz, Micron, 4ATF1G64HZ-3G2B1
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB3.1 Hub
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB2.1 Hub
USB Device: USB 2.0 Hub
USB Device: BillBoard Device
USB Device: Integrated Camera
Thunderbolt Bus: 

<img width="476" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24568042/bf2c3ede-5292-4581-8e32-eb96ff391e18">

**Comment by wanghongenpin** [comment]
系统设置允许任何来源了么

**Comment by wanghongenpin** [comment]
我找了几个Mac电脑试了下，首次打开会提示损坏，然后去系统设置-安全性与隐私-允许任何来源 就好了。

**Comment by guominfang** [comment]
@wanghongenpin 不明觉厉，用了一个星期左右，就被系统提示强制删除。安装的时候我已经选择了，允许了，不然我也不会能用一个星期不

**Comment by guominfang** [comment]
@wanghongenpin  今天重新安装，并运行 ` codesign --force --deep --sign - /Applications/Proxypin.app
`
可以重新打开软件
