### ISSUE TITLE
希望搜索功能可以增强一下

### ISSUE THREAD

**Issue by doyoman** [wanghongenpin/network_proxy_flutter#20]
目前搜索只能搜索url内的关键词，希望可以搜索请求体，响应体等内容关键字，使用的是ios版

**Comment by wanghongenpin** [comment]
现在可以搜索请求方法和响应类型了，可以应对大部分场景了，高级复杂搜索后面再准备做

**Comment by xream** [comment]
渴望拥有搜索响应体 弥补某些 app 的不足

**Comment by wanghongenpin** [comment]
这周末处理下

**Comment by wanghongenpin** [comment]
新增版本 1.0.1
1.增加高级搜索，点击搜索icon触发
2.显示SSL握手异常、建立连接异常、未知异常等请求
3.当响应体大时异步加载json, 完善请求重写，修复手机扫码连接未开启代理时不转发问题
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/1.0.1

**Comment by wanghongenpin** [comment]
已经完成，手机端请下载最新版本。
