### ISSUE TITLE
[Mac]response 乱码

### ISSUE THREAD

**Issue by chenjunjie45** [wanghongenpin/network_proxy_flutter#204]
**描述错误(Describe the bug)**
response乱码

**屏幕截图(Screenshots)*
<img width="1230" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/79789819/7b3e9dde-1c5e-4662-80e8-793a9bc761a0">

**Comment by wanghongenpin** [comment]
这应该不是乱码吧，实际响应就是这样吧

**Comment by wanghongenpin** [comment]
可以发下curl，或者看下其他抓包软件是否是类似情况

**Comment by wanghongenpin** [comment]
看响应是正常的，如果和其他抓包软件不一致，欢迎重新打开
