### ISSUE TITLE
ios抓包失败

### ISSUE THREAD

**Issue by kingz40o** [wanghongenpin/network_proxy_flutter#21]
抓取app包时提示以下信息，stream软件可以正常抓包。

URL SessionTask failed with error: 发生了
SSL 错误，无法建立与该服务器的安全连接。

**Comment by wanghongenpin** [comment]
请检查证书安装并且已信任，如果不是特殊版本，绝大数都是证书配置问题

**Comment by kingz40o** [comment]
证书已安装并且信任

**Comment by wanghongenpin** [comment]
是所有app都是这样吗，浏览器访问网页可以吗

**Comment by kingz40o** [comment]
网页可以抓，测试的app不可以，stream可以抓，不清楚是什么原因导致的

**Comment by wanghongenpin** [comment]
> 网页可以抓，测试的app不可以，stream可以抓，不清楚是什么原因导致的

是哪个app，所有app都不行吗

**Comment by kingz40o** [comment]
https://apps.apple.com/us/app/jrcb%E6%94%B6%E9%93%B6%E5%AE%9D/id1397286494?l=zh-Hans-CN

**Comment by wanghongenpin** [comment]
> https://apps.apple.com/us/app/jrcb%E6%94%B6%E9%93%B6%E5%AE%9D/id1397286494?l=zh-Hans-CN

多谢反馈, 确实有点问题，明天发版解决

**Comment by wanghongenpin** [comment]
最新版已经解决了，麻烦下载最新版本呢

**Comment by kingz40o** [comment]
可以了
