### ISSUE TITLE
高级重放里，间隔（ms）是否可以设置允许某个随机数范围？

### ISSUE THREAD

**Issue by pinoren** [wanghongenpin/network_proxy_flutter#212]
**您的功能请求是否与问题有关？请描述.**
高级重放功能里，间隔（ms）仅可设定固定值，有时可能需要一个小范围的随机数，或者每次默认都是某个固定数值。

**描述您想要的解决方案**
希望在高级重放功能中加入随机值范围选项，使得重发间隔可以是指定范围内的随机数值，也可以通过把随机数范围设定为例如 200-200ms，使得数值被固定，不必每次重复填写。

**附加上下文**
设想功能界面：
![未标题-1](https://github.com/wanghongenpin/network_proxy_flutter/assets/31525739/89b85757-3189-4409-9112-0fb36c0f738a)

**Comment by wanghongenpin** [comment]
可以，安排

**Comment by pinoren** [comment]
太感谢啦！！！｡:.ﾟヽ(*´∀`)ﾉﾟ.:｡

**Comment by wanghongenpin** [comment]
V1.1.0-Beta 高级重放请求支持随机间隔；

https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.0-Beta

**Comment by pinoren** [comment]
太感谢您啦！这下方便多啦！！！

**Comment by pinoren** [comment]
##试用一下，发现一个小小的问题。就是重发之后每一次要再随机数字的话，就需要重新选择第2个选项在手工填入数值，可不可以设置成为能自动记忆这个填的数值和默认选随机数值呢。。。就比如说我上次填写的是使用随机数值200~500，那么下一次点高级重发的时候，他默认就在这个选项上？我觉得这个可能应该是这个页面或者主设置页面里面的一个选项，大概应该称为：记忆自定义设置？万分感谢。。。

实际上我还希望用这种记忆自定义设置的功能来实现，我可以填入例如随机数值200~200ms，使得以后重复操作的时候可以不用手工的重复输入多次这个数值。当然如果这个页面有记忆功能的话，那我也可以在固定数值里面填入200。

**Comment by wanghongenpin** [comment]
下载下最新的包,已经支持

> 记忆自定义设置

**Comment by wanghongenpin** [comment]
写错了，后面会重新打包

**Comment by pinoren** [comment]
收到，非常感谢您啦！！

**Comment by pinoren** [comment]
> 写错了，后面会重新打包

内个，发正式版的时候这个写错的字段没有更正。。。。

**Comment by pinoren** [comment]
问题得到了解决，感谢作者大佬。。。
