### ISSUE TITLE
Android apk无法安装

### ISSUE THREAD

**Issue by maochengliang** [wanghongenpin/network_proxy_flutter#218]
**描述错误(Describe the bug)**

**To Reproduce**
下载android apk后安装报错，android 12版本，型号：sony

**屏幕截图(Screenshots)*
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdl1848231075.tmp/base.apk: Failed to collect certificates from /data/app/vmdl1848231075.tmp/base.apk using APK Signature Scheme v2: SHA-256 digest of contents did not verify]

**Comment by wanghongenpin** [comment]
是在Releases里下载的包吗？看上去像证书的问题，还没有人反馈过这样的问题

**Comment by gsjz20** [comment]
没出现过 我是正常的
