### ISSUE TITLE
[Android]抓包响应体有乱码

### ISSUE THREAD

**Issue by wingswing1** [wanghongenpin/network_proxy_flutter#223]
**描述错误(Describe the bug)**
抓包中国农业银行，响应体乱码（中文），用小黄鸟抓正常。
**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面
见上描述
**屏幕截图(Screenshots)*
见附图
![Uploading Screenshot_2024-05-24-15-14-11-245_com.network.proxy-edit.jpg…]()

**Comment by wanghongenpin** [comment]
图片是不是挂了，看不到

**Comment by wingswing1** [comment]
![Uploading Screenshot_2024-05-24-15-14-11-245_com.network.proxy-edit.jpg…]()

**Comment by wingswing1** [comment]
![Screenshot_2024-05-24-15-14-11-245_com network proxy-edit](https://github.com/wanghongenpin/network_proxy_flutter/assets/91712199/13cf7309-0da4-4786-998d-9bacd5415fe3)

**Comment by wingswing1** [comment]
> 图片是不是没上传完，看不到
见楼上

**Comment by wanghongenpin** [comment]
得看下header content-type

**Comment by wingswing1** [comment]
![IMG_20240527_093618](https://github.com/wanghongenpin/network_proxy_flutter/assets/91712199/1deaaf45-e801-4473-a21b-1c03aaf63bc0)
![IMG_20240527_093715](https://github.com/wanghongenpin/network_proxy_flutter/assets/91712199/ad32243d-ac71-440e-bce2-b3e120615adc)
![IMG_20240527_093742](https://github.com/wanghongenpin/network_proxy_flutter/assets/91712199/b32bc5b6-957c-4c7a-bba0-d89be4a4ab99)
![IMG_20240527_093805](https://github.com/wanghongenpin/network_proxy_flutter/assets/91712199/82478809-0f98-44a0-803a-095103e9b3b2)

**Comment by wingswing1** [comment]
> 得看下header content-type

更新了全部截图，见楼上

**Comment by wanghongenpin** [comment]
我感觉是加过密了，可以试下其他抓包软件是乱码不，如果是那就是加密了

**Comment by wingswing1** [comment]
小黄鸟抓的正常，也不正常的话我就不反馈了，并没有加密



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月27日 09:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wanghongenpin/network_proxy_flutter] [Android]抓包响应体有乱码 (Issue #223) |

我感觉是加过密了，可以试下其他抓包软件是乱码不，如果是那就是加密了

**Comment by wanghongenpin** [comment]
这个请求我用小黄鸟也是乱码

![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/8aa5df1d-767c-49b2-ae5e-a8635e960cf4)

**Comment by wanghongenpin** [comment]
其他抓包软件也是乱码，大概率是接口做了加密，如果其他软件可以正常展示，欢迎再次打开
