### ISSUE TITLE
[iOS]socket_patch会崩溃

### ISSUE THREAD

**Issue by OCer** [wanghongenpin/network_proxy_flutter#224]
**描述错误(Describe the bug)**
socket_patch.dart报错

**To Reproduce**
使用画中画到后台，在美团APP搜索美团充电宝，进入充电宝页面抓包，退出画中画回到抓包的APP

**屏幕截图(Screenshots)*
flutter: \^[[38;5;12m[lwkgh41f] POST https://cdb.meituan.com/marketing/source/reportSource<…>
flutter: pictureInPicture MethodCallHandler exitPictureInPictureMode
flutter: \^[[38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m│ SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = ct-cn-central-00001.oos-b-220615.ctyunapi.cn, port = 50291<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ [lwkgvb3h] error http://ct-cn-central-00001.oos-b-220615.ctyunapi.cn Channel(lwkgvb3h InetSocketAddress(InternetAddress('222.246.140.1', IPv4):443)<…>
flutter: \^[[38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m│ SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = ct-cn-central-00001.oos-b-220615.ctyunapi.cn, port = 50294<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ [lwkgwnrm] error http://ct-cn-central-00001.oos-b-220615.ctyunapi.cn Channel(lwkgwnrm InetSocketAddress(InternetAddress('222.246.140.1', IPv4):443)<…>
flutter: \^[[38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;196m│ SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = ct-cn-central-00001.oos-b-220615.ctyunapi.cn, port = 50294<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ [lwkgwnrm] write error<…>
flutter: \^[[38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'dart:io-patch/socket_patch.dart': Failed assertion: line 2163 pos 16: '<optimized out>': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2163:16)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#7      _StreamController._add (dart:async/stream_controller.dart:658:7)
#8      _StreamController.add (dart:async/stream_controller.dart:606:5)
#9      _StreamSinkImpl.add (dart:io/io_sink.dart:154:17)
#10     _Socket.add (dart:io-patch/socket_patch.dart:2321:38)
#11     Channel.writeBytes (package:network_proxy/network/channel.dart:115:17)
<asynchronous suspension>
#12     Channel.write (package:network_proxy/network/channel.dart:97:5)
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'dart:io-patch/socket_patch.dart': Failed assertion: line 2184 pos 16: '<optimized out>': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      _SocketStreamConsumer.addStream.<anonymous closure> (dart:io-patch/socket_patch.dart:2184:16)
#3      _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#6      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#7      _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
#8      _StreamController._closeUnchecked (dart:async/stream_controller.dart:647:7)
#9      _StreamController.close (dart:async/stream_controller.dart:640:5)
#10     _StreamSinkImpl.flush (dart:io/io_sink.dart:192:26)
#11     _Socket.flush (dart:io-patch/socket_patch.dart:2335:27)
#12     Channel.writeBytes (package:network_proxy/network/channel.dart:117:21)
<asynchronous suspension>
#13     Channel.write (package:network_proxy/network/channel.dart:97:5)
<asynchronous suspension>

**Comment by wanghongenpin** [comment]
没办法复现，你那边是否必现，最新TF版本1.1.2还有问题吗

**Comment by wanghongenpin** [comment]
无法复现
