### ISSUE TITLE
[Android] 脚本未生效

### ISSUE THREAD

**Issue by MengJunTuan** [wanghongenpin/network_proxy_flutter#227]
**描述错误(Describe the bug)**
脚本未生效

**To Reproduce**
1.建立两个脚本，退出并重新打开ProxyPin，开启抓包，开启脚本日志界面，发送请求测试，无日志输出，脚本未执行。

2.不停止抓包，进入脚本界面，选择任意脚本进行编辑，不进行任何改动点击保存， 再次发包进行测试，脚本可执行

**屏幕截图(Screenshots)*

**Comment by MengJunTuan** [comment]
重写也有类似问题

**Comment by wanghongenpin** [comment]
发下请求的curl，以及脚本url规则

**Comment by wanghongenpin** [comment]
能否提供一些调试信息？

**Comment by MengJunTuan** [comment]
// 在请求到达服务器之前,调用此函数,您可以在此处修改请求数据
// 例如Add/Update/Remove：Queries、Headers、Body
async function onRequest(context, request) {
  console.log(request.url);
  request.headers["X-New-Headers"] = "My-Value";
  var data = '一个超长加密加密的字符串'
 var body = JSON.parse(request.body);
  body['fish_data'] = data;
  request.body = JSON.stringify(body);
  return request;
}

**Comment by MengJunTuan** [comment]
> // 在请求到达服务器之前,调用此函数,您可以在此处修改请求数据
> // 例如Add/Update/Remove：Queries、Headers、Body
> async function onRequest(context, request) {
>   console.log(request.url);
>   request.headers["X-New-Headers"] = "My-Value";
>   var data = '一个超长加密加密的字符串'
>  var body = JSON.parse(request.body);
>   body['fish_data'] = data;
>   request.body = JSON.stringify(body);
>   return request;
> }
>   

其他未做更改， 第二个脚本与第一个脚本类似，不同之处是第二个脚本修改的是响应内容，bug产生时console.log无任何输出，且body也没有正常的进行替换

**Comment by wanghongenpin** [comment]
同一个URL写了两个脚本吗？现在只会执行一个脚本，你可以在一个脚本同时处理request和response

**Comment by wanghongenpin** [comment]
一个URL只能执行一个脚本
