### ISSUE TITLE
接口响应的二进制数据无法识别

### ISSUE THREAD

**Issue by tre0521** [wanghongenpin/network_proxy_flutter#229]
能否以16进制的方式显示接口响应的二进制内容

**Comment by M17764017422** [comment]
我提过这个，为二进制数据提供更多的展现方案，可识别的数据根据类型提供直接预览，比如图片、音频、视频等，不能预览的类型通过系统调用第三方软件打开比如PDF、epub、7Z压缩包等。
其它不能识别类型的数据，通过16进制预览前50个字节+一串对完整数据的校验码，为问题分析提供参考。
说的是手机版
@wanghongenpin 

_最初由 M17764017422 在 https://github.com/wanghongenpin/network_proxy_flutter/issues/51#issuecomment-1863970640 发布_

**Comment by wanghongenpin** [comment]
现在已经有16禁止展示了

<img width="774" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/c6eafd02-4d84-4709-b3dd-6dc9bc2a8be3">

> 能否以16进制的方式显示接口响应的二进制内容
