### ISSUE TITLE
win11 一直报错呢. 

### ISSUE THREAD

**Issue by 104979058** [wanghongenpin/network_proxy_flutter#23]
错误 错误应用程序名称: ProxyPin.exe，版本: 1.0.0.1，时间戳: 0x64c76d61
错误模块名称: flutter_windows.dll，版本: 0.0.0.0，时间戳: 0x64aefcb8
异常代码: 0xc0000005
错误偏移量: 0x0000000000010541
错误进程 ID: 0x0x46B0
错误应用程序启动时间: 0x0x1D9C4DF14EC7B4D

**Comment by wanghongenpin** [comment]
看flutter是支持windows11的，我现在用的是10，先自己研究下呢，实在不行我装个11虚拟机

**Comment by wanghongenpin** [comment]
我虚拟机安装windows11是可以打开，从文件夹直接运行ProxyPin.exe
<img width="1420" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/0dbf9965-20cf-4f44-ac3c-4e1a144f3f7a">
