### ISSUE TITLE
[Problem] 抓包微信小程序的一系列问题

### ISSUE THREAD

**Issue by yanecc** [wanghongenpin/network_proxy_flutter#230]
想要抓包微信小程序，目标小程序只能在手机上运行，尝试通过NekoBox进行http代理连接电脑，无法打开小程序，提示网络错误。又下载了手机端ProxyPin，能正常访问小程序，但是电脑端只捕获到乱码。看到 https://github.com/wanghongenpin/network_proxy_flutter/issues/43 中提到安卓设备需要root，但是我的设备无法root，所以尝试使用WSA，使用代理同样无法打开小程序，尝试arm64客户端，但是在WSA中闪退。。。

**Comment by wanghongenpin** [comment]
虚拟机使用不带任何后缀的，虚拟机好像是x64架构，电脑版显示乱码是啥
