### ISSUE TITLE
安卓14证书复制遇到了问题

### ISSUE THREAD

**Issue by yangshaoxing** [wanghongenpin/network_proxy_flutter#231]
安卓14复制证书到/apex。。。目录这个是做了说明的，但是怎么复制过去没说，试了好几种办法都不行

**Comment by wanghongenpin** [comment]
root之后可以用面具模块挂载，有尝试使用本证书面具模块，或者其他面具模块吗
https://gitee.com/wanghongenpin/Magisk-ProxyPinCA/releases/tag/1.1.0

**Comment by wanghongenpin** [comment]
可以网上搜索下安卓14安装证书，目录挂载啥的，都有详细的说明和教程
