### ISSUE TITLE
对于指定域名使用软件的证书，而不是全部

### ISSUE THREAD

**Issue by WYF-2013** [wanghongenpin/network_proxy_flutter#234]
**您的功能请求是否与问题有关？请描述.**
在安卓14上使用ProxyPin时，我需要对https请求A和B进行抓包和使用js脚本修改。当我刷入证书模块后，对A的操作一切正常，但是B依旧不信任证书，这表现在软件上就是没有该请求的抓包记录。

**描述您想要的解决方案**
我希望在上述问题下增加对指定URL如B不使用软件证书的功能，这类似于电脑软件Charles（https://www.charlesproxy.com），其中的SSL代理设置，没有进行SSL代理的域名也将显示在抓包列表中（显示unknown），虽然报文可能会显示一些乱码，但是通过分析对应16进制内容也会很有价值。

**附加上下文**
Charles抓包软件的截图：
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/98894272/6adc2ff8-9ef3-49b1-a4dc-f488409bc4aa)

**Comment by wanghongenpin** [comment]
有域名黑白名单，开启黑名单 将域名加入黑名单，不会域名进行解析，所以也没有证书问题

**Comment by wanghongenpin** [comment]
域名黑白名单类似于你图片上charles功能

**Comment by wanghongenpin** [comment]
已经存在域名黑白名单功能
