### ISSUE TITLE
[Android]base64解码存在空白字符

### ISSUE THREAD

**Issue by youke2580c** [wanghongenpin/network_proxy_flutter#238]
**描述错误(Describe the bug)**
base64解码有问题，复制会有空白字符

**To Reproduce**
系统版本：安卓11
应用版本：V1.0.9

重现行为的步骤: 
解码请求body，会有空白字符，重新编码不一样，对不上了
[829-1033-9513-ebd6cbd3ec79.txt](https://github.com/user-attachments/files/15865625/829-1033-9513-ebd6cbd3ec79.txt)
抓包详情
 **屏幕截图(Screenshots)*
![Screenshot_2024_0617_180443.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/56914697/ebe6b87a-5de6-43a5-b648-574520ff2031)

![Screenshot_2024_0617_180411.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/56914697/14adb94e-6c98-4c69-aa94-0a612225d5e5)

![Screenshot_2024_0617_180423.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/56914697/8073f336-37e3-4b6a-b9be-be13c6c11cf6)

**Comment by youke2580c** [comment]
[829-1033-9513-ebd6cbd3ec79.txt](https://github.com/user-attachments/files/15865625/829-1033-9513-ebd6cbd3ec79.txt)
抓包详情

**Comment by wanghongenpin** [comment]
V1.1.0-Beta 修复了base64复制空白符号问题；

https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.0-Beta
