### ISSUE TITLE
元萝卜安装JustTrustMe.apk之后，查看Xposed模块作用域提示有误

### ISSUE THREAD

**Issue by maochengliang** [wanghongenpin/network_proxy_flutter#239]
**描述错误(Describe the bug)**
在元萝卜安装JustTrustMe.apk之后，查看Xposed模块作用域提示有误
**To Reproduce**
首先安装元萝卜apk，然后从元萝卜中安装本地下载的JustTrustMe.apk

**屏幕截图(Screenshots)*
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/83636884/c112f537-b80e-408c-98ba-4c0ebfa2949b)

**Comment by wanghongenpin** [comment]
Xposed问题不是本软件能处理的

**Comment by SeaRat** [comment]
xposed和proxypin没关系啊，proxypin又没使用xposed注入应用的功能。应该是xposed或justtrustme的问题
