### ISSUE TITLE
希望增加一个可以直接在原数据里编写重写，并且支持测试正则匹配的功能，就像 iOS 的锤子抓包一样的类似功能，不然每次都要来回切换页面，来回去看数据是否都匹配上了

### ISSUE THREAD

**Issue by JiuWei007** [wanghongenpin/network_proxy_flutter#240]
**您的功能请求是否与问题有关？请描述.**
对问题所在的清晰简洁的描述[...]

**描述您想要的解决方案**
对你想要发生的事情进行清晰简洁的描述.

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by wanghongenpin** [comment]
现在在详情页点击请求重写icon就会自动填充请求
