### ISSUE TITLE
[Android] Can't capture SSLv3 sites

### ISSUE THREAD

**Issue by wajidareeb** [wanghongenpin/network_proxy_flutter#242]
**描述错误(Describe the bug)**

I added the ProxyPin certificate to both the system and user certificates, manually and via Magisk. However, **some sites using SSLv3 cannot be captured**. Attached are the error screenshots.

Device/os: Samsung , **Android 10**
App version: V1.1.0

**屏幕截图(Screenshots)*
site:
![Screenshot_20240624-110309_Chrome](https://github.com/wanghongenpin/network_proxy_flutter/assets/16358069/427f3e71-e3ec-45a6-936c-3ab9edfd2ecf)

ProxyPin:
![Screenshot_20240624-110442](https://github.com/wanghongenpin/network_proxy_flutter/assets/16358069/32c832cd-c8ef-4ef5-a790-df4c94c2ad8e)

**Comment by wanghongenpin** [comment]
This seems to be verifying the self signed certificate, you can try other packet capture software

**Comment by wajidareeb** [comment]
i have tried httpcanary and works fine, but the issue is with ProxyPin

**Comment by wajidareeb** [comment]
Chrome Browser android

**Comment by wanghongenpin** [comment]
> Chrome Browser android

Please try to install the certificate under both system and user certificates，Chrome seems to require a user certificate

![image](https://github.com/user-attachments/assets/ae357fa6-b49f-494d-80e9-0f8abfa5d8af)

**Comment by wajidareeb** [comment]
> > Chrome Browser android
> 
> Please try to install the certificate under both system and user certificates，Chrome seems to require a user certificate
> 
> ![image](https://private-user-images.githubusercontent.com/24794200/356053893-ae357fa6-b49f-494d-80e9-0f8abfa5d8af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTc3OTEsIm5iZiI6MTcyMzA5NzQ5MSwicGF0aCI6Ii8yNDc5NDIwMC8zNTYwNTM4OTMtYWUzNTdmYTYtYjQ5Zi00OTRkLTgwZTktMGY4YWJmYTVkOGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA2MTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZGZjY2ZjYjJjODdhZDQ0YzE3NGM2NGMzNTM2YWZmYTBhYTlhNzZhMWJkY2YzOTk1Mjk3ODI0MGJmYjI2YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d1e_L7YW-XLXdoCT9ahwFcuhouVGsVQ48ehuJpPIa3I)

I have already installed both of them but no success.

**Comment by wajidareeb** [comment]
I used latest version(1.1.4), generate new root crt and finally the issue solved
