### ISSUE TITLE
[Windows、Mac、Android]Andorid

### ISSUE THREAD

**Issue by fanyty** [wanghongenpin/network_proxy_flutter#243]
**描述错误(Describe the bug)**
https的包握手失败，已经安装好证书了
**To Reproduce**
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/136590418/aa35fe33-bafa-40ff-8419-be6f7fb84ec0)
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/136590418/4178d3de-2fff-43f3-849b-b694e82c7087)
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/136590418/b6f0cc54-d575-4dcc-a0fa-d1e3b4ee4324)

**屏幕截图(Screenshots)*

**Comment by M17764017422** [comment]
不够，还要转移到系统证书才能直接用，否则需要萝卜头加解密插件才行。

**Comment by fanyty** [comment]
转移到系统证书需要root手机吗？

**Comment by fanyty** [comment]
可否详细一点，是所有版本的安卓机现在都需要安装到根目录吗

**Comment by wanghongenpin** [comment]
安卓7.0以后默认不会信任用户下证书，需要移动到系统里，但是得需要root，另外一种方式使用xposek=框架，但也不是能抓到所有的
关于安卓证书问题，网上有大量的文章，可以搜下看下

[安卓无ROOT使用Xposed模块抓包](https://github.com/wanghongenpin/network_proxy_flutter/wiki/%E5%AE%89%E5%8D%93%E6%97%A0ROOT%E4%BD%BF%E7%94%A8Xposed%E6%A8%A1%E5%9D%97%E6%8A%93%E5%8C%85)
