### ISSUE TITLE
希望添加给请求备注的功能

### ISSUE THREAD

**Issue by z7572** [wanghongenpin/network_proxy_flutter#245]
**您的功能请求是否与问题有关？请描述.**
如果链接很长，会难以分辨所需要的请求，如果能给链接备注，可读性就会变强一些

**描述您想要的解决方案**
功能同黄鸟，可以长按一个请求然后备注内容，之后就会在所有相同的链接的上方文字中显示

**Comment by M17764017422** [comment]
已经有颜色标记功能了，我这边是够用了的，不过在这基础上加文字备注我也不反对

**Comment by wanghongenpin** [comment]
已经存在颜色标记，展示太多文字会影响请求展示
