### ISSUE TITLE
[iOS]画中画崩溃

### ISSUE THREAD

**Issue by OCer** [wanghongenpin/network_proxy_flutter#247]
**描述错误(Describe the bug)**
在iOS 12上，点击画中画必定崩溃，在iOS 17上是可以使用的
**To Reproduce**
重现行为的步骤:
在iOS 12系统上点击画中画按钮

**Comment by wanghongenpin** [comment]
我记得API好像得13以上

**Comment by wanghongenpin** [comment]
小窗口展示还用到了SwiftUI, 而且iOS新机型都是用的最新系统版本，旧系统使用较少，暂不考虑兼容较旧系统，旧系统可以先不用画中画模式
