### ISSUE TITLE
[Windows]手机设置电脑的IP和端口代理，无法抓取到https的包，手机本机的proxy pin可以抓取https的包

### ISSUE THREAD

**Issue by fanyty** [wanghongenpin/network_proxy_flutter#248]
**描述错误(Describe the bug)**

**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面

**屏幕截图(Screenshots)*

**Comment by wanghongenpin** [comment]
安卓吗? WiFi代理抓不到flutter应用请求, 可以用手机版抓包配置外部代理转发到桌面, 这是安卓系统机制
