### ISSUE TITLE
是否可以增加一个依次发送多个包的功能？

### ISSUE THREAD

**Issue by pinoren** [wanghongenpin/network_proxy_flutter#251]
**您的功能请求是否与问题有关？请描述.**
有时需要依次发送多个包多次，比如 a包，b包，c包，需要按abc顺序发送一遍，重复20次，在发送包的时候，需要把他们全部添加到收藏，然后再手忙脚乱的先发送第1个包20次，然后再发送第2个包20次，然后再发送第3个包20次，由于手工操作控时不精确，所以导致这发的20次其实顺序可能有很多次是错序的。

**描述您想要的解决方案**
希望在收藏里可以选中多个包，并使用高级重放功能按顺序（比如收藏的先后顺序）重发。

**附加上下文**
暂无。

**Comment by aiimix7811** [comment]
同样  我也有这个功能需求

**Comment by aiimix7811** [comment]
您的功能请求是否与问题有关？请描述.
可不可以增加一个抓包出来的数据包顺序回放的功能？

描述您想要的解决方案
通过导入har包，顺序回放抓到的数据包，如果包少还好分析，如果数据包几十个甚至一两百个，逐个去分析工作量非常大，可不可以增加一个har包导入批量顺序回放

附加上下文
目前市面上没有这种分析，只有一篇csdn的（基于har包录制回放的相关简介和介绍原理）https://blog.csdn.net/weixin_45741835/article/details/134510666

而我这个需求差不多，只不过你那个是收藏的重发，我这个是直接抓出来筛选过后的包保存成har之后再顺序重发

**Comment by beck-8** [comment]
在我遇到这种文档的时候，一般是将curl复制出来，手动组合脚本。调研、开发、测试也不简单的。
并且几乎所有类型的工具，都不会最开始就做这类功能

**Comment by pinoren** [comment]
> 在我遇到这种问题的时候，一般是将curl复制出来，手动组合脚本。调研、开发、测试也不简单的。 并且几乎所有类型的工具，都不会最开始就做这类功能

您说的很有道理，不过我只是作为一个用户向作者申请需求，而不是强制要求作者三天内我要看到这个功能实现。
作者肯定是要评估一个功能需求的申请是否有必要实现的，但并不是一个用户说我需要，然后另一个用户说，不，你不需要。然而就从作者没有理会这个功能申请来看，显然他的优先级并不高，但并不代表把复杂问题简单化的功能没必要提出。
或者换个说法，关于您的操作，我觉得也是需要作者来实现软件的基本功能的，会不会有一个熟练编程的大佬，跳出来说，别乱提要求，作者想怎么设计这个软件就怎么设计，提需求就是给作者添麻烦，一般有需求我都是自己从头写软件。。。🤔

**Comment by beck-8** [comment]
> > 在我遇到这种问题的时候，一般是将curl复制出来，手动组合脚本。调研、开发、测试也不简单的。 并且几乎所有类型的工具，都不会最开始就做这类功能
> 
> 您说的很有道理，不过我只是作为一个用户向作者申请需求，而不是强制要求作者三天内我要看到这个功能实现。 作者肯定是要评估一个功能需求的申请是否有必要实现的，但并不是一个用户说我需要，然后另一个用户说，不，你不需要。然而就从作者没有理会这个功能申请来看，显然他的优先级并不高，但并不代表把复杂问题简单化的功能没必要提出。 或者换个说法，关于您的操作，我觉得也是需要作者来实现软件的基本功能的，会不会有一个熟练编程的大佬，跳出来说，别乱提要求，作者想怎么设计这个软件就怎么设计，提需求就是给作者添麻烦，一般有需求我都是自己从头写软件。。。🤔

是你在曲解我的意思。我也很希望作者能添加更多的东西。我并没有说不能提出问题。只是讲现在临时的解决方案

**Comment by aiimix7811** [comment]
其实可以参考hargo，https://github.com/mrichman/hargo.git
我觉得挺好的，但是命令行的我不会用，希望可以有ui界面的，短时间不知道作者考不考虑这个功能，但是咱可以慢慢等，不着急😚

**Comment by pinoren** [comment]
> 其实可以参考hargo，https://github.com/mrichman/hargo.git 我觉得挺好的，但是命令行的我不会用，希望可以有ui界面的，短时间不知道作者考不考虑这个功能，但是咱可以慢慢等，不着急😚

一起等。。。作者在4天前把我这个提议加了一个备注同类引用问题，但是我没看明白是做的什么操作。。。

**Comment by pinoren** [comment]
> 其实可以参考hargo，https://github.com/mrichman/hargo.git 我觉得挺好的，但是命令行的我不会用，希望可以有ui界面的，短时间不知道作者考不考虑这个功能，但是咱可以慢慢等，不着急😚

喜大普奔，作者默默的在一开始就进行了“调研、开发、测试”并实现了这个功能！( ˝ᗢ̈˝ )

**Comment by pinoren** [comment]
> 其实可以参考hargo，https://github.com/mrichman/hargo.git 我觉得挺好的，但是命令行的我不会用，希望可以有ui界面的，短时间不知道作者考不考虑这个功能，但是咱可以慢慢等，不着急😚

作者默默的变通实现了这个功能。。。实现的途径是把指定域名下的所有包用高级功能可以依次重发一遍。

下一个期待就是能通过高级功能多次重发վ'ᴗ' ի

**Comment by pinoren** [comment]
。。。发现个用法，重放域名下的请求每次都是倍增，重放操作五次就已经是62次了。。。

**Comment by pinoren** [comment]
作者大佬：重放域名下的请求没有重放间隔控制，每次都是无间隔一通猛发。。。

**Comment by wanghongenpin** [comment]
> 。。。发现个用法，重放域名下的请求每次都是倍增，重放操作五次就已经是32遍重发了。。。

因为每次重放会使得当前域名下倍增， 下次重放域名下请求自然会翻倍

**Comment by pinoren** [comment]
> > 。。。发现个用法，重放域名下的请求每次都是倍增，重放操作五次就已经是32遍重发了。。。
> 
> 因为每次重放会使得当前域名下倍增， 下次重放域名下请求自然会翻倍

这个功能使得多次重发变得方便。多谢作者大佬\(  ͯω  ͯ)/
