### ISSUE TITLE
[Windows、Mac、Android]xxx

### ISSUE THREAD

**Issue by fuoins** [wanghongenpin/network_proxy_flutter#252]
- [ ] **重写响应 会不接收这个包直接应用会不加载 不是网的问题 我替换![Screenshot_2024-07-03-23-01-45-956_com.network.proxy.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/127714490/5ca03bd9-0f60-4d5e-b21c-e9f08f4b3d9b)

[.*?]  的内容时出现的 我用小黄鸟同样的正则规则去修改是可以的**

**然后我用了安卓12和14都试了 刷了模块系统证书是有的开了https 应该是bug**

**屏幕截图(Screenshots)*

**Comment by wanghongenpin** [comment]
发下原请求体

**Comment by wanghongenpin** [comment]
没有进一步反馈,先关闭了,可以试下最新版本,是否存在问题, 如果有进展欢迎重新打开
