### ISSUE TITLE
[Windows、Mac、Android]在关闭抓包时，编辑请求功能发送的请求未被记录

### ISSUE THREAD

**Issue by z7572** [wanghongenpin/network_proxy_flutter#253]
**描述错误(Describe the bug)**
与重写和高级重写不同，编辑请求功能发送的请求只有在开启抓包时才会被记录到请求列表，而前者在关闭抓包时的请求仍可以被记录

**Comment by wanghongenpin** [comment]
桌面端发起请求会获取系统代理，没设置就会看不到请求，
手机端都是可以看到的吧？

**Comment by z7572** [comment]
> 桌面端发起请求会获取系统代理，没设置就会看不到请求， 手机端都是可以看到的吧？

手机端也看不到

**Comment by wanghongenpin** [comment]
V1.1.2版本已经支持

https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.2
