### ISSUE TITLE
[Windows、Mac、Android] Changing 'Host' in headers effects the host in uri

### ISSUE THREAD

**Issue by HuaTaoFnox** [wanghongenpin/network_proxy_flutter#254]
In my case, I need to set a different value for 'Host' than the one in URI.
But it seems like the URI has been sent used the value I set in 'Host'.

**Comment by wanghongenpin** [comment]
Request rewrite changes the Header Host but it doesn't take effect?

**Comment by wanghongenpin** [comment]
If you want to modify the target domain name, which is not supported yet, you can use redirection to achieve the corresponding effect

**Comment by HuaTaoFnox** [comment]
Thank you for your time. But I'm afraid it's not what I wanted.
The redirection just looks same, but the url actually is the other host.
e.g. The url is https://aaa.com, the host in headers is "host": "bbb". The backend of aaa.com needs the "host" to route it.

**Comment by wanghongenpin** [comment]
You can use request rewrite to implement request update

![QQ_1722952607717](https://github.com/user-attachments/assets/ce90ec48-15dc-425a-9c37-20f7b2bb40a9)
