### ISSUE TITLE
安卓，啥情况

### ISSUE THREAD

**Issue by hsimw** [wanghongenpin/network_proxy_flutter#256]
![Screenshot_2024-07-12-03-47-47-575_com network proxy](https://github.com/user-attachments/assets/b58a2c04-53b1-4419-9edd-18bf553170e4)

**Comment by beck-8** [comment]
问题是什么？

**Comment by hsimw** [comment]
> 问题是什么？

ssl握手失败

**Comment by beck-8** [comment]
> > 问题是什么？
> 
> ssl握手失败

点进去有具体的错误

**Comment by hsimw** [comment]
> > > 问题是什

> > > 问题是什么？
> > 
> > 
> > ssl握手失败
> 
> 点进去有具体的错误，看一下

![Screenshot_2024-07-19-15-12-10-294_com network proxy](https://github.com/user-attachments/assets/dce27606-2d01-48e0-98b9-a742bde6fc51)

**Comment by beck-8** [comment]
6

**Comment by beck-8** [comment]
难怪作者不愿搭理

**Comment by beck-8** [comment]
这么多页面你就不会都点点看一下？

**Comment by beck-8** [comment]
Null check operator used on a null

**Comment by hsimw** [comment]
> 版本号/手机型号/系统版本都写一下

1.0.9/Redmi K60 Ultra/1.0.15.0.UMLCNXM

**Comment by wanghongenpin** [comment]
局域网请求如果不影响使用可以先忽略,或者设置抓指定APP

**Comment by wanghongenpin** [comment]
可以试下最新版包, 修复了一些连接失败得请求展示成ip了
