### ISSUE TITLE
deepin下提示找不到文件

### ISSUE THREAD

**Issue by skyrimt** [wanghongenpin/network_proxy_flutter#258]
deepin下抓https是提示   -1  PathNotFoundException: Cannot open file, path = 'assets/certs/server.crt' (OS Error: 没有那个文件或目录, errno = 2)

**屏幕截图(Screenshots)*
![image](https://github.com/user-attachments/assets/7d76b6d3-17b6-4fa9-b94a-012a85c6f1cb)

**Comment by skyrimt** [comment]
最新版本v1.1出现，换成v1.0.9后可以正常使用

**Comment by wanghongenpin** [comment]
已经重新打包, 现在最新的包好了
