### ISSUE TITLE
使用脚本功能时，在编辑中文本过长没有横向滚动条，无法做对应的编辑

### ISSUE THREAD

**Issue by xyabc120** [wanghongenpin/network_proxy_flutter#260]
**您的功能请求是否与问题有关？请描述.**
如题，在做一些请求和响应根据规则变更时，遇到当行字符串比较长时，编辑器没有横向滚动条，使用非常不友好，希望可以加入对应功能，或自动换行开关

**描述您想要的解决方案**
- 编辑器可横向滚动
- 自动换行开关

**Comment by wanghongenpin** [comment]
建议使用其他代码编辑器吧，如果做一个完善的代码编辑器 工作量较大

**Comment by wanghongenpin** [comment]
在其他文本编辑好，复制过来

**Comment by xyabc120** [comment]
不需要弄很完善的编辑器，支持换行显示或者加滚动条就好。从其他应用复制太麻烦，尤其在写调试代码的时候，切来切去 每次长按选择复制粘贴很费劲，真当你有这种场景编辑的时候就很能理解了

**Comment by wanghongenpin** [comment]
桌面端吗

**Comment by xyabc120** [comment]
> 桌面端吗

ios

**Comment by wanghongenpin** [comment]
ios两指可以左右滑动

> ios
