### ISSUE TITLE
程序窗口bug，导致修改响应体的时候，超过窗口的内容不显示。 最终导致这一条规则修改失败

### ISSUE THREAD

**Issue by es3344520** [wanghongenpin/network_proxy_flutter#261]
如题，这个就是因为修改响应体的程序窗口，如果修改的内容过长，就不会显示需要修改的内容。 
后面把相关内容改成1，就可以正常显示。 因此可以判断出来， 就是因为这个地方的窗口问题导致的   

MAC版本， 软件版本1.1.0  

 
![1](https://github.com/user-attachments/assets/4c59741a-8f96-4ea4-b0be-4444ef9321a4)
![2](https://github.com/user-attachments/assets/157f5d71-07e0-4137-b866-5bb2e617d192)
![3](https://github.com/user-attachments/assets/cdd6767e-20f3-4ba0-b9d0-743300102a35)

**Comment by wanghongenpin** [comment]
是英文单词渲染导致的，对于英文单词 如果后面不够完整展示，那么会换行展示，如果英文单词展示一般会导致阅读影响

**Comment by wanghongenpin** [comment]
还有规则会生效，只是展示问题

**Comment by es3344520** [comment]
> 还有规则会生效，只是展示问题

无法生效，已经测试过了

**Comment by es3344520** [comment]
上面一条修改正常匹配而且生效，下面一条就又出现这种情况，实际测试过，无法生效。 

![1](https://github.com/user-attachments/assets/547e981d-b54e-4a37-8e73-d1d8ce47af0a)
![2](https://github.com/user-attachments/assets/303ce06f-5b0b-4e8f-a9a8-4f47a1e7d481)

**Comment by wanghongenpin** [comment]
我这里没显示出来，但是最后响应是生效了
<img width="381" alt="image" src="https://github.com/user-attachments/assets/25e9b0ec-a243-4646-90f6-86c936238364">

<img width="698" alt="image" src="https://github.com/user-attachments/assets/10f753d2-898e-4e0e-8694-265369e56eac">

<img width="547" alt="image" src="https://github.com/user-attachments/assets/87e96d88-35ce-48eb-abb7-2e78c8596a68">

**Comment by es3344520** [comment]
......我重放试试，因为目前是针对， 对应的程序没有生效这一条。      不过这个显示问题还是要修复一下， 即便是可以正常匹配修改， 很容易被误解。

**Comment by wanghongenpin** [comment]
最新版V1.1.1已经处理换行问题

https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.1
