### ISSUE TITLE
[Mac]下载最新版,打开白屏没任何反应

### ISSUE THREAD

**Issue by zhangya4548** [wanghongenpin/network_proxy_flutter#263]
**描述错误(Describe the bug)**
[Mac]下载最新版,打开白屏没任何反应
**To Reproduce**
[Mac]下载最新版,打开白屏没任何反应

**屏幕截图(Screenshots)*
<img width="1329" alt="Xnip2024-07-19_16-54-12" src="https://github.com/user-attachments/assets/a89a81a5-d639-4f43-99a0-5e10a0eed6fc">

**Comment by zhangya4548** [comment]
关闭退出重试也还是一样

**Comment by zhangya4548** [comment]
下载的是 [V1.1.0](https://gitee.com/wanghongenpin/network-proxy-flutter/releases/tag/1.1.0)

**Comment by zhangya4548** [comment]
v1.9, v1.8, v1.7 均下载尝试使用都一样

**Comment by wanghongenpin** [comment]
从来没见别人反馈过类似问题，主要是没法复现，如果条件允许，可以拉下代码，编译运行下

**Comment by wanghongenpin** [comment]
看报错日志知道问题就好处理了

**Comment by zhangya4548** [comment]
怎么编译运行?有文档吗?

**Comment by wanghongenpin** [comment]
https://docs.flutter.cn/get-started/install/macos/desktop

**Comment by zhangya4548** [comment]
看过了,完全不懂,太难了我放弃使用了

**Comment by pxvp2008** [comment]
遇到了一样的问题
