### ISSUE TITLE
[Android]

### ISSUE THREAD

**Issue by fanyty** [wanghongenpin/network_proxy_flutter#266]
**描述错误(Describe the bug)**
请问pb协议的请求，抓取到的16进制的请求和响应的数据是完整的吗？

**Comment by wanghongenpin** [comment]
不支持, 16进制是完整的

**Comment by fanyty** [comment]
我的理解是，所以这个抓包工具，pb协议的请求，抓取不到完整的请求和响应数据是吗？

**Comment by wanghongenpin** [comment]
是完整得
