### ISSUE TITLE
V1.1.1版本 Android/编辑请求报错

### ISSUE THREAD

**Issue by w342655** [wanghongenpin/network_proxy_flutter#268]
**描述错误(Describe the bug)**
https编辑请求报错，1.1.1版本
**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面

**屏幕截图(Screenshots)*

![Screenshot_2024-08-02-21-54-58-937_com network proxy](https://github.com/user-attachments/assets/c98e9e43-cd3a-4815-a0bf-4d12da1eee74)
![Screenshot_2024-08-02-21-55-03-101_com network proxy](https://github.com/user-attachments/assets/3764beb9-c111-44e0-8a44-148ed7973eb5)
![Screenshot_2024-08-02-21-55-20-231_com android settings](https://github.com/user-attachments/assets/64d8ddb9-4f09-4d2a-bb65-d52eed972737)
![Screenshot_2024-08-02-21-55-39-637_com android settings](https://github.com/user-attachments/assets/abea00f8-9170-47ca-97c6-8ebc458de52e)

**Comment by wanghongenpin** [comment]
400和请求参数有关系, 他不是提示让用https

**Comment by w342655** [comment]
> 400和请求参数有关系，他不是提示让用https

但是1.0.9版本就能编辑请求

**Comment by w342655** [comment]
> 400和请求参数有关系, 他不是提示让用https

![Screenshot_2024-08-03-21-37-21-115_com network proxy](https://github.com/user-attachments/assets/a2e81fef-4774-4ca3-b5c9-c66a6ea48a1c)

**Comment by wanghongenpin** [comment]
发下curl请求

**Comment by w342655** [comment]
> 发下curl请求

curl -X POST 'https://sctel10000.cn/haoyl/llpReport/biz/dataCollection' \
  -H 'Host: sctel10000.cn' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 301' \
  -H 'charset: utf-8' \
  -H 'User-Agent: Mozilla/5.0 (Linux; Android 14; 23113RKC6C Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 XWEB/1160117 MMWEBSDK/20240103 MMWEBID/9978 MicroMessenger/8.0.48.2588(0x28003043) WeChat/arm64 Weixin GPVersion/1 NetType/4G Language/zh_CN ABI/arm64 MiniProgramEnv/android' \
  -H 'content-type: application/json' \
  -H 'Accept-Encoding: gzip,compress,br,deflate' \
  -H 'Referer: https://servicewechat.com/wx3bff267ece0861a0/81/page-frame.html'  \
   --data '{"userPhone":"7d4b2845a99a54f088354f9d28f11bf5","user_phone":"","configTag":"ykzq_index","value1":"pages/index/index?channelID=&subChannelID=&promo_code=","value2":"四川电信云卡专区","value3":"","promo_code":"","value4":"登录","value5":"单C","value6":"23113RKC6C","timestamp":1722609793409}' \
  --compressed

**Comment by wanghongenpin** [comment]
最新1.1.0包已经修复

**Comment by w342655** [comment]
> 最新1.1.0包已经修复

收到
1.1.1版本不行吗

**Comment by w342655** [comment]
> 最新1.1.0包已经修复

谢谢大佬了

**Comment by w342655** [comment]
> 最新1.1.1包已经修复

我又发现了个bug怎么办😂

**Comment by w342655** [comment]
curl -X GET 'https://xrm.189store.com/minio/liulp/video_icon/6%E8%A7%86%E9%A2%913.png' \
  -H 'Host: xrm.189store.com' \
  -H 'Connection: keep-alive' \
  -H 'User-Agent: Mozilla/5.0 (Linux; Android 14; 23113RKC6C Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 XWEB/1160117 MMWEBSDK/20240103 MMWEBID/9978 MicroMessenger/8.0.48.2588(0x28003043) WeChat/arm64 Weixin GPVersion/1 NetType/WIFI Language/zh_CN ABI/arm64 MiniProgramEnv/android' \
  -H 'Accept: image/wxpic,image/tpg,image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8' \
  -H 'X-Requested-With: com.tencent.mm' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'Sec-Fetch-Mode: no-cors' \
  -H 'Sec-Fetch-Dest: image' \
  -H 'Referer: https://servicewechat.com/wx3bff267ece0861a0/81/page-frame.html' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7'  \
   --compressed

**Comment by w342655** [comment]
把curl请求链接改成https://xrm.189store.com/minio/liulp/video_icon/6视频1.png就能正常请求，应该是编辑请求那个没有解密

**Comment by w342655** [comment]
编辑请求的链接未url解密

**Comment by wanghongenpin** [comment]
最新包已经处理url解码

**Comment by w342655** [comment]
> 最新包已经处理url解码

谢谢大佬

**Comment by w342655** [comment]
> 最新包已经处理url解码
还是不行
![Screenshot_2024-08-04-07-28-44-071_com network proxy](https://github.com/user-attachments/assets/ed15f737-ae94-4ebc-9677-72f77a97dc67)
![Screenshot_2024-08-04-07-28-39-484_com network proxy](https://github.com/user-attachments/assets/20b0d0ee-2485-4de8-ab90-d87651d8dafd)
![Screenshot_2024-08-04-07-28-34-639_com network proxy](https://github.com/user-attachments/assets/84ccfbe0-afef-4c64-99bc-3a8d4fe676c4)

![Screenshot_2024-08-04-07-28-53-365_com network proxy](https://github.com/user-attachments/assets/eeffe2ce-d4c8-4f27-b952-5b56315d1b43)

**Comment by w342655** [comment]
有中文的链接编辑请求都是url加密了的请求不到路经就会报错

**Comment by wanghongenpin** [comment]
> 有中文的链接编辑请求都是url加密了的请求不到路经就会报错

最新版包已经处理url编码

**Comment by w342655** [comment]
> > 有中文的链接编辑请求都是url加密了的请求不到路经就会报错
> 
> 最新版包已经处理url编码

这次可以了，谢了大佬
