### ISSUE TITLE
[Android]无法导入p12证书

### ISSUE THREAD

**Issue by Rw-Ro** [wanghongenpin/network_proxy_flutter#269]
无法导入这个证书
https://pan.huang1111.cn/s/6ea3XIN
密码:
01

**Comment by Rw-Ro** [comment]
应该不是证书的问题，另一个同类型软件Reqable可以安装这个证书。

**Comment by wanghongenpin** [comment]
V1.1.3版本已经处理
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.3
