### ISSUE TITLE
[Windows]

### ISSUE THREAD

**Issue by qkkas** [wanghongenpin/network_proxy_flutter#272]
**描述错误(Describe the bug)**
IDM下载的所有包都抓不到，尝试了多个网站，而且好像只能抓到edge的包
**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面
打开idm抓包
**屏幕截图(Screenshots)*

**Comment by wanghongenpin** [comment]
不是所有软件都支持代理得, 请尝试下其他抓包软件可以是否看可以抓到

**Comment by wanghongenpin** [comment]
可以看下软件是否支持设置代理，把代理地址端口配置成抓包的端口
