### ISSUE TITLE
ios17.6无法正常抓包

### ISSUE THREAD

**Issue by huahuazh358** [wanghongenpin/network_proxy_flutter#273]
证书和https都开了，点击软件抓取不会自动创建vpn抓不到任何东西

**Comment by denny-acquired** [comment]
ios 17.3 也是，前段时间还可以抓包的，现在抓不到了

**Comment by denny-acquired** [comment]
ios 17.3 也是，前段时间还可以抓包的，现在抓不到了

**Comment by wanghongenpin** [comment]
用TF最新版1.1.2试下呢，需要开启https抓包

**Comment by denny-acquired** [comment]
> 用TF最新版1.1.2试下呢，需要开启https抓包

1.1.2这版本可以抓到了
