### ISSUE TITLE
[Android]求助怎么删除请求参数

### ISSUE THREAD

**Issue by mydracula** [wanghongenpin/network_proxy_flutter#274]
假如我的地址是
https://bizi.qijishow.com/uploads/2024-08-07/269bfa37a3870bf410d7770bde2fdc97.jpg?imageView2/0/w/900
我本来是用的请求重写想删除参数但是没什么作用可能因为他不是k=v这种
现在是用了脚本功能
```
async function onRequest(context, request) {
 request.url = request.url.replace('?imageView2/0/w/900','')
 request.queries ={}
 const newRequest = { ...request }
 return newRequest;
}
```
为什么地址后面的问号怎么样都移除不了 我把queries给删了或者null或者{}都不行 然后很奇怪即使带了问号也是可以访问的 这个响应我并没有做处理为什么无法正确的显示一个图片
![1723052050366](https://github.com/user-attachments/assets/81cd7075-3c6e-46f3-80a3-21d0ea85ef9c)
下面是视频
https://file.uhsea.com/2408/4b922e877ef2737fa7e6b5247b2e296aYE.mp4

**Comment by wanghongenpin** [comment]
?号不影响吧，只要没有参数就行

**Comment by mydracula** [comment]
> ?号不影响吧，只要没有参数就行

麻烦您看看视频 我写的那个脚本正常返回响应 但是他实际上没有返回图片 我手动重发就正常返回了

**Comment by wanghongenpin** [comment]
develop分支代码已经提交, 你那边可以打包吗

**Comment by mydracula** [comment]
> develop分支代码已经提交, 你那边可以打包吗

我以为我没说清楚问题 刚刚又录了个小黄鸟的
没想到您大晚上还修问题太给力了  那我必须能打包啊 不知道为啥一大堆报错
![image](https://github.com/user-attachments/assets/e4bb9574-b86d-4cf9-b626-dd04e5f9cfdd)
这个问题修复了 只不过这个图片显示有点问题

https://github.com/user-attachments/assets/9f138374-0fd9-451b-aed4-a4a2b79205b3


https://github.com/user-attachments/assets/e14ec13e-2bff-4a00-bb26-47f7f753891a



用很久了这个一直觉得这个比小黄鸟好用多了 就是响应内容是二进制文件的预览不够好  之前用的还是哆啦A梦图标连二进制文件响应都是文本预览的版本  上星期刚更新的版本更好用了  我看issues都和小黄鸟比 那说明已经做得非常可以了 希望作者更加完善越来越好
