### ISSUE TITLE
[Android]抓取uniapp打包的app 视频大概率无法完全播放

### ISSUE THREAD

**Issue by huajiqaq** [wanghongenpin/network_proxy_flutter#275]
**描述错误(Describe the bug)**
使用proxypin抓取uniapp打包的app 如果涉及到视频播放 该视频在抓包过程中就大概率无法正常完全播放
使用同由flutter编写的reqable没有这个问题 应该不是flutter的问题
**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面
apk https://tmp.link/f/66b41811b2455
当打开软件时开启proxypin 就会出现
如果没有就重启即可轻易复现
另外即使可以加载 那么也很容易无法完全播放
**屏幕截图(Screenshots)*
无

**Comment by huajiqaq** [comment]
https://github.com/user-attachments/assets/88da0352-3fe2-4daf-a853-04da870f8247

已经测试并非软件自带验证导致 我写了个demo demo里使用的链接是https://www.w3school.com.cn/example/html5/mov_bbb.mp4 理论应该可以加载

**Comment by huajiqaq** [comment]
分三次测试
打开proxyopin 视频在加载一定时间后无限加载
关闭proxypin 可以正常加载视频
打开proxypin 视频出现无限加载

**Comment by wanghongenpin** [comment]
现在请求内容都是在内存中，太大请求确实有点问题

**Comment by wanghongenpin** [comment]
我这可以播放,  保持网络良好, 播放会慢,或者把视频域名加入代理黑名单, 这样就会支持转发视频

https://github.com/user-attachments/assets/9f42cb0b-04d2-4a50-9d09-46b1a663ce83

**Comment by huajiqaq** [comment]
那可能是我设备问题 那我就不打扰了
