### ISSUE TITLE
有相关使用文档吗？

### ISSUE THREAD

**Issue by 20041010** [wanghongenpin/network_proxy_flutter#278]
**您的功能请求是否与问题有关？请描述.**
对问题所在的清晰简洁的描述[...]

**描述您想要的解决方案**
对你想要发生的事情进行清晰简洁的描述.

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by 20041010** [comment]
有相关使用文档吗？

**Comment by wanghongenpin** [comment]
和其他抓包软件没什么区别，你需要什么文档？

**Comment by wanghongenpin** [comment]
https://github.com/wanghongenpin/network_proxy_flutter/wiki

https://www.bilibili.com/video/BV1Qm4y157Gk/
