### ISSUE TITLE
建议增加关闭按钮后可最小化托盘图标的功能

### ISSUE THREAD

**Issue by chung1912** [wanghongenpin/network_proxy_flutter#279]
建议增加关闭按钮后可最小化托盘图标的功能，可以在设置里面设置，按x按钮后最小化到托盘图标，而不是直接退出软件

**Comment by wanghongenpin** [comment]
点击-按钮不是最小化吗

**Comment by chung1912** [comment]
> 点击-按钮不是最小化吗

就是到托盘图标，不会出现在任务栏那种。最小化那个会在任务栏。就像微信qq那样，点叉叉之后在托盘，点最小化在任务栏
