### ISSUE TITLE
抓包失败

### ISSUE THREAD

**Issue by xingluo233** [wanghongenpin/network_proxy_flutter#28]
https://play.google.com/store/apps/details?id=com.sfacg.oversea

这个软件，我用了大部分抓包软件包括本项目都抓不到包，用Httpcanary抓其他软件就算失败也会报错 但抓这个软件没有任何报错

**Comment by wanghongenpin** [comment]
安卓大部分都不信任用户证书，其实是ssl校验失败了，后面会给出提示，或者root下，放到系统证书，有没有遇到Httpcanary能抓但是这个不能抓的

**Comment by xingluo233** [comment]
> 安卓大部分都不信任用户证书，其实是ssl校验失败了，后面会给出提示，或者root下，放到系统证书，有没有遇到Httpcanary能抓但是这个不能抓的

已经把证书放到系统分区了

**Comment by wanghongenpin** [comment]
> https://play.google.com/store/apps/details?id=com.sfacg.oversea
> 
能否发个apk下载链接，我试下

**Comment by xingluo233** [comment]
> > https://play.google.com/store/apps/details?id=com.sfacg.oversea
> > 
> 能否发个apk下载链接，我试下
> 
> 

https://wkkc.vip/s/20AUI1xDLmjv请点击链接获取《SuperFantasy_1.0.34.apks》,有效期至 :2023-08-06 15:52 或访问 ：https://wkkc.vip | 取件码：049403

**Comment by wanghongenpin** [comment]
> https://wkkc.vip/s/20AUI1xDLmjv

这个软件我测了，用户证书root抓不了，不过现在显示握手失败的请求了，系统证书我还没法测，小米解锁还等几天，等过几天能root了我试下

**Comment by wanghongenpin** [comment]
重新下载下最新的安卓包可以么

**Comment by xingluo233** [comment]
> 重新下载下最新的安卓包可以么

还是不行

**Comment by wanghongenpin** [comment]
你这个软件我用Httpcanary也抓不了，微信其他软件都可以，安卓10以下的不支持，请保证系统证书能看到ProxyPin根证书
![6d34a6f2b4c714a7b02ce63135fe2cfa](https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/54ded624-8c8e-4654-ac11-022f073b622c)
