### ISSUE TITLE
[Android]请求重放&脚本修改链接时会改变URL

### ISSUE THREAD

**Issue by Left-Hai** [wanghongenpin/network_proxy_flutter#283]
**描述错误(Describe the bug)**
问题描述：重放或者脚本拦截时请求的路径被修改，大部分网站可以正常访问，但是有些接口会请求失败

**To Reproduce**
版本：1.1.1
开启HTTPS代理，已安装系统证书
外部代理设置，Charles: 127.0.0.1:8888，方便观察请求的差异

1、打开ProxyPin开启HTTPS代理和外部代理(Charles)
2、浏览器访问地址：httpbin.org,请求如下：
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/3cdc4959-5aba-415a-9e8e-976f1cffe8a1">
3、ProxyPin重放该请求，截图如下：
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/fd416778-7963-411c-b193-fad004d74325">

大部分的请求都可以正常获取响应，少数接口会因为这个变化导致响应失败

**Comment by wanghongenpin** [comment]
多谢反馈, 最新包已经处理

**Comment by wanghongenpin** [comment]
V1.1.2版本已经处理

https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.2
