### ISSUE TITLE
[Android]请求重发错误

### ISSUE THREAD

**Issue by MrMoxing** [wanghongenpin/network_proxy_flutter#286]
**描述错误(Describe the bug)**

现在重发不支持 Https 重发吗？还是Bug？
链接是 https，但是重发是以 http 重发的，会导致 
“The plain HTTP request was sent to HTTPS port”

**屏幕截图(Screenshots)*

![S40815-14262329_com.network.proxy.png](https://github.com/user-attachments/assets/d52fff4f-08a9-428a-8e52-5d22e511164c)

**Comment by wanghongenpin** [comment]
用最新的包试下

**Comment by MrMoxing** [comment]
> 用最新的包试下

就是最新包 1.1.1
