### ISSUE TITLE
[ios] 针对跨域接口的拦截脚本异常 貌似是微信webview的问题

### ISSUE THREAD

**Issue by k186** [wanghongenpin/network_proxy_flutter#288]
**描述错误(Describe the bug)**
针对跨域接口创建的脚本 会导致options 后的post请求没有出发，安卓和 ios 都有这个问题。创建空白脚本就会出现。

**To Reproduce**
新增脚本，填写拦截的url 不做任何改动，只能发送opitons请求，无法发送后续post 请求

**屏幕截图(Screenshots)*

![image](https://github.com/user-attachments/assets/1409c44d-195a-4b49-a4f8-31fb0ab6238d)

![image](https://github.com/user-attachments/assets/297fab00-c430-425a-b1cf-b8bf160f0a73)

**Comment by k186** [comment]
在ios 版本 使用的okHTTP这个库请求转发的 webview请求；同样页面在 嵌套的微信 webview 就正常的，

**Comment by k186** [comment]
同一个脚本 不同 app表现不一致，被抓的是个跨端项目，APP 端看他使用的okhttp这个库 这个库能正常，但是他web端放在微信浏览器里面就不行

**Comment by wanghongenpin** [comment]
最新包还有问题,修复了脚本一些问题

**Comment by wanghongenpin** [comment]
使用最新把版本V1.1.3

**Comment by k186** [comment]
国庆节我试试后反馈。 这几天没空

wanghongenpin ***@***.***> 于2024年9月15日周日 21:10写道：
