### ISSUE TITLE
安卓版使用后的一点小建议

### ISSUE THREAD

**Issue by JavaCodeMing** [wanghongenpin/network_proxy_flutter#29]
1、希望能在域名白名单的基础上添加app应用白名单功能。
2、希望在全部请求的列表项支持删除单个的功能。
3、希望在域名列表中能按app应用做一级分类，按域名做二级分类。

**Comment by wanghongenpin** [comment]
1和2最近做下，3可能不太好获取哪个应用请求得，先不做

**Comment by wanghongenpin** [comment]
1和2最新版本已经有了，3目前先不做
![Weixin Image_20230816183824](https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/545609b0-07af-455b-8609-e29a444114c4)

**Comment by JavaCodeMing** [comment]
> 1和2最新版本已经有了，3目前先不做
> ![Weixin Image_20230816183824](https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/545609b0-07af-455b-8609-e29a444114c4)
> 

好的，应用白名单已经用上了，效果很好，非常感谢！
