### ISSUE TITLE
[Mac]无法访问局域网？

### ISSUE THREAD

**Issue by devcxm** [wanghongenpin/network_proxy_flutter#292]
**To Reproduce**

执行命令
```shell
export https_proxy=http://127.0.0.1:9099 http_proxy=http://127.0.0.1:9099 all_proxy=socks5://127.0.0.1:9099

curl 192.168.1.1 
```

根据日志，好像是代理软件访问url路径出错了？

**Comment by wanghongenpin** [comment]
我这边可以，请给出详细的日志
<img width="710" alt="image" src="https://github.com/user-attachments/assets/b803a747-7926-44b7-b305-dcbf874250b7">

**Comment by wanghongenpin** [comment]
我这边可以，有详细日志吗？

<img width="712" alt="image" src="https://github.com/user-attachments/assets/18c1476f-7795-429c-a461-c98f09d74a6a">

<img width="979" alt="image" src="https://github.com/user-attachments/assets/78574ca3-bc60-46c5-be3c-d6a10af1fb38">

**Comment by devcxm** [comment]
可能跟 #283有关，拉取最新代码后可以了。

**Comment by devcxm** [comment]
> 我这边可以，有详细日志吗？
> 
> <img alt="image" width="712" src="https://private-user-images.githubusercontent.com/24794200/361294890-18c1476f-7795-429c-a461-c98f09d74a6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTEzNDgsIm5iZiI6MTcyNDY1MTA0OCwicGF0aCI6Ii8yNDc5NDIwMC8zNjEyOTQ4OTAtMThjMTQ3NmYtNzc5NS00MjljLWE0NjEtYzk4ZjA5ZDc0YTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA1NDQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNTBkZjk2Mzg1ZGFlYmIwNmE4NzQzOGNkMmNhMTQ5MDU4NTdiYWQ1Nzg1NGVjOTQyNmZhZmVlZWRjMTk4ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t3CUjOCvPdTvd5Oo8wvfa5pJCBqO3GA-nTcgMQzJxA0"> <img alt="image" width="979" src="https://private-user-images.githubusercontent.com/24794200/361294863-78574ca3-bc60-46c5-be3c-d6a10af1fb38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTEzNDgsIm5iZiI6MTcyNDY1MTA0OCwicGF0aCI6Ii8yNDc5NDIwMC8zNjEyOTQ4NjMtNzg1NzRjYTMtYmM2MC00NmM1LWJlM2MtZDZhMTBhZjFmYjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA1NDQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZDI0MzAyOGM1MzE2MDdmNGU1Y2I0NWE4OGEwNzlmODI3MzdmMmRiOGI0YTQ4MDRlZWNkOWNiMzk1NmUwYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-J4i7iszhZq7LA-jEpCVEQHRHGWA1zEPLCj6ypkxCyY">

@wanghongenpin 刚发现一个问题不知道是不是存在，设置外部代理后，是不是会把http请求转成https？你curl你这个127.0.0.1:8080试试

**Comment by wanghongenpin** [comment]
无法复现，我外部代理配置7890都能正常访问

**Comment by devcxm** [comment]
> > 无法复现，我外部代理配置7890都能正常访问
> 
>  8.27.2.mp4 
> 刚刚测试，在另一台电脑使用Charles测试没问题。但在录屏这台电脑用Charles测试会出现问题，换另一个代理软件ProxyMan作为外部代理软件却可以正常请求。可能是Charles的问题吧。

补充一下，录屏出问题这台是因为开启了脚本测试：
<img width="711" alt="Screenshot 2024-08-27 at 21 37 06" src="https://github.com/user-attachments/assets/69d92823-9a7b-4296-9895-bd2a804a72d7">

**Comment by wanghongenpin** [comment]
使用V1.1.2最新包试下

**Comment by devcxm** [comment]
> 使用V1.1.2最新包试下

已修复
