### ISSUE TITLE
[Android]这个网站抓包抓不到响应体，导致页面空白

### ISSUE THREAD

**Issue by zidekuls** [wanghongenpin/network_proxy_flutter#297]
**描述错误(Describe the bug)**
开发者你好，对下面网站进行抓包，响应体为空，页面空白
https://www.catpeijian.cn/zh-CN/cat
**To Reproduce**
重现行为的步骤: 
直接在手机浏览器访问，进行抓包，可以看到没有响应体，页面空白。
其他网址都是正常抓包的，用小黄鸟试着对这网址能正常抓包显示出页面
**屏幕截图(Screenshots)*

无响应体如图
![无响应体](https://github.com/user-attachments/assets/5c24bd02-f5de-448f-89dc-d5e5c26dd362)

页面空白如图
![页面空白](https://github.com/user-attachments/assets/3a8f212c-dd51-4e45-8db0-dd431863321c)

小黄鸟如图，多了一个head请求？不懂为什么会这样
![Screenshot_2024-08-29-05-26-47-862_com guoshi httpcanary premium](https://github.com/user-attachments/assets/234ff075-2403-4496-909a-c5e92b272c30)

**Comment by mdikjse** [comment]
试了下我的也一样，确实空白了。。。

**Comment by wanghongenpin** [comment]
这个网站编码多了个空格,我处理下

![QQ_1724942054398](https://github.com/user-attachments/assets/5fe1e4ec-af1d-495b-98a6-460de8b6586f)

**Comment by wanghongenpin** [comment]
V1.1.2最新包已经处理

**Comment by zidekuls** [comment]
> V1.1.2最新包已经处理

大佬神速！

**Comment by zidekuls** [comment]
> V1.1.2最新包已经处理

意识到其他平台可能也有同样的问题，我用windows版试了，也重现了

**Comment by wanghongenpin** [comment]
> 
> 意识到其他平台可能也有同样的问题，我用windows版试了，也重现了

其他平台后面会打包

**Comment by wanghongenpin** [comment]
V1.1.3版本已经处理
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.3
