### ISSUE TITLE
Android]纸间书摘开启后软件搜索功能就用不了了

### ISSUE THREAD

**Issue by childeyouyu** [wanghongenpin/network_proxy_flutter#298]
**描述错误(Describe the bug)**
是用的是安卓版本，抓包软件纸间书摘的搜索功能，开启猴搜索功能旧不能用了，提示网络错误。

**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面
稳定复现

**屏幕截图(Screenshots)*

**Comment by Kr1s77** [comment]
遇到了相似的问题：小红书开启抓包后，软件搜索功能就用不了了
使用 charles 抓包正常，但是使用此软件抓不到搜索接口 "api/sns/v10/search/notes" 的数据包，但是不是每次都抓不到，可能会出现抓到一两页的情况，然后继续滑动就抓取不到了

**Comment by wanghongenpin** [comment]
安卓需要系统证书,请先尝试其他抓包是否可以

**Comment by wanghongenpin** [comment]
无法复现,请提供视频或者截图

**Comment by childeyouyu** [comment]
> 无法复现,请提供视频或者截图

GitHub 有视频大小限制，发邮箱了。

**Comment by wanghongenpin** [comment]
证书问题, 请将证书安装到系统下,  也可以尝试其他抓包软件

**Comment by xiaohao890809** [comment]
> 证书问题, 请将证书安装到系统下, 也可以尝试其他抓包软件

请问怎么安装证书呢，一加11的安卓14系统，需要root吗？
