### ISSUE TITLE
[iOS]手机使用流量，分享热点给其他设备使用，抓其他设备的http请求

### ISSUE THREAD

**Issue by wangzhi17** [wanghongenpin/network_proxy_flutter#299]
**描述错误(Describe the bug)**
一台手机热点，另一台设备连接热点，然后开启抓包，另一台设备的http请求抓不到，分享热点的那台设备是可以抓到包的。
**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面
app版本是v1.1.1
**屏幕截图(Screenshots)*

**Comment by wanghongenpin** [comment]
连上热点后使用扫码连接或者外部代理, 或者配置WiFi代理
