### ISSUE TITLE
iOS的证书无法安装

### ISSUE THREAD

**Issue by motaionx** [wanghongenpin/network_proxy_flutter#3]
点击下载根证书，跳转到safai打开提示about:blank
你这个证书的下载地址是在哪？这里有点问题.

**Comment by wanghongenpin** [comment]
> 点击下载根证书，跳转到safai打开提示about:blank 你这个证书的下载地址是在哪？这里有点问题.

确实有点问题，可能是最近更新其他东西印象的，稍等我重新打个包

**Comment by wanghongenpin** [comment]
> 点击下载根证书，跳转到safai打开提示about:blank 你这个证书的下载地址是在哪？这里有点问题.

我刚试了下，默认6666端口号不行，换个其他端口就可以下载证书了，后面默认端口号不会再使用6666了

**Comment by wanghongenpin** [comment]
> 我刚试了下，默认6666端口号不行，换个其他端口就可以下载证书了，后面默认端口号不会再使用6666了

搜了下，好像浏览器会禁用6666端口。

**Comment by wanghongenpin** [comment]
> 点击下载根证书，跳转到safai打开提示about:blank 你这个证书的下载地址是在哪？这里有点问题.

我刚重新打了个包，默认端口号改成9099了，可以下载证书了。

**Comment by motaionx** [comment]
可以了
