### ISSUE TITLE
无法抓取Android局域网请求

### ISSUE THREAD

**Issue by toutoumu** [wanghongenpin/network_proxy_flutter#30]
打开手机端代理工具后, 访问本地局域网的应用均无法使用, 且无法通过代理工具抓包
连接到mac端同样无法抓取局域网的包

**Comment by wanghongenpin** [comment]
手机root了么，访问什么应用呢

**Comment by wanghongenpin** [comment]
我红米root放到系统证书测试微信默认浏览器都可以，安卓10以下的不支持
![42242fb254879314ee0f06abb4173ec1](https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/0ea1de99-e8eb-4e33-b4e8-a6938d7d14eb)

**Comment by wanghongenpin** [comment]
长时间无反馈关闭，请下载最新版，非root能抓的应用比较少
