### ISSUE TITLE
请求列表展示UI交互建议

### ISSUE THREAD

**Issue by devcxm** [wanghongenpin/network_proxy_flutter#302]
首先感谢作者开源这么好的项目，希望并且这个项目一定会越来越好。

现在展示形式是`全部请求`和`域名列表`

说说手机端的建议：
1、首页请求列表只展示一项（不通过tabbar切换），建议默认`域名列表`，然后可以通过按钮切换两种模式；
2、`全部请求`列表可以通过类型快速筛选，如`http`、`https`、`json`、`js`、`图片`等（类似`chrome dev tools`筛选请求）。

第一点手机端`全部请求`请求太多太快了，眼花缭乱不好查找，不像电脑一样屏幕大而且可以用鼠标控制，所以建议默认`域名列表`。
第二点实现起来比较大的工作量，不是很重要，可以暂不考虑。

桌面端如果实现起来不困难的话，键盘的上下键切换请求可以做一下。

**Comment by DuckBurnIncense** [comment]
关于第一点, 个人认为, 现在默认展示 "全部请求" 挺好的, 因为 "全部请求" 是按照时间排序的, 当抓包一个完全未知的程序 / 网页时, 一般都需要按照时间顺序检查请求, 确定请求顺序, 才便于进行接下来的操作. 如果开始就以 "域名列表" 方式查看的话, 不便于理解程序的逻辑. 因此, 我认为在设置里加一个 "首页选择" 的选项比较妥善.

**Comment by devcxm** [comment]
> 关于第一点, 个人认为, 现在默认展示 "全部请求" 挺好的, 因为 "全部请求" 是按照时间排序的, 当抓包一个完全未知的程序 / 网页时, 一般都需要按照时间顺序检查请求, 确定请求顺序, 才便于进行接下来的操作. 如果开始就以 "域名列表" 方式查看的话, 不便于理解程序的逻辑. 因此, 我认为在设置里加一个 "首页选择" 的选项比较妥善.

需求不一样，你说的也有道理。像我抓未知请求时肯定上电脑，在手机上分析效率低。手机端我用`ProxyMan`比较多，它默认是`域名列表`，对刚接触`ProyPin`的人来说，`全部请求`列表可能更合适。

**Comment by huapeng222** [comment]
能不能在列表上显示全部url呢，我这边有的请求是http://a.com/?a=1&b=2，这种请求在列表上就显示一个"/"
