### ISSUE TITLE
外部代理好像不支持用户密码？

### ISSUE THREAD

**Issue by beck-8** [wanghongenpin/network_proxy_flutter#303]
**您的功能请求是否与问题有关？请描述.**
外部代理好像不支持用户密码？

**描述您想要的解决方案**
外部代理支持用户密码

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by wanghongenpin** [comment]
都是自己使用，要啥密码

**Comment by beck-8** [comment]
不好意思，我想先请问一下这个外部代理是二级代理的意思吗？可能我搞错了，当成二级代理了，在哪里可以配置二级代理吗

**Comment by wanghongenpin** [comment]
比如外部代理配置VPN端口，会转发到VPN，这样可以实现外网抓包

**Comment by beck-8** [comment]
嗯对，那我理解的没错。因为我的外部代理在云上，加了密码校验，防止有人滥用

**Comment by wanghongenpin** [comment]
V1.1.3版本已经处理
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.3
