### ISSUE TITLE
导出har文件serverIPAddress格式不正确

### ISSUE THREAD

**Issue by devcxm** [wanghongenpin/network_proxy_flutter#310]
ProxyPin导出的`serverIPAddress`带端口，使用Charles软件打开识别出错，测试了其它软件是不带端口
https://github.com/wanghongenpin/network_proxy_flutter/blob/eef651d28675537a02bc434bfe4e57f8acffcb3b/lib/utils/har.dart#L57

期望
```javascript
"serverIPAddress": "113.31.103.132",
```
实际
```javascript
"serverIPAddress": "113.31.103.132:80",
```

**Comment by wanghongenpin** [comment]
V1.1.3版本已经处理 
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.3

**Comment by devcxm** [comment]
```json
{
                "startedDateTime": "2024-09-18T12:41:50.299173Z",
                "time": 18652,
                "pageref": "ProxyPin",
                "_id": "m17ur6oo",
                "_app": null,
                "request": {
                    "method": "CONNECT",
                    "url": "http://clients3.google.com",
                    "httpVersion": "HTTP/1.1",
                    "cookies": [],
                    "headers": [
                        {
                            "name": "Host",
                            "value": "clients3.google.com"
                        },
                        {
                            "name": "Proxy-Connection",
                            "value": "keep-alive"
                        },
                        {
                            "name": "Connection",
                            "value": "keep-alive"
                        }
                    ],
                    "queryString": [],
                    "postData": {
                        "mimeType": "",
                        "text": ""
                    },
                    "headersSize": -1,
                    "bodySize": 0
                },
                "cache": {},
                "timings": {
                    "send": 0,
                    "wait": 18652,
                    "receive": 0
                },
                "serverIPAddress": null,
                "response": {
                    "status": -4,
                    "statusText": "Connection reset by peer",
                    "httpVersion": "HTTP/1.1",
                    "cookies": [],
                    "headers": [
                        {
                            "name": "Content-Type",
                            "value": "text/plain"
                        },
                        {
                            "name": "Content-Length",
                            "value": "122"
                        }
                    ],
                    "content": {
                        "size": 122,
                        "mimeType": "text/plain",
                        "text": "SocketException: Connection reset by peer (OS Error: Connection reset by peer, errno = 54), address = 0.0.0.0, port = 9099"
                    },
                    "redirectURL": "",
                    "headersSize": -1,
                    "bodySize": 122
                }
            }
```


有个请求`"serverIPAddress": null`，Charles还是会出现异常，当null的时候，替换成空字符串就行了。

**Comment by devcxm** [comment]
顺便提个问题，我的过滤添加了白名单，没加黑名单，非https协议也会显示在列表并被抓取，更合理的逻辑是不是只抓取白名单域名？http协议不应该自动抓取。

**Comment by devcxm** [comment]
还有，HAR `entries` 列表是按`startedDateTime`降序，建议改为升序。

**Comment by devcxm** [comment]
https://github.com/wanghongenpin/network_proxy_flutter/blob/a17200522d04583af42bbed1c9e3a8ed27e1cf71/lib/utils/har.dart#L46

这个`queryString `如果有值，不能为空数组，否则Charles的路径无法显示query

**Comment by wanghongenpin** [comment]
最新包已经处理, 现在entries 已经是升序

**Comment by devcxm** [comment]
> 最新包已经处理, 现在entries 已经是升序

我在iPhone上测试最新main分支，还是降序啊。Charles列表视图的时候会重新排序，折叠视图是降序。打开文件是降序，作者再确认一下。

**Comment by wanghongenpin** [comment]
<img width="583" alt="image" src="https://github.com/user-attachments/assets/b6ab109a-b469-4cee-ba71-135ce7fefd3e">

**Comment by devcxm** [comment]
> <img alt="image" width="583" src="https://private-user-images.githubusercontent.com/24794200/369734433-b6ab109a-b469-4cee-ba71-135ce7fefd3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDc3NTcsIm5iZiI6MTcyNzE0NzQ1NywicGF0aCI6Ii8yNDc5NDIwMC8zNjk3MzQ0MzMtYjZhYjEwOWEtYjQ2OS00Y2VlLWJhNzEtMTM1Y2U3ZmVmZDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDAzMTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiOTdlM2RmYzI5YzAxNDU2MDliNjhlYmM4NjQ2Yzk4N2QwZjhlZDhjZDdmOWJkMDEyM2FlZDhjZjJhNWUzNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xWR_jft1BqBIFBBLZMyhMvoul7qz-Pkjh6Xnjmj8VVQ">

奇怪，我下载app store最新版本也是降序。跟这个issue无关先关闭了。
