### ISSUE TITLE
[Windows 7] v1.1.2和之后版本无法启动

### ISSUE THREAD

**Issue by z7572** [wanghongenpin/network_proxy_flutter#312]
![截图](https://github.com/user-attachments/assets/798981f4-32d6-4595-9d96-ca7cfce66ded)
系统版本win7 64位
经测试在1.1.1及以前的版本可以正常运行，1.1.2版本以及之后就会这样

**Comment by wanghongenpin** [comment]
[ProxyPin-Windows7_x64.zip](https://github.com/user-attachments/files/17085498/ProxyPin-Windows7_x64.zip)

**Comment by wanghongenpin** [comment]
> [ProxyPin-Windows7_x64.zip](https://github.com/user-attachments/files/17085498/ProxyPin-Windows7_x64.zip)

试下这个包可以不, flutter3.19.0之后不支持windows7了, 这个是用旧版本打得包

**Comment by z7572** [comment]
> > [ProxyPin-Windows7_x64.zip](https://github.com/user-attachments/files/17085498/ProxyPin-Windows7_x64.zip)
> 
> 试下这个包可以不, flutter3.19.0之后不支持windows7了, 这个是用旧版本打得包

可以运行了
