### ISSUE TITLE
[Windows]圖標全都變成方框

### ISSUE THREAD

**Issue by KCKCC** [wanghongenpin/network_proxy_flutter#313]
**描述错误(Describe the bug)**
從release頁面下載的
**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面
一打開就是這樣
嘗試安裝 文件裡的cupertino icon.tts 無效
**屏幕截图(Screenshots)*
![Screenshot 2024-09-17 114531](https://github.com/user-attachments/assets/e77eb8b0-ea87-4fb2-89ff-1ebb0e9a9b4b)

**Comment by KCKCC** [comment]
補充 material 的也安裝了 還是沒有...
win11系統

**Comment by wanghongenpin** [comment]
啥都不用安装啊, 我这边没有复现, 你之前版本可以得吗

**Comment by KCKCC** [comment]
1.1.3 1.1.2 都是這個狀況，以前寫flutter的經驗是缺字體會暫時顯示方框，所以找了下載文件夾裡面的字體檔安裝看看。
不過也沒看到包裡有圖檔

**Comment by wanghongenpin** [comment]
试下这个包呢
[ProxyPin-Windows7_x64.zip](https://github.com/wanghongenpin/network_proxy_flutter/releases/download/V1.1.3/ProxyPin-Windows7_x64.zip)
