### ISSUE TITLE
希望优化请求重写操作流程

### ISSUE THREAD

**Issue by lovefan-fan** [wanghongenpin/network_proxy_flutter#314]
**您的功能请求是否与问题有关？请描述.**
对问题所在的清晰简洁的描述[...]

现在的请求重新要点击设置——点击请求重新——点击添加——在输入url

**描述您想要的解决方案**
对你想要发生的事情进行清晰简洁的描述.

希望优化为在需要重写的请求上右键直接可以选择重写，并且自动填入url（如果请求有响应，也希望在替换响应中带入原有的响应）

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

无

**Comment by wanghongenpin** [comment]
点击重写icon
<img width="647" alt="image" src="https://github.com/user-attachments/assets/69c50153-3e88-46a8-917a-bd57352115d3">

**Comment by lovefan-fan** [comment]
> 点击重写icon <img alt="image" width="647" src="https://private-user-images.githubusercontent.com/24794200/368394713-69c50153-3e88-46a8-917a-bd57352115d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MjUxMTQsIm5iZiI6MTcyNjYyNDgxNCwicGF0aCI6Ii8yNDc5NDIwMC8zNjgzOTQ3MTMtNjljNTAxNTMtM2U4OC00NmE4LTkxN2EtYmQ1NzM1MjExNWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDAyMDAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZTA2NWMwY2UzNzFkMjg3ZTQ5NGE1YTIxODQ1MTI3NDE2NGQ5YzM0MDQyZjg0NjlhNDZjOTdmY2FkZjFjODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K_smxcrVVmYcMCFGwJILFdOh3QquOFPVYEPQg6pIgEc">

嗷嗷，原来如此
