### ISSUE TITLE
建议增加重写规则导出加密功能

### ISSUE THREAD

**Issue by es3344520** [wanghongenpin/network_proxy_flutter#318]
如题：  这个功能在分享重写的时候非常重要， 可以避免重写规则内容被别人看到。
 
比如想分享某一个重写规则给别人用， 导出的时候自动加密， 这样导出的文件，无法通过文本编辑查看明文重写内容， 而是加密之后的文本。  然后别人可以正常使用，  但是不能编辑这个重写和查看规则内容。    

这样可以有效保护原作者的成果

**Comment by wanghongenpin** [comment]
重复提交 #133
