### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by neauxty** [wanghongenpin/network_proxy_flutter#32]
个人建议：①可以加一个保留抓包日志的功能，②快捷复制请求头这些

**Comment by wanghongenpin** [comment]
一键复制所有请求头吗，现在右键可以快速复制单个header value

**Comment by wanghongenpin** [comment]
1.0.3Beta新增历史记录功能
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/1.0.3-Beta
