### ISSUE TITLE
能不能支持纯血鸿蒙的抓包啊

### ISSUE THREAD

**Issue by myangelct1984** [wanghongenpin/network_proxy_flutter#320]
**您的功能请求是否与问题有关？请描述.**
对问题所在的清晰简洁的描述[...]

**描述您想要的解决方案**
对你想要发生的事情进行清晰简洁的描述.

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by wanghongenpin** [comment]
暂不考虑支持，可以使用Wi-Fi代理方式抓包

**Comment by wanghongenpin** [comment]
先用wifi配置代理方式吧, 后面鸿蒙用户多了再说

**Comment by Lil-Lil-git** [comment]
> 估计不可能吧。
> 纯血鸿蒙比ios还封闭，完全没有packagemanager和应用包安装程序，完全禁止了第三方市场应用安装(ios至少有个testflight或者爱思助手，华为是直接一棒子打死)，即使做出了鸿蒙版hap安装包也安装不了啊。

hap包可以侧载的呀，我手机上有很多个人做的hap包自己装的
