### ISSUE TITLE
Linux的UI界面是否可以用WEB来呈现

### ISSUE THREAD

**Issue by dream10201** [wanghongenpin/network_proxy_flutter#321]
**您的功能请求是否与问题有关？请描述.**
对问题所在的清晰简洁的描述[...]
Linux的UI界面是否可以用WEB来呈现，类似于[mitmproxy](https://github.com/mitmproxy/mitmproxy)
**描述您想要的解决方案**
对你想要发生的事情进行清晰简洁的描述.

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by wanghongenpin** [comment]
不太清楚用web页面展示好处是什么

**Comment by dream10201** [comment]
无头服务器，长时间运行。比如我在我的nas上跑，电视设置代理，nas写脚本去广告等等

**Comment by devcxm** [comment]
> 无头服务器，长时间运行。比如我在我的nas上跑，电视设置代理，nas写脚本去广告等等

https://github.com/mitmproxy/mitmproxy 这个项目更适合你
