### ISSUE TITLE
可不可以把请求和响应分开啊，因为有的时候只需要复制的是请求响应没有用

### ISSUE THREAD

**Issue by 01345zz** [wanghongenpin/network_proxy_flutter#326]
**您的功能请求是否与问题有关？请描述.**
对问题所在的清晰简洁的描述[...]

**描述您想要的解决方案**
对你想要发生的事情进行清晰简洁的描述.

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by wanghongenpin** [comment]
复制curl格式
