### ISSUE TITLE
大师傅你好，我觉得您写的这个代理工具是全网最好的，我能给一个小建议吗，关于黑白名单

### ISSUE THREAD

**Issue by soshunte** [wanghongenpin/network_proxy_flutter#328]
**您的功能请求是否与问题有关？请描述.**
对问题所在的清晰简洁的描述[...]
黑名单，比如规则是*.xx.com 是否考虑变换个格式比如*.xx.*看起来更合理，因为干扰的流量实在太野了，太多点都点不完
**描述您想要的解决方案**
对你想要发生的事情进行清晰简洁的描述.

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by wanghongenpin** [comment]
有没有一种可能现在就支持

**Comment by soshunte** [comment]
比如哈 是添加到黑名单 .a.com 那么 *.a.top或者是 *.a.cn  也会被黑名单吗。还是说s什么格式啊 大师傅

**Comment by wanghongenpin** [comment]
> 比如哈 是添加到黑名单 .a.com 那么 *.a.top或者是 *.a.cn 也会被黑名单吗。还是说s什么格式啊 大师傅

不会拦截, 就是正则,和其他软件差不多, 你要不这三个都配置,  要不配置成 *.a.*

**Comment by wanghongenpin** [comment]
小师傅, 你还有问题嘛

**Comment by wanghongenpin** [comment]
对
