### ISSUE TITLE
功能建议：批量导出

### ISSUE THREAD

**Issue by uixsj** [wanghongenpin/network_proxy_flutter#33]
很不错的软件，目前在windows用。

希望增加一键导出所选请求的Response Body，因为请求多，一个一个导出太麻烦了。

**Comment by levylll** [comment]
超级需要这个功能！

**Comment by QAQQL** [comment]
个人建议增加历史 的 克隆,修改功能,尝试过删除历史里的数据,发现该操作是不会保存下来的,重新打开历史还会出现
这么说可能不明显
就是需求是,抓下来的包,可能需要经过删除多余的数据再导出到电脑上,比如删除umeng系列的域名,又怕删错了,想先拷贝一份,再做修改,而且希望一边删,他能一边保存(或者是不保存,但删完后能导出当前整理后的数据)

**Comment by wanghongenpin** [comment]
这个现在历史数据删除某个请求确实不会持久化，等后面有时间了会做

> 个人建议增加历史 的 克隆,修改功能,尝试过删除历史里的数据,发现该操作是不会保存下来的,重新打开历史还会出现 这么说可能不明显 就是需求是,抓下来的包,可能需要经过删除多余的数据再导出到电脑上,比如删除umeng系列的域名,又怕删错了,想先拷贝一份,再做修改,而且希望一边删,他能一边保存(或者是不保存,但删完后能导出当前整理后的数据)

**Comment by QAQQL** [comment]
感谢

**Comment by wanghongenpin** [comment]
现在已经历史记录请求删除已经可以持久化了，但是一个个删除感觉有点麻烦，后续提供过滤或者批量删除操作

> 个人建议增加历史 的 克隆,修改功能,尝试过删除历史里的数据,发现该操作是不会保存下来的,重新打开历史还会出现 这么说可能不明显 就是需求是,抓下来的包,可能需要经过删除多余的数据再导出到电脑上,比如删除umeng系列的域名,又怕删错了,想先拷贝一份,再做修改,而且希望一边删,他能一边保存(或者是不保存,但删完后能导出当前整理后的数据)

**Comment by QAQQL** [comment]
感谢

**Comment by wanghongenpin** [comment]
最新版删除两边已同步
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.0.8-Beta

> 感谢,如果能把这个功能也优化到抓包界面就好了 我尝试在抓包过程中根据域名删除,切换tab后发现并没有用

**Comment by wanghongenpin** [comment]
V1.0.8-Beta新增当前视图导出，可以搜索过滤+删除操作导出数据，后续增加多选操作

https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.0.8-Beta
