### ISSUE TITLE
应用白名单希望可以加一个搜索应用，这样可以减少慢慢一个个找指定应用的时间，从而更便捷。

### ISSUE THREAD

**Issue by zhouwenjin023014** [wanghongenpin/network_proxy_flutter#333]
**您的功能请求是否与问题有关？请描述.**
对问题所在的清晰简洁的描述[...]

**描述您想要的解决方案**
对你想要发生的事情进行清晰简洁的描述.

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by wanghongenpin** [comment]
有没有可能现在已经支持了

**Comment by wanghongenpin** [comment]
功能已经存在
