### ISSUE TITLE
Windows客户端内存占用问题

### ISSUE THREAD

**Issue by 10076** [wanghongenpin/network_proxy_flutter#334]
**您的功能请求是否与问题有关？请描述.**
Windows客户端随着程序抓包的数量增加，内存占用也会不停的增加。需要不定时点击清空抓包记录。而且当占用内存达到一定程度时(在我的电脑上超过3G之后)再去点击小扫把清理就会导致应用卡死（可能根据电脑配置不同导致卡死的内存上限不同）。只能通过任务管理器结束运行后重启应用。

**描述您想要的解决方案**
希望能增加自动清理功能。例如抓了超过X条就抛弃之前的记录。或者只保留最近X分钟内的抓包记录。或者配置间隔X分钟能自动清理一次

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by wanghongenpin** [comment]
提供内存自动清理？
<img width="512" alt="image" src="https://github.com/user-attachments/assets/28c36d23-82e7-41d8-a34a-a4170ef269e4">

**Comment by 10076** [comment]
是的。非常感谢

**Comment by wanghongenpin** [comment]
V1.1.5版本已经处理
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.5
