### ISSUE TITLE
增加过滤非接口的请求

### ISSUE THREAD

**Issue by hadis91** [wanghongenpin/network_proxy_flutter#341]
你好，可否增加一个配置项用于过滤图片、js、html等非接口的请求呢？一般抓包的时候都不关注这些信息，所以不想在列表展示这些内容

**Comment by wanghongenpin** [comment]
先用搜索过滤吧
<img width="504" alt="image" src="https://github.com/user-attachments/assets/0fcfe105-c397-416e-a6fc-47d81a54719d">

**Comment by hadis91** [comment]
好的谢谢
