### ISSUE TITLE
[Android] Bug on showing json response body with Cyrillic charsets

### ISSUE THREAD

**Issue by MrIkso** [wanghongenpin/network_proxy_flutter#344]
**Describe the bug**
Bug on showing json response body with Cyrillic charsets. Maybe you not used utf8 encoding for decoding this body(?)

**To Reproduce**
See screenshot or see it [url](https://api.kinorium.com/1.0.0/?method=getMovie&movie_id=10810461&key=29f6172620cbc7d31d8649ffee15dcbe)

**Screenshots**
![Screenshot_20241020_134428](https://github.com/user-attachments/assets/d0dce7fb-fe72-4161-a54c-9d8b5baf8fc6)
![Screenshot_20241020_134758](https://github.com/user-attachments/assets/92df6eec-334a-434b-b398-60b3f856a4a5)

**Comment by wanghongenpin** [comment]
The next version will fix it. Now the character judgment is `utf-8`, not `utf8`

**Comment by wanghongenpin** [comment]
V1.1.5 Version has been processed
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.1.5
