### ISSUE TITLE
[Windows] 关闭开启代理如何使用

### ISSUE THREAD

**Issue by qiuyueovo** [wanghongenpin/network_proxy_flutter#346]
**描述错误(Describe the bug)**
现在的情况是 
我开启代理后，基本上抓不到包。包括但不限于Google浏览器、飞书等应用。
关闭代理后，能抓取到Google浏览器的部分包，但是网页会提示不安全等信息、网页无法正常加载。这或许也和我开启了是否启用https代理有关？
**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面

**屏幕截图(Screenshots)*
![image](https://github.com/user-attachments/assets/e9af6c9f-2913-4070-90c4-db619d95e8c7)

**Comment by qiuyueovo** [comment]
我也安装了根证书到本机了。

**Comment by wanghongenpin** [comment]
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/65bc32d2-6875-411a-b280-362eff10606d">

安装根证书，开启https代理，设置为系统代理，如果开启了其他VPN应用，会有冲突，可以用外部代理方式解决

**Comment by qiuyueovo** [comment]
> <img alt="image" width="1026" src="https://private-user-images.githubusercontent.com/24794200/378248232-65bc32d2-6875-411a-b280-362eff10606d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NzY4MTgsIm5iZiI6MTcyOTQ3NjUxOCwicGF0aCI6Ii8yNDc5NDIwMC8zNzgyNDgyMzItNjViYzMyZDItNjg3NS00MTFhLWIyODAtMzYyZWZmMTA2MDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDAyMDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NDg4OTY1ZjRkMDUyY2YwYjgxZWMwNmIzYWMyY2Y4ZmYyNjVkZTg2MDFkYWY4MDM3MDZmM2FjN2EwZmRiNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.M0R7qFWoL-DMwG5TibfPP1dToiVwvW_xjLZrNNRBqpk">
> 安装根证书，开启https代理，设置为系统代理，如果开启了其他VPN应用，会有冲突，可以用外部代理方式解决

了解。但是我现在能抓取出大部分请求了。但是我在使用的时候还是会有一些不顺畅的位置。
1. 开启代理没办法和抓包同时使用，例如，抓包开启的时候我没办法访问github和一些网站。这个会让我很苦恼。
2. 抓包无法抓取到飞书小程序里面的内容。操作为：关闭代理的情况在开启抓包。无法抓取到飞书小程序内容。我试过了市面上大部分抓包软件，大部分都无法抓取到飞书小程序的内容。部分软件除外。（当然也可能排除我这个小白不太会使用）

**Comment by wanghongenpin** [comment]
外部代理设置vpn端口，就可以访问外网
<img width="432" alt="image" src="https://github.com/user-attachments/assets/c023432e-65f4-4043-b873-1c78fde1cc41">

**Comment by qiuyueovo** [comment]
> 外部代理设置vpn端口，就可以访问外网 <img alt="image" width="432" src="https://private-user-images.githubusercontent.com/24794200/378250970-c023432e-65f4-4043-b873-1c78fde1cc41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0Nzk5MzQsIm5iZiI6MTcyOTQ3OTYzNCwicGF0aCI6Ii8yNDc5NDIwMC8zNzgyNTA5NzAtYzAyMzQzMmUtNjVmNC00MDQzLWI4NzMtMWM3OGZkZTFjYzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDAzMDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOGY2YzQzNTZmODg5YmExYzFkYTMwNmUxMmUwYzJlOTgzMDc1NmM0NzQwYWI3ZjU4MjcxZTlmMDI3MDQ4YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0Jm6XgA7hrJuIIJfIL9D6T902Ed31XfM8Wcj26j9HqI">

是的是的 我现在可以了。感谢。
稍后我在尝试一下我说的另外一个问题。

**Comment by qiuyueovo** [comment]
> > 外部代理设置vpn端口，就可以访问外网 <img alt="image" width="432" src="https://private-user-images.githubusercontent.com/24794200/378250970-c023432e-65f4-4043-b873-1c78fde1cc41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0Nzk5MzQsIm5iZiI6MTcyOTQ3OTYzNCwicGF0aCI6Ii8yNDc5NDIwMC8zNzgyNTA5NzAtYzAyMzQzMmUtNjVmNC00MDQzLWI4NzMtMWM3OGZkZTFjYzQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDAzMDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOGY2YzQzNTZmODg5YmExYzFkYTMwNmUxMmUwYzJlOTgzMDc1NmM0NzQwYWI3ZjU4MjcxZTlmMDI3MDQ4YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0Jm6XgA7hrJuIIJfIL9D6T902Ed31XfM8Wcj26j9HqI">
> 
> 是的是的 我现在可以了。感谢。 稍后我在尝试一下我说的另外一个问题。

第二个问题可能还是没办法。第一个问题已经解决了。
