### ISSUE TITLE
请问是否支持linux？

### ISSUE THREAD

**Issue by Weoworks** [wanghongenpin/network_proxy_flutter#35]

**Comment by wanghongenpin** [comment]
可能得稍微调试下，打包linux得需要linux环境，我现在没linux环境,

**Comment by wanghongenpin** [comment]
打包得需要flutter环境
https://flutter.cn/docs/get-started/install/linux

**Comment by wanghongenpin** [comment]
1.0.2已经打包linux，deb格式


> > 可能得稍微调试下，打包linux得需要linux环境，我现在没linux环境,
> 
> 大佬发一下打包命令，初出茅庐，小的不懂

**Comment by kero990** [comment]
大佬好，我在一台arm uos 设备上尝试编译项目。不过uos的字体设置跟其他常见linux不同。几乎所有flutter的项目中文字体都无法识别，是一堆口口。想问下您本项目如何指定系统字体。uos的默认字体叫做Noto Sans CJK SC
