### ISSUE TITLE
请问下抓包的时候是必须要安装手机版的ProxyPin应用吗？

### ISSUE THREAD

**Issue by onism0106** [wanghongenpin/network_proxy_flutter#38]
直接启动macOS上的抓包，https的抓不到，也安装了证书。但是手机上安装ProxyPin就可以。
能否像Charles那样安装好证书后，手机上不需要安装任何代理应用就能抓包呢？

**Comment by wanghongenpin** [comment]
> 直接启动macOS上的抓包，https的抓不到，也安装了证书。但是手机上安装ProxyPin就可以。 能否像Charles那样安装好证书后，手机上不需要安装任何代理应用就能抓包呢？

现在也不需要安装手机版，wifi配置代理就行
