### ISSUE TITLE
功能建议: 请求重定向

### ISSUE THREAD

**Issue by limoruirui** [wanghongenpin/network_proxy_flutter#41]
有些时候需要改写加载的js 希望能将url重定向到自己的静态资源文件实现 虽然说rewrite也能实现 但是rewrite的话 每一次静态资源文件改动 所有设备都要一起改

**Comment by wanghongenpin** [comment]
1.0.3Beta版已经增加，先做了个简版的，ui界面看着有点别扭，后面优化
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/1.0.3-Beta
