### ISSUE TITLE
关于linux下的默认中文字体

### ISSUE THREAD

**Issue by kero990** [wanghongenpin/network_proxy_flutter#42]
大佬好，我在一台arm uos 设备上尝试编译项目。不过uos的字体设置跟其他常见linux不同。几乎所有flutter的项目中文字体都无法识别，是一堆口口。想问下您本项目如何指定系统字体。uos的默认字体叫做Noto Sans CJK SC。

**Comment by wanghongenpin** [comment]
可以看下flutter指定字体文档
https://flutter.cn/docs/cookbook/design/fonts

**Comment by kero990** [comment]
> 可以看下flutter指定字体文档 https://flutter.cn/docs/cookbook/design/fonts

我这里是个UOS的设备，目前的环境是Flutter 3.14.0-0.2.pre，现在的问题是，我编译的多个flutter都无法显示字体。经测试，直接为themeData赋值fontFamily: 'Noto Sans CJK SC',就可以正确显示，但使用textTheme的fontFamily就是无效的。我不知道为什么。
然而themeData的copyWith并不支持直接使用fontFamily，这导致一旦项目使用了复杂的themeData实现，我浅薄的flutter知识就不会改了，您这个我就不会改。。。。。
我不知道这是不是flutter的bug，还是系统的兼容性。我只想编译几个项目而已。

**Comment by wanghongenpin** [comment]
去Flutter社区提问吧，字体我研究的也不多
> 
> 我这里是个UOS的设备，目前的环境是Flutter 3.14.0-0.2.pre，现在的问题是，我编译的多个flutter都无法显示字体。经测试，直接为themeData赋值fontFamily: 'Noto Sans CJK SC',就可以正确显示，但使用textTheme的fontFamily就是无效的。我不知道为什么。 然而themeData的copyWith并不支持直接使用fontFamily，这导致一旦项目使用了复杂的themeData实现，我浅薄的flutter知识就不会改了，您这个我就不会改。。。。。 我不知道这是不是flutter的bug，还是系统的兼容性。我只想编译几个项目而已。
