### ISSUE TITLE
微信小程序，头条等抓取不到

### ISSUE THREAD

**Issue by dreamlist** [wanghongenpin/network_proxy_flutter#43]

**Comment by wanghongenpin** [comment]
微信小程序抓包是可以的，除了安卓得root，可以说下具体哪个小程序不行，头条软件没试过，可能做了ssl校验

**Comment by over-star** [comment]
windows测试可以

**Comment by dreamlist** [comment]
> Windows测试可以

windows， fiddler也可以，有些小程序做了校检只能移动端访问，手机上抓取不到

**Comment by wanghongenpin** [comment]
具体哪个小程序抓取不到？提示ssl握手错误还是什么
> 
> windows， fiddler也可以，有些小程序做了校检只能移动端访问，手机上抓取不到
