### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by zhangya4548** [wanghongenpin/network_proxy_flutter#46]
能否增加自定义中间件脚本功能

比如可以通过自定义中间件脚本后拦截修改某个请求的参数, 返回值等, 然后这个自定义的脚本可以分享给别人用

**Comment by wanghongenpin** [comment]
准备支持js脚本，onRequest及onResponse

**Comment by wanghongenpin** [comment]
1.0.4Beta支持脚本功能
https://github.com/wanghongenpin/network_proxy_flutter/releases

脚本文档说明：https://github.com/wanghongenpin/network_proxy_flutter/wiki/%E8%84%9A%E6%9C%AC
