### ISSUE TITLE
add a forwarding feature

### ISSUE THREAD

**Issue by adk23333** [wanghongenpin/network_proxy_flutter#49]
具体是指把符合条件的请求的response转发给指定的服务器接口以作它用

**Comment by adk23333** [comment]
#39 
问题应该是[这个](https://github.com/wanghongenpin/network_proxy_flutter/issues/39#issuecomment-1711025079) 手机端有吗，怎么用，没找到😭

**Comment by wanghongenpin** [comment]
手机还没打包，你是安卓还是ios
> #39 问题应该是[这个](https://github.com/wanghongenpin/network_proxy_flutter/issues/39#issuecomment-1711025079) 手机端有吗，怎么用，没找到😭

**Comment by adk23333** [comment]
> 手机还没打包，你是安卓还是ios
> 
> 抱歉，没说清楚，我是安卓的，我希望这个功能应该是可以全自动进行的。不然我只能使用autoxjs来监听app的ui行为来完成一些自动任务了hh

**Comment by wanghongenpin** [comment]
后面会提供脚本，目前先只有重定向，可以自己起个服务，转发到自己服务

**Comment by adk23333** [comment]
> 后面会提供脚本，目前先只有重定向，可以自己起个服务，转发到自己服务

这个app互相之间转发的api文档有吗

**Comment by wanghongenpin** [comment]
1.0.4Beta支持脚本功能，可以自定义转发接口
https://github.com/wanghongenpin/network_proxy_flutter/releases

**Comment by adk23333** [comment]
> 1.0.4Beta支持脚本功能，可以自定义转发接口
> https://github.com/wanghongenpin/network_proxy_flutter/releases

测试了一下，功能没有什么问题。

就是安卓端脚本列表点按会有一些动画残留在ui上的小bug

脚本的log是在哪里查看？pc端吗

**Comment by wanghongenpin** [comment]
现在没法查看log，脚本异常了详情会展示原因，后面持续优化吧
> 
> 脚本的log是在哪里查看？pc端吗
