### ISSUE TITLE
功能建议。

### ISSUE THREAD

**Issue by mymine** [wanghongenpin/network_proxy_flutter#50]
建议增加图片和json文件预览。

**Comment by wanghongenpin** [comment]
现在不能展示图片和json吗？

**Comment by mymine** [comment]
> 现在不能展示图片和json吗？

可以吗？图片是一堆乱码。应该是作为文本预览了。json预览应该是分级格式化的吧

**Comment by wanghongenpin** [comment]
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/0f97d160-c345-48ac-a6f3-470166fa2806)
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/4e1b162c-4794-4601-b5e3-70193c1ac58c)

**Comment by mymine** [comment]
> ![image](https://user-images.githubusercontent.com/24794200/268829807-0f97d160-c345-48ac-a6f3-470166fa2806.png) ![image](https://user-images.githubusercontent.com/24794200/268829863-4e1b162c-4794-4601-b5e3-70193c1ac58c.png)

可以，不过手机版json预览好像只是高亮处理。不能分级折叠

**Comment by wanghongenpin** [comment]
只有响应类型是json才会有json层级格式化

**Comment by mymine** [comment]
> 只有响应类型是json才会有json层级格式化

哦，我以为响应类型和后缀是.json都会有呢
