### ISSUE TITLE
功能建议: 切换应用图标

### ISSUE THREAD

**Issue by amoxuk** [wanghongenpin/network_proxy_flutter#52]
增加类似ish的切换应用图标的功能![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/26641021/28f200fb-419c-4299-ae6a-c58a1ad4d0bf)
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/26641021/2d3aae74-ec1a-418a-b49d-5846be72d335)

**Comment by wanghongenpin** [comment]
和抓包关联不大，先找一些第三方软件修改图标吧
