### ISSUE TITLE
[IOS求助]有人愿意提供企业签名吗

### ISSUE THREAD

**Issue by wanghongenpin** [wanghongenpin/network_proxy_flutter#54]
TF人现在已经满了，每次删除人都会导致TF不能用，需要找苹果技术人员处理都得等一个星期。

如果有企业签名大家安装就方便多了, 并且没有人员名额限制，有什么要求可以私聊我。

或者有什么好的想法欢迎回复

**Comment by hinego** [comment]
应该让用户去国外的应用市场下载。有tf肯定大多数人都想偷懒
