### ISSUE TITLE
[系统] MIUI14-Android 13：美团买菜抓包握手失败

### ISSUE THREAD

**Issue by LeanFly** [wanghongenpin/network_proxy_flutter#55]
美团买菜-我的栏目下，有个天天果园，点击进入后，页面空白无内容，看抓包工具提示握手失败。

手机是 MIUI14 ，Android 13，未root
电脑是win11
proxypin 是 1.0.3

![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/18253047/05f4bb7a-71fd-4bea-8285-636d1a142bcb)

请求内容Request
CONNECT catdot.dianping.com:443 HTTP/1.1
Host: catdot.dianping.com:443
Proxy-Connection: Keep-Alive
User-Agent: Dalvik/2.1.0 (Linux; U; Android 13; 22041211AC Build/TP1A.220624.014)

--------------------------------------------------------

响应内容Response
HTTP/1.1 -2
Content-Type: text/plain
Content-Length: 146

HandshakeException: Handshake error in server (OS Error: 
	SSLV3_ALERT_CERTIFICATE_UNKNOWN(../../third_party/boringssl/src/ssl/tls_record.cc:592))

curl -X CONNECT 'catdot.dianping.com:443' \
  -H 'Host: catdot.dianping.com:443' \
  -H 'Proxy-Connection: Keep-Alive' \
  -H 'User-Agent: Dalvik/2.1.0 (Linux; U; Android 13; 22041211AC Build/TP1A.220624.014)'  \
   --compressed

![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/18253047/b2aebc75-1e49-4c2b-b8cd-df59e035a2ba)

![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/18253047/60481a4a-e805-4dab-aaa8-e11fd3c71c62)

![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/18253047/fee8426d-67fc-4ee5-945e-ae2615750e52)

**Comment by wanghongenpin** [comment]
证书安装问题，证书书安装流程介绍：https://www.bilibili.com/video/BV1Qm4y157Gk/

![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/59dcd43f-024b-4bf1-b4b1-1d0653ae9c1f)

**Comment by wanghongenpin** [comment]
我红米的可以，全部握手失败检查下证书
证书安装流程介绍：https://www.bilibili.com/video/BV1Qm4y157Gk/
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/7e87165d-2d6f-4924-8be3-5818abb99f91)

**Comment by wanghongenpin** [comment]
安卓不root大部分应用都不能抓，安卓系统原因
