### ISSUE TITLE
[windows]未安装证书时windows系统点击停止抓包会无响应

### ISSUE THREAD

**Issue by fr4nkhe** [wanghongenpin/network_proxy_flutter#56]
**描述错误**
未安装证书时windows系统点击停止抓包会无响应，安装证书后变正常了

**To Reproduce**
重现行为的步骤:

**屏幕截图*

**Comment by wanghongenpin** [comment]
我本地测试无法复现，你那边是必现的吗

**Comment by wanghongenpin** [comment]
此bug无法复现，如果其他人也有遇到，可重新打开。
