### ISSUE TITLE
Android,OnePlus8T

### ISSUE THREAD

**Issue by JMing-A** [wanghongenpin/network_proxy_flutter#57]
** 一加8TColorOS13.1,Android13
** 已root,alpha版本面具
** 无法抓包
** 面具安装证书模块重启后系统设置找不到证书,mt管理器证书路径下可以找到证书文件,但系统不识别

**Comment by wanghongenpin** [comment]
你研究下，其实模板没啥代码，就一个证书，我是按照Magisk模块开发文档写的

**Comment by wanghongenpin** [comment]
主要是将系统证书放到 /system/etc/security/cacerts 目录下，你能不能获取到系统目录写入权限，或者尝试面具其他模块
这个模块是将用户证书移动到系统目录，你可以先安装到用户证书，然后安装这个模块，然后重启手机，看下有系统证书没
https://github.com/ys1231/MoveCertificate

**Comment by wanghongenpin** [comment]
长时间无反馈，先关闭了，可以网上搜索下安卓系统证书教程，需要我处理的，欢迎重新打开
