### ISSUE TITLE
[Windows]win7无法启动软件，是否不支持

### ISSUE THREAD

**Issue by by123456by** [wanghongenpin/network_proxy_flutter#58]
**描述错误**

**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面

**屏幕截图*
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/15666692/dcf4a558-5e94-475b-a959-658e6f3b3879)

**Comment by wanghongenpin** [comment]
windows7 支持64位， 32位不支持, 如果是64位，你搜下这个api-ms-win-core-winrt-l1-1-0.dll单独下载安装下
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/2e4b77c6-c488-4f80-94fb-1c5b8ba66c9f)

**Comment by wanghongenpin** [comment]
尽量使用新版本系统
