### ISSUE TITLE
请求头和返回头，支持展开/折叠设置

### ISSUE THREAD

**Issue by Chen-shijie** [wanghongenpin/network_proxy_flutter#59]
现在默认都是展开的，实际上在使用过程中，更多的是关注返回体，头部占用了大片空间，不利于查看，最好支持设置头部默认展开和折叠
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/48749488/f82208a3-f232-4576-805f-e23db55fd6fa)

**Comment by wanghongenpin** [comment]
1.0.7-Beta版本增加 header展开设置，在偏好里设置（左下角icon）

https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/1.0.7-Beta
