### ISSUE TITLE
Win10下暗黑模式主题样式

### ISSUE THREAD

**Issue by jaychoubaby** [wanghongenpin/network_proxy_flutter#6]
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/26641387/d21aa09a-e95d-47ba-8410-646c40f38214)

暗黑模式下紫色几乎看不清，另外称赞一下作者，希望越来越好

**Comment by jaychoubaby** [comment]
另外，response中得返回值 希望可以鼠标双击进行选中，方便复制

**Comment by wanghongenpin** [comment]
这个json展示用的第三方库，flutter第三方库太不完善了，后面我准备在它上面增强，准备做成类似于json.cn那样json面板和操作
> ![image](https://user-images.githubusercontent.com/26641387/256162553-d21aa09a-e95d-47ba-8410-646c40f38214.png)
> 
> 暗黑模式下紫色几乎看不清，另外称赞一下作者，希望越来越好

**Comment by wanghongenpin** [comment]
现在双击value会复制，桌面版没提示，手机版有提示
> 另外，response中得返回值 希望可以鼠标双击进行选中，方便复制

**Comment by wanghongenpin** [comment]
> 老板建个TG群呗
有个微信群，咱们是正经学术群，不需要TG了吧[狗头]
![e8d1f6feabf02313f2bd2dcae7dfc5b](https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/c1c157c1-2b87-4131-bc8f-cdcb572b41f9)

**Comment by wanghongenpin** [comment]
暗黑模式样式 和idea保持一致了，双击或右键value可快速复制
最新版下载地址：https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/0.0.2

<img width="902" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/a9ecdc72-94eb-4f8f-8581-c536a5eb90cf">


> 另外，response中得返回值 希望可以鼠标双击进行选中，方便复制

**Comment by jaychoubaby** [comment]
> 暗黑模式样式 和idea保持一致了，双击或右键value可快速复制 最新版下载地址：https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/0.0.2
> 
> <img alt="image" width="902" src="https://user-images.githubusercontent.com/24794200/256530394-a9ecdc72-94eb-4f8f-8581-c536a5eb90cf.png">
> > 另外，response中得返回值 希望可以鼠标双击进行选中，方便复制

已体验，很nice，谢谢老板
