### ISSUE TITLE
加

### ISSUE THREAD

**Issue by sdfsddsd** [wanghongenpin/network_proxy_flutter#60]
加

**Comment by wanghongenpin** [comment]
生成请求代码是什么意思呢？类似于Postman生成Java一些语言请求代码吗

**Comment by sdfsddsd** [comment]
想了想也无所谓，就是直接生成重发的请求代码，复制粘贴省的撸请求代码了，不过现在你这个转发到电脑上还不行，手机上有数据扫码链接之后有的数据电脑上没有显示

**Comment by sdfsddsd** [comment]
> 生成请求代码是什么意思呢？类似于Postman生成Java一些语言请求代码吗

哦  更新了之后数据可以显示了
