### ISSUE TITLE
功能建议-增加上级代理

### ISSUE THREAD

**Issue by Amaake3321** [wanghongenpin/network_proxy_flutter#61]
**单纯抓到App的包没啥用，还要进行一系列改包测试，但是app提供的改包功能有限，

所以最好转发流量到BurpSuite之类的软件上来进行进一步的处理

安全测试迫切需要**

**Comment by wanghongenpin** [comment]
已经有外部代理设置了

**Comment by Amaake3321** [comment]
> 已经有外部代理设置了

手机app还没有，只有连接终端的功能，，这个外部代理能够详细介绍一下嘛

**Comment by wanghongenpin** [comment]
手机连接电脑就是局域网转发，只要网络能通 就没问题，可以访问电脑ip+端口号 看下网络通不

> 手机app还没有，只有连接终端的功能，手机端能加一下嘛（迫切需要） 而且我试了一下这个连接终端的功能，同个c段没法连接（比如电脑192.168.1.1，手机192.168.2.1）网络通但是无法连接

**Comment by wanghongenpin** [comment]
我觉得你可以用电脑版，手机配置wifi代理，电脑版配置外部代理转发

**Comment by kingz40o** [comment]
+1 app增加外部代理设置

**Comment by wanghongenpin** [comment]
手机端已增加外部代理，ios TF已经更新，安卓重新下载最新版
<img src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/6bbb27f5-8416-4943-a587-743417680d0c" width = "300" height = "500" alt="图片名称" align=center />
