### ISSUE TITLE
[Android]游戏好像没法抓包

### ISSUE THREAD

**Issue by Dystnine** [wanghongenpin/network_proxy_flutter#64]
**描述错误**
打开抓包后游戏提示无网络，抓包软件也报错，不打开正常
**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面
1.下载游戏https://apkpure.com/jp/%E9%AD%94%E6%B3%95%E4%BD%BF%E3%81%84%E3%81%AE%E7%B4%84%E6%9D%9F/com.colyinc.mahoyaku
2.使用zygisk安装证书
3.打开抓包软件
4.打开游戏
**屏幕截图*
![图片](https://github.com/wanghongenpin/network_proxy_flutter/assets/123282693/5ffa8620-dbdc-449d-b3cc-ce04ff239dbd)
![图片](https://github.com/wanghongenpin/network_proxy_flutter/assets/123282693/a984795e-8eec-4574-8f2e-9b7a5317114f)
![图片](https://github.com/wanghongenpin/network_proxy_flutter/assets/123282693/67405236-dbb7-486a-825f-3d3f2b7c62bc)

**Comment by wanghongenpin** [comment]
你这个软件我安装了打不开，没开代理

**Comment by Dystnine** [comment]
> 你这个软件我安装了打不开，没开代理

软件有检查root和虚拟机，虚拟机只有蓝蝶能开，手机需要shamiko

**Comment by wanghongenpin** [comment]
测试太麻烦，我试了安装不了证书，这个模拟器root了导入不了系统证书，如果其他抓包软件可以用，用其他抓包软件吧

**Comment by Dystnine** [comment]
> 测试太麻烦，我试了安装不了证书，这个模拟器root了导入不了系统证书，如果其他抓包软件可以用，用其他抓包软件吧

可以安装的，蓝蝶先开root，把证书用Root Certificate Manager安装上，再关闭root

**Comment by wanghongenpin** [comment]
测试太麻烦了，你试下其他抓包软件可以不，如果不行 那就是游戏有校验

**Comment by Rin-Wood** [comment]
> 测试太麻烦了，你试下其他抓包软件可以不，如果不行 那就是游戏有校验

https://d.qoo-apk.com/19054/apk/com.ngelgames.tog-569-186465068-1701741004.apk

游戏抓不到http是正常的吗？我用小黄鸟能看到这个url-kr-tog-srv2.ngelgames.com:20001
![Screenshot_20231209-202426](https://github.com/wanghongenpin/network_proxy_flutter/assets/153263099/988a4b7e-0f7a-41a3-8e1d-8176adbd983d)

**Comment by wanghongenpin** [comment]
> > 游戏无法启用，还有我用小黄鸟也看不到请求
> 
> https://d.qoo-apk.com/19054/apk/com.ngelgames.tog-569-186465068-1701741004.apk

**Comment by wanghongenpin** [comment]
请尝试用最新版包重试下，调试条件非常麻烦暂时不会处理
