### ISSUE TITLE
开启抓取后访问网页显示隐私错误

### ISSUE THREAD

**Issue by tiam-bloom** [wanghongenpin/network_proxy_flutter#66]
**描述错误**
开启抓取后访问网页显示隐私错误
**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面
是我设置不对吗,
**屏幕截图*
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/73210704/ccd50f78-d635-49b1-9aec-15e456b6c089)

**Comment by wanghongenpin** [comment]
证书问题，是否安装正确，安装重新打开下软件试下呢。

**Comment by wanghongenpin** [comment]
长时间未反馈先关闭了，有问题可以重新打开，桌面端提示这个大概率是证书安装不正确，可以按照教程安装下证书。mac证书一定要放到钥匙串系统证书分类下
