### ISSUE TITLE
添加所抓抓文件大小

### ISSUE THREAD

**Issue by yjstlu** [wanghongenpin/network_proxy_flutter#67]
**您的功能请求是否与问题有关？请描述.**
对问题所在的清晰简洁的描述[...]

**描述您想要的解决方案**
对你想要发生的事情进行清晰简洁的描述.

**附加上下文**

**Comment by wanghongenpin** [comment]
响应报文大小吗？

**Comment by wanghongenpin** [comment]
如果是响应体大小，已经有Content-Type了，还是说整个响应报文大小？

**Comment by yjstlu** [comment]
整个响应报文的大小在下图界面添加显示



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月27日(周一) 下午3:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wanghongenpin/network_proxy_flutter] 添加所抓抓文件大小 (Issue #67)




 
如果是响应体大小，已经有Content-Type了，还是说整个响应报文大小？

**Comment by M17764017422** [comment]
> 1.0.5增加报文大小
> https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/1.0.5 
> <img width="266" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/7c834d91-b964-4812-acfa-dbe948d24c60">
> <img width="600" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/ec239f03-0ed6-4ba9-9f99-5f688926aa05">
> 

全部请求列表显示了两个报文大小，都是发送报文的大小，数值都是一样的，和实际的收发大小不一致。@wanghongenpin

**Comment by wanghongenpin** [comment]
多谢反馈 近期会打个新包
> 
> 全部请求列表显示了两个报文大小，都是发送报文的大小，数值都是3.2kb，和实际的收发大小3.2kb/1.74kb不一致。@wanghongenpin

**Comment by wanghongenpin** [comment]
TF1.0.6最新版本已经修复
