### ISSUE TITLE
当电脑有多个IP的时候无法指定IP，导致扫描二维码说不在同一网络

### ISSUE THREAD

**Issue by farmer-simon** [wanghongenpin/network_proxy_flutter#7]

**Comment by wanghongenpin** [comment]
你是用的WiFi还是网线呢，我测试mac首个可用的名字是en0，windows优先取 WiFi的IP，这种多个IP我想的是提供下拉框选择

![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/393756d5-b4d9-47cc-835d-c74e5df169a6)

**Comment by wanghongenpin** [comment]
扫码链接时多ip增加下拉框选择，你看能解决你的问题不，最新版的包已经更新
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/0.0.2
<img width="468" alt="17fdab0149a96b56637030ff8cccee0" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/4e5dd45d-c615-496a-ae71-afdc4dd7dd48">

**Comment by mayjack0312** [comment]
同样遇到这问题了，WiFi连接的，显示连接失败，请检查是否在同一局域网

**Comment by wanghongenpin** [comment]
IP显示是否正确，windows如果开启了防火墙，首次打开网络需要允许访问，ios扫码连接电脑，本地网络权限需要打开

![IMG_0559](https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/841b3ccc-1290-4fa6-bfc2-571545831767)

> 同样遇到这问题了，WiFi连接的，显示连接失败，请检查是否在同一局域网

**Comment by wanghongenpin** [comment]
是否是多IP导致的，vmware、docket这些虚拟机会创建虚拟网卡，多个IP默认显示的可能不正确，最新版多个IP可以下拉框选择，
ip应该获取不会错，是语言提供的API。

> 显示得ip跟我本机得ip不一样，本机ip是192.168.68.25，软件却显示在192.168.68.44.使用显示得ipv6也无法链接

**Comment by wanghongenpin** [comment]
手机用浏览器访问电脑ip+端口号，会响应pong，没响应就是手机和电脑网络没通
大概会影响的问题
1. 多个虚拟网卡ip显示错了，最新版本改成下拉框了，选择正确ip即可
2. 防火墙导致的，如果开启了防火墙，windows首次打开软件就有允许网络访问弹框，需要允许下。
3. ios扫码连接电脑需要开启本地网络权限。

如果其他抓包软件(Charles等)手机可以访问电脑，把本抓包软件改成对应端口，应该也是可以访问的。

**Comment by mayjack0312** [comment]
> IP显示是否正确，windows如果开启了防火墙，首次打开网络需要允许访问，ios扫码连接电脑，本地网络权限需要打开
> 
> ![IMG_0559](https://user-images.githubusercontent.com/24794200/256231649-841b3ccc-1290-4fa6-bfc2-571545831767.jpg)
> 
> > 同样遇到这问题了，WiFi连接的，显示连接失败，请检查是否在同一局域网

App权限全给了，我本地有虚拟机，Windows防火墙也全开了，电脑使用的是v0.02的新版本，下拉选的是我电脑的ip地址，我又和手机对了一下，IP段都是一样的，但还是连不上，不知道是什么情况
电脑ip是：192.168.11.198
手机ip是：192.168.11.187

**Comment by Lzsh1** [comment]
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/74004927/6233daf0-0749-4656-8052-be9dc6878fb1)

**Comment by mayjack0312** [comment]
![c5cf319207ba8e808378d4a16956f06](https://github.com/wanghongenpin/network_proxy_flutter/assets/102800660/6aeb6676-f78c-4fde-a287-624a5766788f)
![c360f5a646aaa14c9bcc0ca7f773bcd](https://github.com/wanghongenpin/network_proxy_flutter/assets/102800660/8f4b38b6-2eba-4a7c-84a4-0ece85c0ac56)
ping的通，但就是显示不出来，怀疑是哪里设置不对劲，两个设备的ip段还是没对上

**Comment by wanghongenpin** [comment]
> Referenc

我好像知道是哪里问题了，多ip扫码连接确实有问题，稍等我打个新包。

**Comment by wanghongenpin** [comment]
麻烦再下载下最新的版本呢，我感觉应该好了🐶，我这没有多ip设备没法测。。

> ping的通，但就是显示不出来，怀疑是哪里设置不对劲，两个设备的ip段还是没对上 安卓证书那那个ip段是不是固定的，我觉得有可能是那的问题

**Comment by Lzsh1** [comment]
我得还是显示链接失败，不在同一局域网

**Comment by mayjack0312** [comment]
> 麻烦再下载下最新的版本呢，我感觉应该好了🐶，我这没有多ip设备没法测。。
> 
> > ping的通，但就是显示不出来，怀疑是哪里设置不对劲，两个设备的ip段还是没对上 安卓证书那那个ip段是不是固定的，我觉得有可能是那的问题

可以了可以了，这下能用了

**Comment by wanghongenpin** [comment]
> 我得还是显示链接失败，不在同一局域网

你这个是ip显示的不对，和上面问题可能还不一样，你用浏览器访问下，看实际哪个ip能通

**Comment by mayjack0312** [comment]
> 我得还是显示链接失败，不在同一局域网

powershell跑个ipconfig，然后去手机设置里看ip地址是啥，ip段是不是一个
