### ISSUE TITLE
【功能建议】一些期望的操作逻辑的优化

### ISSUE THREAD

**Issue by WYXHY-Cimolestes** [wanghongenpin/network_proxy_flutter#72]
**您的功能请求是否与问题有关？请描述.**
1.想要调整一下请求重写的逻辑，就是说能不能在那个列表栏直接长按就能出现这个选项，可且和编辑请求重发一样，自动把一些信息填入呢？
2.还有请求重写，和编辑重发他那一个body能不能加一个本地文件上传呀？因为有些文件太大，复制不了
3.还有我觉得原来小黄鸟的规则替换其实还是蛮有用，虽然脚本支持，但是也没必要每次都要写代码呀，而且原来的规则替换是支持历史规则导入的，不过如果之后重写能够实现上面所说的，可以在列表栏长按得到，并且可以自动导入一些数据填充的话，就像小黄鸟那个界面差不多的话，直接用脚本其实也还是能接受的，并且如果实现了这个特性，用脚本甚至比规则替换更好，但是现在请求重写和使用脚本的功能，我觉得太过于分裂了，就是我认为整套逻辑，他应该是合成一个的，就是能够共同协作的，但是现在是两个按钮，两个界面很分裂，
上面所有指的都是安卓端

总结就是三点,1,优化一下请求，重写脚本功能的操作逻辑:在列表界面长按可以出现重写选项，
2,且能够自动导入该条文求的请关数据，并且在同一页面支持脚本和重写功能合为一体
3,如果可能的话，能加规则替换最好
**描述您想要的解决方案**
其实可以效仿一下Httpcanary的做法呀，整套操作逻辑，我觉得是比较舒服的，而且这个相比于原来那个还多了一个脚本支持，如果在操作逻辑上能够更加的舒适一点，我觉得是个相当不错体验
**附加上下文**
HttpCanary_3.3.6.apk
没别的意思，就是觉得这个的操作逻辑比较顺畅，没有比较或者贬低的意思
http://cloud.ananas.chaoxing.com/view/fileview?objectid=ca857f4ab217abb72baa566b92dcfa23

**Comment by WYXHY-Cimolestes** [comment]
虽然小黄鸟都是过去式了，但是我觉得这一套逻辑下来是比较完整，而且符合用户习惯的

**Comment by WYXHY-Cimolestes** [comment]
那个重写的逻辑，我懂了，直接点，然后就可以，我的问题，我的问题，但是能不能把请求中西合那个脚本融合一下，就是提供两个选项？上面部分是正常的，重写下面部分是使用脚本，然后把脚本那一个界面给他加进来，然后我还是觉得如果单独的重写消息体的话，建议还是加一个规则替换，和本地文件上传

**Comment by WYXHY-Cimolestes** [comment]
不过整个重写功能确确实实还需要优化一下非脚本状态下的重写，普通状态下的重写好像可改的东西并不多，主要是在改响应体

**Comment by wanghongenpin** [comment]
后面会加上规则替换

**Comment by M17764017422** [comment]
> 后面会加上规则替换

能不能为URL地址参数，提供一个K:V表单化地址编辑器，点击k可以快速暂停/启用参数，点击v弹出编辑框，可以修改删除参数。保存后自动合并到地址栏，方便快速发送请求，特别是get方法参数特别长，调试参数功能，经常需要删除/恢复很麻烦。@wanghongenpin

**Comment by wanghongenpin** [comment]
1.0.6的修改请求能满足需求吗，修改请求参数都是单独的配置，有单独启用开关

> 能不能为URL地址参数，提供一个K:V表单化地址编辑器，点击k可以快速暂停/启用参数，点击v弹出编辑框，可以修改删除参数。保存后自动合并到地址栏，方便快速发送请求，特别是get方法参数特别长，调试参数功能，经常需要删除/恢复很麻烦。@wanghongenpin

**Comment by M17764017422** [comment]
> 1.0.6的修改请求能满足需求吗，修改请求参数都是单独的配置，有单独启用开关
> 
这样就可以了，能基本满足需求。
我就是基于现有功能提的改进意见，主要是一些地址参数实在太长了，放在一个编辑框里实在不方便

**Comment by M17764017422** [comment]
最好还能快速复制单项参数，比如：&K=v

**Comment by M17764017422** [comment]
> 1.0.6的修改请求能满足需求吗，修改请求参数都是单独的配置，有单独启用开关
> 
> > 能不能为URL地址参数，提供一个K:V表单化地址编辑器，点击k可以快速暂停/启用参数，点击v弹出编辑框，可以修改删除参数。保存后自动合并到地址栏，方便快速发送请求，特别是get方法参数特别长，调试参数功能，经常需要删除/恢复很麻烦。@wanghongenpin
> 
仔细研究了一下，发现我想说的问题其实在编辑重放
![IMG_20231220_222030.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/31874069/7b5d4d97-663d-4215-bb30-dbea72615be8)

![Screenshot_2023-12-20-22-02-42-542-edit_com.network.proxy.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/31874069/ea2566a1-b5a3-4032-bf23-821db44cc730)
抱歉了，没看清楚位置就发了，还是希望下一版能实现@wanghongenpin

**Comment by M17764017422** [comment]
表单化地址编辑器，还是望跟进一下，地址实在太长了😂

**Comment by wanghongenpin** [comment]
1.0.7版本做
> 表单化地址编辑器，还是望跟进一下，地址实在太长了😂

**Comment by M17764017422** [comment]
非常好。我的问题已经解决，可以优化的地方，在修改或删除对话框增加一个复制按钮，将参数复制到剪贴板。

**Comment by wanghongenpin** [comment]
请求重写已支持正则和选择文件，此贴关闭
