### ISSUE TITLE
兼容android模拟器，目前逍遥安卓模拟器上没有抓到包

### ISSUE THREAD

**Issue by kibozh** [wanghongenpin/network_proxy_flutter#74]
https已开启
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/12003972/3173885c-43a3-4621-9548-6eb4583a8e7b)

证书已安装
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/12003972/e1113abd-87b7-4de2-b5f9-5b009dea2b1c)

首页抓包已开启，单一个包都没抓到
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/12003972/9d40a5ff-7787-4d0d-b1bb-e9b2f7dce024)

**Comment by wanghongenpin** [comment]
安卓模拟器是不是10以下的，月底安卓会打个包，解决抓flutter请求和支持安卓10以下版本

**Comment by wanghongenpin** [comment]
这个模拟器我安装完没网，我用mumu模拟器可以抓包，mumu模拟器安卓是12

**Comment by wanghongenpin** [comment]
1.0.5Beta安卓支持了，我自己测可以抓包
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/1.0.5-Beta

<img width="808" alt="8104c68e33cccf089e3174163c09eb5" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/86fffda0-dec2-41ef-aa5a-50564b49ee04">
