### ISSUE TITLE
重写可否选择本地文件

### ISSUE THREAD

**Issue by Wenmoux** [wanghongenpin/network_proxy_flutter#77]
有的请求/响应体太大了 能否添加选择本地文件功能 (快3M 卡死了 (｡•ˇ‸ˇ•｡))

**Comment by wanghongenpin** [comment]
1.0.7-Beta版 重写支持选择本地文件
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/1.0.7-Beta
