### ISSUE TITLE
安卓14模块没法用

### ISSUE THREAD

**Issue by leosj** [wanghongenpin/network_proxy_flutter#78]
系统证书模块

**Comment by wanghongenpin** [comment]
你试下这个包可以不，我手上没有安卓14的手机
[ProxyPinCA.zip](https://github.com/wanghongenpin/network_proxy_flutter/files/13446797/ProxyPinCA.zip)

**Comment by leosj** [comment]
@wanghongenpin 我在电报上联系过你了，改别的代码可以用了

**Comment by wanghongenpin** [comment]
好的

**Comment by mrdong916** [comment]
> @wanghongenpin 我在电报上联系过你了，改别的代码可以用了

老哥 可否提供下

**Comment by mymine** [comment]
> @wanghongenpin 我在电报上联系过你了，改别的代码可以用了

官方面具无效。德尔塔版面具可以用。
