### ISSUE TITLE
除了微信其他App支持无root抓包吗

### ISSUE THREAD

**Issue by mayjack0312** [wanghongenpin/network_proxy_flutter#8]

**Comment by wanghongenpin** [comment]
这个得看app配置，uc chrome浏览器、京东app都可以抓包，安卓我测的比较少。话说你现在扫码可以连接了么

**Comment by mayjack0312** [comment]
> 这个得看app配置，uc chrome浏览器、京东app都可以抓包，安卓我测的比较少。话说你现在扫码可以连接了么

OK了，改好了，可以正常连接了 (๑•̀ㅂ•́)و✧

**Comment by wanghongenpin** [comment]
没问题就关闭了，你如果是刚才下载那个版本发现json格式化展示异常，下载下最新的就可以，我刚才在调试json展示，有一段时间上传的包有问题。

> OK了，改好了，可以正常连接了 (๑•̀ㅂ•́)و✧
