### ISSUE TITLE
[Android]1.0.5版本无法抓Flutter包，已经安装httpsca证书

### ISSUE THREAD

**Issue by haifengzuishuai** [wanghongenpin/network_proxy_flutter#80]
**描述错误**

**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面

**屏幕截图*

**Comment by wanghongenpin** [comment]
什么应用，提示什么，证书安装正确了吗

**Comment by haifengzuishuai** [comment]
证书安装正确，其他应用能抓到https的包和对应的response，应用是自己公司的应用，没有上市场，如果要测试我可以加大佬

**Comment by wanghongenpin** [comment]
> 证书安装正确，其他应用能抓到https的包和对应的response，应用是自己公司的应用，没有上市场，如果要测试我可以加大佬

发下app包呢，我TG: https://t.me/pinsilence
