### ISSUE TITLE
[Android]无法对JavDB抓包

### ISSUE THREAD

**Issue by QINYUUi** [wanghongenpin/network_proxy_flutter#81]
**描述错误**

**To Reproduce**
重现行为的步骤: 如具体应用抓包失败，请说明软件名称以及具体操作页面

**屏幕截图*
https://github.com/bdvajstudio/javdb

**Comment by wanghongenpin** [comment]
你这个应用有点黄

**Comment by wanghongenpin** [comment]
我这里是可以得

![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/47ba2a72-a739-457a-ab34-63b5ac87194d)

**Comment by wanghongenpin** [comment]
你这个应用我打开闪退，其他应用能抓到吗，看下系统证书里有证书么

**Comment by wanghongenpin** [comment]
安装了系统证书，我测试没问题，可以用最新版 检查下证书是否安装到了系统目录，我用模拟器测试也可以
