### ISSUE TITLE
android 10 以下的无法抓包

### ISSUE THREAD

**Issue by tanzhh-bingosoft** [wanghongenpin/network_proxy_flutter#82]

**Comment by wanghongenpin** [comment]
我用模拟器测试没问题，等我买个二手的手机试下

**Comment by wanghongenpin** [comment]
小米安卓8测试可以，请检查版本是否是1.0.5，以及系统证书安装了没有
<img width="342" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/fd424bcc-d81b-419d-935b-32f77269ca51" />

<img width="321" alt="image" src="https://github.com/wanghongenpin/network_proxy_flutter/assets/24794200/9fecd60a-8f09-4b57-b23a-d86c22c65108">
