### ISSUE TITLE
悬浮预览

### ISSUE THREAD

**Issue by lsdlh** [wanghongenpin/network_proxy_flutter#87]
可以增加后台悬浮窗预览抓包吗

**Comment by M17764017422** [comment]
点赞

**Comment by wanghongenpin** [comment]
安卓可以，ios好像没有对应API，只有视频可以小窗口

**Comment by wanghongenpin** [comment]
安卓可以，ios好像没有对应API，只有视频可以小窗口

**Comment by lsdlh** [comment]
> 安卓可以，ios好像没有对应API，只有视频可以小窗口

目前使用安卓

**Comment by wanghongenpin** [comment]
1.0.6版本已经发布，安卓支持小窗口，在设置里面关闭
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/1.0.6

**Comment by M17764017422** [comment]
窗口细长，大小固定，且和小米系统的小窗模式不连贯

**Comment by wanghongenpin** [comment]
窗口大小是系统规定死的，只能调整比例，现在只要离开程序就进入小窗口，如果想用系统的小窗口可以从设置里关闭小窗口模式

> 窗口细长，大小固定，且和小米系统的小窗模式不连贯

**Comment by wanghongenpin** [comment]
和系统小窗口不连贯，可以做只有点home键才出发小窗口，切换到任务管理不处罚小窗口

**Comment by M17764017422** [comment]
比例调宽一点点，前台活动界面在全部请求列表就自动关闭悬浮窗

**Comment by wanghongenpin** [comment]
改成按home键进入小窗口模式，和小黄鸟一样， 在应用长按home进入任务管理 不会触发小窗口模式，小窗口模式新增了清理按钮

**Comment by M17764017422** [comment]
> 还发现了一个奇怪的问题，一些地址会在http://换行浪费显示空间比如：https://
adashbc.ut.taobao.com

![IMG_20231223_125024.jpg](https://github.com/wanghongenpin/network_proxy_flutter/assets/31874069/0395e6ed-4dc8-4ec4-b217-c3ade0516e10)

**Comment by wanghongenpin** [comment]
这个系统文本组件都会优化换行，防止单词分行展示，最新包已经做了特殊处理

> > 还发现了一个奇怪的问题，一些地址会在一些符号位置提前换行，浪费显示空间比如：https://
> > adashbc.ut.taobao.com
