### ISSUE TITLE
[IOS]重大BUG还是重大特性？

### ISSUE THREAD

**Issue by 17633912479** [wanghongenpin/network_proxy_flutter#88]
**描述错误**
任意请求 点击请求重发 然后编辑某一个请求头或者请求体点击修改  然后切换后台到任意应用  此时切换回ProxyPin   就会发现刚刚修改过的请求头或者请求体就会恢复为原始的请求 并不是我修改之后的
**To Reproduce**
百分百复现  我并没有退出请求重发界面
**屏幕截图*

**Comment by 17633912479** [comment]
https://github.com/wanghongenpin/network_proxy_flutter/assets/91017562/0626c792-3046-47fe-86a8-6740e66a7d28

**Comment by wanghongenpin** [comment]
近期会发版修复

**Comment by 17633912479** [comment]
> 近期会发版修复

有些时候开启抓包会断网  就是必须切换软件再切换回去 才能正常加载抓到包  过程没有stream丝滑

**Comment by wanghongenpin** [comment]
有时候开启着代理，直接退出 可能没执行关闭vpn方法， 如果软件退出了，但是vpn还开着，手动关下就行

> 有些时候开启抓包会断网 就是必须切换软件再切换回去 才能正常加载抓到包 过程没有stream丝滑

**Comment by 17633912479** [comment]
> 有时候开启着代理，直接退出 可能没执行关闭vpn方法， 如果软件退出了，但是vpn还开着，手动关下就行
> 
> 
> 
> > 有些时候开启抓包会断网 就是必须切换软件再切换回去 才能正常加载抓到包 过程没有stream丝滑
> 
> 
> 
> 

不,你理解错了我的意思是  当你抓包某个app


开启抓包～操作被抓包app（未正常加载发送或响应,卡住的状态）～切换到proxypin～后台的被抓包应用正常加载

**Comment by wanghongenpin** [comment]
1.0.6TF已经发版
