### ISSUE TITLE
全部请求列表允许为链接添加颜色标记

### ISSUE THREAD

**Issue by M17764017422** [wanghongenpin/network_proxy_flutter#89]
用户可以通过长按为一个地址添加颜色高亮显示，方便观察关键链接流程。
就是给几个关键地址添加不同的颜色标记。形式不重要，字体颜色、背景颜色都可以。

**Comment by M17764017422** [comment]
至少以域名为单位标记颜色应该不难

**Comment by wanghongenpin** [comment]
是把某个请求标记颜色吗

**Comment by M17764017422** [comment]
> 是把某个请求标记颜色吗

是的，就像现在的添加收藏一样，安卓手机版

**Comment by M17764017422** [comment]
抓包过程中，一般只有少部分关键请求地址是有意义的，将它们标记成不同的颜色，然后刷新，观察请求流程和连接顺序

**Comment by wanghongenpin** [comment]
有两种方案，第一种是把某个请求标记高亮颜色，第二种配置关键词高亮，还有我觉得现在长按请求弹出菜单太多了

> 抓包过程中，一般只有少部分关键请求地址是有意义的，将它们标记成不同的颜色，然后刷新，观察请求流程和连接顺序

**Comment by M17764017422** [comment]
关键字方案应该会更加灵活，只要1请求地址中包含关键字就高亮，关键字可以是正则表达式。
合并重发菜单改成使用脚本，把请求连接相关的功能扩展统一交给用户脚本

**Comment by M17764017422** [comment]
目前是一个重放功能占用了三个菜单，复制链接占用两个菜单

**Comment by wanghongenpin** [comment]
1.0.8-Beta支持请求高亮，后续再增加根据关键词高亮

https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.0.8-Beta

**Comment by M17764017422** [comment]
> 抓包过程中，一般只有少部分关键请求地址是有意义的，将它们标记成不同的颜色，然后刷新，观察请求流程和连接顺序

试了一下感觉没法用，我希望能够将那些关键的请求地址高亮显示，并为它们分配不同的颜色，以便在刷新页面或重新发起请求后，可以迅速地识别出这些已标记的关键地址。

**Comment by M17764017422** [comment]
> 1.0.8-Beta支持请求高亮，后续再增加根据关键词高亮
> 
> https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/V1.0.8-Beta

好的，有计划就没问题。

**Comment by M17764017422** [comment]
下一版能实现吧？1.0.9版@wanghongenpin

**Comment by wanghongenpin** [comment]
做了个简单版的
https://www.lanzoub.com/ib9mK1q82o1i
密码:1cc7

> 下一版能实现吧？1.0.9版@wanghongenpin

**Comment by wanghongenpin** [comment]
可以下载1.0.9Beta版本
https://github.com/wanghongenpin/network_proxy_flutter/releases/tag/1.0.9-Beta
