### ISSUE TITLE
如何解决安卓手机抓包没网的问题

### ISSUE THREAD

**Issue by tvrohd** [wanghongenpin/network_proxy_flutter#9]
小米安卓欧版，已经root，不知道如何设置可以解决抓包没网，请指教

**Comment by wanghongenpin** [comment]
> 小米安卓欧版，已经root，不知道如何设置可以解决抓包没网，请指教

root后开启抓包软件后网站都访问不了么，我没试过手机ROOT，我明天把我红米手机root下试下

**Comment by tvrohd** [comment]
没网 ca证书默认是装在用户里面的 是不是要弄去系统里面才可以？

**Comment by wanghongenpin** [comment]
> 没网 ca证书默认是装在用户里面的 是不是要弄去系统里面才可以？

是手机本身就没网吗，如果配置了wifi代理或者扫码连接，手机没网也可以，因为实际转发到电脑访问的网络
安卓如果想抓所有app，需要把证书安装到系统里，网上一般有教程，文件命名成 243f0bfb.0    名字就是取证书的hash值
