### ISSUE TITLE
[Android] 导出har后fiddler导入报错

### ISSUE THREAD

**Issue by QAQQL** [wanghongenpin/network_proxy_flutter#90]
**描述错误**
我导出一个556记录的历史,成功导出了har,但里面的中文字符全部乱码
由于隐私问题,我无法直接贴出har文件,抱歉,您可以联系我获取

**屏幕截图*
![图片](https://github.com/wanghongenpin/network_proxy_flutter/assets/51136763/fb563cb5-2903-4968-ad45-652f61838ed3)

导出的har
![图片](https://github.com/wanghongenpin/network_proxy_flutter/assets/51136763/1e3a3f84-51d4-4cec-abc6-92dd38c81cc1)
![图片](https://github.com/wanghongenpin/network_proxy_flutter/assets/51136763/a9f9fe12-ea87-4b1c-be2a-7327dd184911)
使用其他编码读取
![图片](https://github.com/wanghongenpin/network_proxy_flutter/assets/51136763/c0bad488-075a-49e0-a7f6-19d40d1dc3d0)
![图片](https://github.com/wanghongenpin/network_proxy_flutter/assets/51136763/3d33c4fe-3cf0-482b-b80e-d8337a5e0595)

files/history/lqdm707r.txt  我的556记录的本地文件
![图片](https://github.com/wanghongenpin/network_proxy_flutter/assets/51136763/5dc646c5-31a2-4958-b6a0-46b377c572bf)
![图片](https://github.com/wanghongenpin/network_proxy_flutter/assets/51136763/2681d3e4-0779-493d-9443-1c17df392a6e)

**Comment by QAQQL** [comment]
您好,我clone了项目,想看看您在flutter中导出的实现逻辑,发现您app的代码好像没上传全,请问方便补充一下吗

**Comment by QAQQL** [comment]
排查中
![图片](https://github.com/wanghongenpin/network_proxy_flutter/assets/51136763/dd674794-ea86-40b7-9269-f9fca6346d6c)

**Comment by QAQQL** [comment]
已确定,我直接导出json对象内容为txt文本,修改后缀为har可以导入fiddler,而var file的值中中文字符为乱码

**Comment by QAQQL** [comment]
修改为
var file = XFile.fromData(const Utf8Encoder().convert(json), name: fileName, mimeType: "har");
临时解决了我的导出问题,麻烦作者排查一下问题的起由,我这边方便配合测试

**Comment by wanghongenpin** [comment]
多谢反馈，之前默认编码是utf16, 已经改成utf-8, 1.0.6版本已经发布

**Comment by QAQQL** [comment]
感谢
