### ISSUE TITLE
[Android]部分请求不显示

### ISSUE THREAD

**Issue by DeltaFlyerW** [wanghongenpin/network_proxy_flutter#91]
**描述错误**
部分http请求不显示

**To Reproduce**
软件: 囧次元(flutter应用) https://mobai0521.lanzouj.com/iHdH91iu0eze
操作页面: 点击进入任意视频页面

**屏幕截图*
![Screenshot_2023-12-24-16-15-23-357_com network proxy](https://github.com/wanghongenpin/network_proxy_flutter/assets/48078918/560c70e3-acc9-4229-b9f5-7bc9f93c3b88)
![Screenshot_2023-12-24-16-18-16-229_com guoshi httpcanary premium](https://github.com/wanghongenpin/network_proxy_flutter/assets/48078918/d28cc712-b560-4563-afe1-6b20edfbdf7b)

**Comment by wanghongenpin** [comment]
试下这个包呢
https://f.ws59.cn/f/czh6u85sons

**Comment by wanghongenpin** [comment]
重新1.0.6的包，我自测没问题了
