### ISSUE TITLE
【脚本功能】在脚本功能功能中，怎么调试脚本

### ISSUE THREAD

**Issue by guominfang** [wanghongenpin/network_proxy_flutter#93]
在脚本功能功能中，怎么调试脚本，

async function onResponse(context, request, response) {
    // 更新或添加新标头 
    // response.headers["Name"] = context["name"];

   // 想在这里获取 reuest.path 来判断是不是需要捕获的请求
   //根据文档的描述，应该是获取请求路径，目前获取不正确
    let c = geConfig(request.path);
  

    //var body = JSON.parse(response.body);
    //body['key'] = "value";
    //response.body = JSON.stringify(body);
    return response;
}

**Comment by wanghongenpin** [comment]
request.path 是 /api/get 包含url参数， 后续增加脚本日志

**Comment by guominfang** [comment]
嗯，这边已经通过，在响应头里面，返回这个path来查看，path到底是啥
