### ISSUE TITLE
[IOS］快速退出抓包软件无法上网

### ISSUE THREAD

**Issue by ghost** [wanghongenpin/network_proxy_flutter#95]
**描述错误**
请看VCR
**To Reproduce**
所有应用都会出现的情况,极大影响使用体验
使用了好几个月 一直未被修复的bug继自动恢复请求内容后
**屏幕截图*

**Comment by Yzyxmm** [comment]
发不了视频/裂开

**Comment by Yzyxmm** [comment]
https://cloud.189.cn/t/IBJVz2FfIrEj（访问码：bd68）

视频  希望作者能够重视吧

**Comment by wanghongenpin** [comment]
1. 开启抓包后，上不了网切到抓包软件才出现请求 这个是必现的吗
2. 停止抓包，还有网络这个应该是App有些缓存，因为已经调用停止VPN API，如果影响体验，可以做非开启抓包状态拦截到了流量不做展示，直接转发。

**Comment by Yzyxmm** [comment]
> 1. 开启抓包后，上不了网切到抓包软件才出现请求 这个是必现的吗
> 
> 2. 停止抓包，还有网络这个应该是App有些缓存，因为已经调用停止VPN API，如果影响体验，可以做非开启抓包状态拦截到了流量不做展示，直接转发。

1. 开启抓包后，上不了网切到抓包软件才出现请求 这个是必现的吗？

答： 复现概率百分之80。
可能的原因： 好像是因为,开启抓包后快速退出抓包软件好像是有概率会发生,stream也有时候会有类似的症状但是复现概率可能只有百分之1

2. 停止抓包，还有网络这个应该是App有些缓存，因为已经调用停止VPN API，如果影响体验，可以做非开启抓包状态拦截到了流量不做展示，直接转发。

答： 建议做   非开启抓包状态拦截到了流量不做展示，直接转发。
 因为 无论是黄鸟蓝鸟还是所有的抓包软件都是这样  或者增加一个开关


一些小的建议

请求展示界面（也就是抓到的包界面）还有一些别的界面的按钮点击反馈 可以做的强一点 还有黄鸟的红点策略 点击观看后 红点消失

**Comment by wanghongenpin** [comment]
我用最新版本测试不会出现了，请使用最新版本
