### ISSUE TITLE
[Windows]-[请求重写]-[替换响应]数据后，chrome提示异常

### ISSUE THREAD

**Issue by SuperRonin** [wanghongenpin/network_proxy_flutter#97]
**描述错误**

1.   本地开发web网页，启动了172.16.1.75:9528端口
2.   配置响应重写接口 http://172.16.1.75:9528/epr/web/todo  返回数据为`{a:1}`
3.   chrome控制台提示：http://172.16.1.75:9528/epr/web/todo?id=11018 net::ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_LENGTH

**屏幕截图*
![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/22882883/69f784c9-104e-4a2e-8545-fa8cd31c893e)

![image](https://github.com/wanghongenpin/network_proxy_flutter/assets/22882883/79504293-7829-4530-aa97-4a2a275c1d30)

**Comment by wanghongenpin** [comment]
你重写了header吗，content-length有两个

**Comment by SuperRonin** [comment]
> 你重写了header吗，content-length有两个

并没有重写header，只写了body数据，我尝试将翻墙软件关闭后也无果

**Comment by SuperRonin** [comment]
> 你重写了header吗，content-length有两个

奥，一开始我以为是没有指定content-length的原因，后来确实尝试加了这个参数，但是无果，截图可能是贴错了。

**Comment by wanghongenpin** [comment]
重新下载下1.0.6的包那，刚重新打了个包

**Comment by wanghongenpin** [comment]
重新下载1.0.6的包那，刚重新打了个包

**Comment by SuperRonin** [comment]
> 重新下载1.0.6的包那，刚重新打了个包

1.0.6版本我试了可以了👍

另外有个疑问，比如还是我这个地址172.16.1.75:9528，如果开启了代理，在加载网页时，静态资源还是会抛出如下异常

http://172.16.1.75:9528/static/js/chunk-vendors.js net::ERR_EMPTY_RESPONSE

**Comment by wanghongenpin** [comment]
你这个文件我访问不了，没办法测试，请求重写什么的有冲突吗
> 
> 另外有个疑问，比如还是我这个地址172.16.1.75:9528，如果开启了代理，在加载网页时，静态资源还是会抛出如下异常
> 
> http://172.16.1.75:9528/static/js/chunk-vendors.js net::ERR_EMPTY_RESPONSE
